i3df/build.rs
i3df/src/lib.rs

This reduces the build time from 60 s to 6 s when files like
i3df/src/renderables.rs change, making the feedback loop a lot more
comfortable to work with. In addition, it reduces the build time for initial builds by extracting certain functions to reduce duplication in the generated file.

Improve build speed

---

.travis.yml

Fix a typo in .travis.yml to enable the cargo cache and delete wasm-pack binary before installation. Otherwise, the build will be stalled while the wasm-pack installer is waiting for user input to allow overwriting the binary. Also set npm cache to true.

Enable cargo cache in .travis.yml

---

viewer/rust/lib.rs

Turns out overriding alloc_zeroed to call alloc is in fact dangerous and
leads to corrupted data. This change removes the custom allocator.

Do not override allocator

---

viewer/src/views/threejs/utilities.ts

Otherwise, the result might be unused.

Write to `out` in fromThreeMatrix

---

viewer/src/examples/threejs/simple.ts
viewer/src/utils/Box3.ts
viewer/src/utils/cameraUtils.ts

Previously Box3.center() would scale only the max value by 0.5 and not
the sum of the max and min value.

Improve camera suggestion and fix Box3 center

---

viewer/src/views/threejs/sector/instancedMeshes.ts
viewer/src/views/threejs/sector/triangleMeshes.ts

We cannot assume that the data in the original model has proper face
culling set up and need to draw both sides.

Draw all meshes double sided

---

viewer/src/models/sector/parseSectorData.ts

Previously, we would read from the array of all meshes with the wrong
offset. This caused some geometry not to render correctly.
Fixes RJ3D-541

Read the triangle counts from the correct mesh

---

examples/public/primitives/uploaded_sectors_simple.txt

Otherwise, the simple example with primitives no longer works.
The contents are not important since the primitives scene currently does
not have any simple sectors.

Add dummy uploaded_sectors_simple.txt

---

viewer/tsconfig.json

This avoids the error message
Uncaught SyntaxError: Cannot use import statement outside a module
which was caused by parser.worker.js being placed under dist/workers and
then copied into the examples.

Keep running tsc from putting files in the dist folder

---

viewer/src/models/cad/parseSectorData.ts
viewer/src/workers/parser.worker.ts
viewer/src/workers/types/parser.types.ts

Previously, we would allocate arrays large enough to contain color and tree index information about all other meshes for each mesh.

Share color and tree index arrays between meshes

---

.dependabot/config.yml

This should keep dependabot from creating a large number of PRs that take
forever to merge into master because they need to be rebuilt every time
another PR has been merged. Instead, we ask dependabot to pull all these
updates into a new branch, called dependency-updates and merge them
immediately because this branch has no protection.
We will then need to manually create a PR from this branch into master
once a week.

Make dependabot push changes to unprotected branch

---

examples/webpack.config.js

Enable debugging of Reveal through examples.

Fix Reveal library source maps in examples

---

viewer/src/views/threejs/cad/materials.ts

Previously, the wrong number of elements were initialized to 255,
which lead the all nodes above a certain tree index number to be
initialized as hidden. This change ensures all nodes are visible by
default.

Actually fill the entire array of visibility

---

examples/package-lock.json
examples/src/filtering.ts
examples/src/picking.ts
examples/src/post-processing-effects.ts
examples/src/sector-with-pointcloud.ts
examples/src/side-by-side.ts
examples/src/simple.ts
examples/src/ssao.ts
examples/src/utils/loaders.ts
examples/src/world-to-screen.ts
viewer/src/models/cad/parseSectorData.ts

Resolves an issue where user was sent in an infinite login loop.

Initialize CogniteClient once in examples that load multiple models

---

examples/src/custom-scene-elements.ts
examples/src/filtering.ts
examples/src/picking.ts
examples/src/post-processing-effects.ts
examples/src/sector-with-pointcloud.ts
examples/src/side-by-side.ts
examples/src/ssao.ts
examples/src/two-models.ts
examples/src/walkable-path.ts
examples/src/world-to-screen.ts

This is necessary for the models to load and draw on the first frame.

Adapt examples to new update API in CadNode

---

.travis.yml

Unless we are building for a release branch, we will only make debug
builds, which are significantly faster than release builds. In addition,
we will only target Node 10 to reduce build times.

Speed up Travis builds by building debug and dropping Node 10

---

examples/src/migration.ts

The model will created inside `addModel` anyways and the `model` reference was to an unused object.

Do not create model twice in migration examples

---

scripts/verify-package-lock.sh

dependencies' was replaced with 'requires' after npm install. See https://stackoverflow.com/questions/52926922/package-lock-json-requires-vs-dependencies

Accept 'requires' dependencies in package-log.json in addition to 'dependencies'

---

examples/src/migration.ts
examples/template-single-canvas.ejs
viewer/package-lock.json
viewer/package.json
viewer/src/migration/Cognite3DViewer.ts
viewer/src/views/threejs/cad/CadNode.ts

This implements the same API as in the original viewer for click events
and sets the color of a clicked node in the migration example.
Also, offset the canvas a little more to make sure we detect offset bugs
while testing.

Add support for getting intersection from click in migration wrapper

---

viewer/src/models/cad/parseSectorData.ts

Previously, we used the wrong index when assigning the tree index
attribute for merged meshes.

Fix tree index attribute in merged mesh

---

viewer/src/cache/MemoryRequestCache.ts
viewer/src/cache/RequestCache.ts

Keep a maximum number of elements in the cache and evict based on last accessed. Attempt to reduce memory footprint.

Introduce a limit on number of elements in the cache

---

viewer/rust/lib.rs

Instead of relying on Vec to be converted to equivalent arrays,
just specify the type of JS object we want directly.

Align CTM parsing with the others

---

examples/tslint.json
viewer/tslint.json

Disable perfer-for-of tslint rule that encourages `for (const element of ...)` over `for (let i = 0; ...)` since `for (let i=0; ...)` is [a lot faster](https://www.incredible-web.com/blog/performance-of-for-loops-with-javascript/).

Disable prefer-for-of

---

f3df/src/bin/dump.rs
f3df/src/renderables.rs
f3df/tests/integration.rs
i3df/build.rs
i3df/src/bin/dump.rs
i3df/src/lib.rs
i3df/src/renderables.rs
viewer/rust/lib.rs
viewer/src/glsl/base/updateFragmentDepth.glsl
viewer/src/glsl/sector/primitives/cone.frag
viewer/src/glsl/sector/primitives/eccentricCone.frag
viewer/src/glsl/sector/primitives/ellipsoidSegment.frag
viewer/src/glsl/sector/primitives/generalCylinder.frag
viewer/src/glsl/sector/primitives/sphericalSegment.frag
viewer/src/views/threejs/cad/materials.ts

This PR fixes two issues:
1. BigUInt64Array is not supported on Safari/iOS - use u32 over u64 structs exposed by Rust
2. Avoid using gl_FragDepthEXT when WebGL extension is unavailable.

Fix issues causing viewer not to work on iOS

---

examples/src/filtering.ts
examples/src/picking.ts
examples/src/post-processing-effects.ts
examples/src/sector-with-pointcloud.ts
examples/src/simple.ts
examples/src/ssao.ts
examples/src/utils/loaders.ts
examples/src/world-to-screen.ts
examples/webpack.config.js

Route all requests through CDF through a webpack-dev-server proxy to work around CORS issues accessing CDF from LAN (i.e. when not using localhost, such as from phones/tables)

Route CDF requests through webpack-dev-server proxy

---

examples/src/utils/loaders.ts
examples/webpack.config.js

Fixes an issue where the user was sent in eternal login loop when opening examples that loaded data from CDF.

Disable proxy in webpack dev server as it caused eternal login loops.

---

viewer/README.md

Nothing more but steps to run reveal in create-react-app.

doc(readme): mention how to handle .wasm and .worker.js files when reveal is used

---

.gitignore
examples/README.md
viewer/package-lock.json
viewer/package.json

Since examples/public is also used to store local models - ignore it.
Also, fixed viewer `npm run serve` script for local development.
Updated examples/readme.md

chore(.gitignore): add examples/public with exceptions

---

README.md

Port is also changed from 8080 to 3000. I see port 8080 is specified in `examples/.env.example`, but the server as started by `npm run serve` starts at port 3000. Is this a bug?

Update README to reflect new location of the serve script

---

examples/src/pages/DistanceMeasurement.tsx
viewer/src/__tests__/migration/Cognite3DViewer.test.ts
viewer/src/public/migration/Cognite3DViewer.ts

* add methods from old 3d viewer to add/remove Object3D on scene
* Fixed hardcoded local reveal manager in distance measurement example.
~Part of code with `additionalObjects` isn't used for now, so I kept it but commented out.~

Cognite3DViewer: implement basic addObject3D/removeObject3D + minor examples fix

---

examples/src/pages/Simple.tsx
viewer/src/datamodels/cad/sector/CachedRepository.ts
viewer/src/public/LocalHostRevealManager.ts
viewer/src/public/RevealManager.ts
viewer/src/public/RevealManagerBase.ts
viewer/src/public/migration/Cognite3DViewer.ts

I noticed that after example is left and everything is unmounted, reveal still requesting stuff in the queue and that's not necessary.

fix(RevealManager): add dispose() method

---

viewer/rust/lib.rs
viewer/src/utilities/workers/parser.worker.ts

I'm not expecting (or measuring..) a significant performance gain, but it's a nice simplification that removes a struct type and removes a function call in ts, in addition to having more consistent naming with f3d.

Remove unnecessary struct wrapping and double entry into wasm when parsing an i3d sector

---

viewer/src/public/migration/Cognite3DViewer.ts

Fixes an issue causing e.g. highlighted objects which should be rendered in front of other objects to be rendered like 'regular objects'

Post rendering effects (e.g. highlighting) now works with the Cognite3dViewer.getScreenshot()

---

viewer/src/index.ts

Need that type for the console, to be able to setup colortype picker.

ts(viewer): export PotreePointColorType as public

---

examples/src/pages/SimplePointcloud.tsx
viewer/src/__tests__/viewer/public/RevealManagerBase.test.ts
viewer/src/datamodels/cad/sector/CachedRepository.ts
viewer/src/datamodels/pointcloud/PointCloudManager.ts
viewer/src/datamodels/pointcloud/PotreeLoadHandler.ts
viewer/src/public/RevealManager.ts
viewer/src/public/migration/Cognite3DViewer.ts
viewer/src/utilities/Spinner.ts

* fix spinner styles
* implement loading state logic for pointCloudManager
Now the spinner should always be here for Cognite3dViewer and play well with `revealManager.on('loadingStateChange', ...`

Add spinner for pointcloud; fix spinner styles

---

viewer/src/__tests__/viewer/public/RevealManagerBase.test.ts
viewer/src/datamodels/cad/CadManager.ts
viewer/src/datamodels/pointcloud/PointCloudManager.ts
viewer/src/datamodels/pointcloud/PotreeGroupWrapper.ts
viewer/src/public/RevealManagerBase.ts
viewer/src/public/migration/Cognite3DModel.ts
viewer/src/public/migration/Cognite3DViewer.ts
viewer/src/public/migration/CogniteModelBase.ts
viewer/src/public/migration/CognitePointCloudModel.ts

This works for me to implement edit rotation in the console. So I can do the following:
```ts
model.updateTransformation(rotationMatrix);
viewer.forceRerender();
```
An alternative implementation I think would be to have render trigger right in `updateTransformation` function. Which in turn should do something like
```ts
// for CognitePointCloudModel
updateTransformation(matrix: Matrix4): void {
this.applyMatrix4(matrix);
this.updateMatrixWorld(false);
this.potreeNode.requestRedraw()
}
// for Cognite3dModel
updateTransformation(matrix: Matrix4): void {
this.cadNode.applyMatrix4(matrix);
this.cadNode.updateMatrixWorld(false);
this.cadNode.requestRedraw()
}
```
But I just thought maybe it would be convenient to have that forceRedraw fn for some other cases. So left like that.

feat(Cognite3dViewer): add `forceRerender(): void`

---

viewer/src/__tests__/setupJest.ts
viewer/src/__tests__/views/threejs/cad/picking.test.ts
viewer/src/utilities/networking/types.ts

Get rid of warning from initialization of THREE.WebGLRenderer about missing extensions during unit testing.

Remove warning spam from ThreeJS in tests

---

Cargo.lock
examples/README.md
examples/yarn.lock
viewer/package.json
viewer/yarn.lock

* Removed manual viewer/dist linking in serve script. It's already specified as a linked dependency in examples/package.json
* Remove cognite sdk from package dependencies, it shouldn't be there since it's in peer + devDependencies already. 
* I noticed all lock files got updates after dependency update got merged, so committed them.

chore: simplify viewer's `serve` script; update .lock files

---

viewer/.eslintrc.js
viewer/package.json

I decided to just run tsc on lint to check for various ts errors uncaught by the linter, and specifically, for unused vars. 
If I enable eslint rule for unused vars it works poorly with our `(_unused, args) => ...`. And in general, there is some mess with unused vars and typescript in eslint. Hopefully, it will be resolved someday, but for now, I think running tsc is a good thing. 
See [related issue ](https://github.com/typescript-eslint/typescript-eslint/issues/1856):
> This is never something we invested much time into for a number of reasons like:
> * most of the rules that use the scope manager are either infrequently used, or have analogous checks/options in the TypeScript itself,
> * we wanted to be careful that we wouldn't implement something that would get outdated by changes to …

chore: check for unused vars and ts errors on lint

---

examples/package.json
examples/yarn.lock

I just realized that in the same way we link local viewer in examples, we might have a link on the viewer's installed cognite/sdk. That allows us to forget about different versions.

chore(examples): link the same sdk viewer uses, to avoid version conflicts

---

.editorconfig
openctm/src/bin/dump.rs
openctm/src/lib.rs
openctm/tests/box.rs
viewer/rust/lib.rs

Implemented the features we actually use for MG2 encoded OpenCTM files. It doesn't work flawlessly with the way we reference ctm files from i3d files (at the moment). The colors are stored in the i3d file and dependent on the vertex ordering in the ctm file, which isn't preserved with MG2 compression.
MG1 compressed ctm files with colors from i3d file:
MG2 compressed:
Even though it doesn't work that great with i3d, the parsing logic checks out. Making it work with colors is a large undertaking involving changing the i3d format, new finalize logic, and optimizer changes.

Initial OpenCTM MG2 compression support

---

i3df/src/renderables.rs
viewer/rust/lib.rs

There are still some unwrap calls in the primitive modules (for rotate_between), but I'm not sure how recoverable they are in that code and bubbling them up to JS would require a lot of refactoring.

Reduce the use of unwrap to avoid panics in the workers

---

viewer/src/datamodels/cad/parsers/CadMetadataParserV8.ts

This allows us to view models where the bounding box corners for some sectors are NaN

Workaround for broken scene.json files

---

viewer/src/datamodels/cad/rendering/EffectRenderManager.ts

See https://jsben.ch/zRusx for performance comparison. This code was a hotspot in the code for rendering highlighted objects and hence worth the effort to optimize.

fix: optimize hasIntersection() by using iterator instead of forEach().

---

viewer/src/datamodels/cad/CadManager.ts
viewer/src/public/migration/RenderController.ts

Fixes a bug causing highlight node to not trigger redraw.

fix: trigger redraw when CadNode is 'updated' (e.g. when a node is highlighted)

---

documentation/docs/migration-guide.md
examples/src/pages/Migration.tsx
viewer/src/__tests__/migration/Cognite3DViewer.test.ts
viewer/src/public/migration/Cognite3DViewer.ts

It should a bit simplify the usage of Cognite3DViewer when type doesn't really matter. Also, now `addModel` truly adds any model and we have explicitly declared addCadModel as we have for addPointCloudModel. 
I actually think that the reveal manager should have the same API instead of an overloading addModel.

feat(Cognite3DViewer): add model now returns any supported model type

---

viewer/src/datamodels/base/SupportedModelTypes.ts
viewer/src/datamodels/base/index.ts
viewer/src/datamodels/cad/CadManager.ts
viewer/src/datamodels/cad/CadModelFactory.ts
viewer/src/index.ts
viewer/src/migration.ts
viewer/src/public/RevealManager.ts
viewer/src/public/migration/Cognite3DModel.ts
viewer/src/public/migration/Cognite3DViewer.ts
viewer/src/public/migration/CogniteModelBase.ts
viewer/src/public/migration/CognitePointCloudModel.ts
viewer/src/public/migration/types.ts
viewer/src/public/types.ts

Replaced `SupportedModelTypes` enum with type union to avoid strings that mimic enum values in revealManager.addModel. Also removed NotSupported `''` from that type because it doesn't really make sense to have it in type that declares supported stuff.

refactor(SupportedModelTypes): use type union, remove NotSupported

---

viewer/tsconfig.json

Shuts up this message from jest. We don't really need to stick with esnext, es2019 should be quite enough. 
> ts-jest[config] (WARN) There is a mismatch between your NodeJs version v12.18.3 and your TypeScript target esnext. This might lead to some unexpected errors when running tests with `ts-jest`. To fix this, you can check https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping

chore(viewer): set target es2019 to get rid of jest warn

---

.github/workflows/ci.yml
documentation/package.json
documentation/yarn.lock
viewer/src/public/types.ts

* Added a CI step to check docs build failures. 
* Added tsconfig from viewer to allow resolving of `@` aliases (no idea at all why it was working before).

Documentation: fix alias resolving, run build on PR

---

viewer/src/public/migration/Cognite3DModel.ts

When `includeDescendants=true`, then `determineTreeIndices` can return an empty `NumericRange`, so nothing will be applied to the original `treeIndex`.

Fix determineTreeIndices

---

viewer/src/public/migration/Cognite3DModel.ts

Temporary placeholder until endpoints on the backend are available.

fix: add not-implemented placeholder for Cognite3DModel.mapTreeIndicesToNodeIds()

---

documentation/docs/examples/cad-colors.mdx
viewer/src/public/migration/Cognite3DViewer.ts

This fixes an issue causing 2D HTML overlays to be appearing to "lag behind" when they their position was updated when Cognite3DViewer triggered 'cameraChanged'.

fix: issue causing worldToScreen() returning wrong values when camera is being moved

---

viewer/jest.config.js
viewer/tsconfig.test.json

- errors will still be catched by lint step

chore: make jest config more forgiving to avoid lint errors during development

---

.github/workflows/ci.yml
documentation/package.json

Rather than using a public NPM package, embed Reveal in the doc. I believe this is the right thing because:
- It allows us to publish nightly documentation
- It allows us to create a PR documentation server for viewing the doc for a feature being developed
- It avoids doc that is not in sync with our codebase

doc: embed current Reveal in documentation, rather than a fixed version

---

.github/workflows/preview-documentation.yml

Deploy documentation to a Github pages site and post a comment about the URL. Uses repository https://github.com/cognitedata/reveal-docs-preview to store the preview docs.

chore: deploy preview documentation on PR build

---

viewer/src/public/migration/Cognite3DViewer.ts

Fixes an issue on iOS causing viewport to be invalid.

fix: use current renderer pixel ratio instead of device pixel ratio when setting canvas size

---

.github/workflows/ci.yml

parser-worker CI with rust etc will run only if there are some changes under the parser-worker folder.

chore: split CI for parser-worker

---

documentation/src/theme/Navbar/index.tsx
documentation/src/theme/Navbar/styles.module.css
documentation/tsconfig.json

OK, this is quite lame but it lets us have some content in that left sidebar on mobile. 
I simply copied HTML content from the right-bottom sidebar into the top-left sidebar. 
Why it's bad - see comments:
```
// Since it's dummy HTML copying – links are common <a> tags and won't be handled by the app.
// It means the page will be reloaded every time one of these links is clicked (like in multipage or common websites, i.e. not SPA).
// Also, 'active' state classes are removed from here because they won't be updated that way
``` 
Also, it's just not recommended to swizzle sidebar, because it is an internal component. 
Anyway, I just hope that we will have some more links for the navbar later (e.g. versions). And that won't look so empty. And then I'll remove these hacks.

fix(docs): duplicate sidebar content to avoid having almost empty navbar on mobile

---

documentation/docs/examples/cad-colors.mdx

We've switched CAD model and the tree index has changed

doc: update tree index used in color example

---

.github/workflows/preview-documentation.yml

Minimizes the chance of another PR pushing docs while building docs (which causes deploy to fail).

chore(build): await checking out preview docs repo untill build is ready

---

viewer/package.json
viewer/src/utilities/networking/CogniteClientNodeIdAndTreeIndexMapper.ts
viewer/src/utilities/networking/utilities.ts

1) dependency on cognite/sdk - we shouldn't use HttpError to avoid having @cognite/sdk module as a direct dependency for the reveal. Well, it's arguable, but it's a quick fix for this problem https://github.com/cognitedata/cdf-hub/pull/687/files#r489204315. 
And, by the way, the guys from cognite-sdk-js mark [HttpError with `@hidden` annotation](https://github.com/cognitedata/cognite-sdk-js/blob/master/packages/core/src/httpClient/httpError.ts#L5), perhaps it shouldn't be used outside (but it is used outside of sdk, not only in reveal). 
2) I set 0.117.x as the version range for the three.js to avoid warning when 117.1 is installed instead of 117.0 in projects that use reveal.
But should we move three.js under common dependencies? It’s a dependency. We use it directly and even re-export …

fix(viewer): avoid direct dependency on sdk; loose three.js peer dependency version

---

documentation/package.json
documentation/yarn.lock
viewer/src/index.ts
viewer/src/public/migration/CognitePointCloudModel.ts
viewer/src/public/migration/types.ts

I wanted to fix more broken links than only one (if you search for `{@link` in [API reference](https://cognitedata.github.io/reveal-docs/docs/API%20Reference) you'll see them all), but I don't really know why some types are not included in typedoc output now. Created a task in miro for taking a look at that later.

fix: export PotreePointSizeType enum; docs(Intersection): fix broken link

---

viewer/src/glsl/post-processing/edge-detect-combine.frag

Can be tested with the following snippet in docs:
```
model.ghostAllNodes();
model.unghostNodeByTreeIndex(409228, applyToChildren=true);
const box = new THREE.BoxGeometry(10, 10, 10);
const material = new THREE.MeshBasicMaterial({color: 'white'});
const mesh = new THREE.Mesh(box, material);
mesh.position.set(121.84861758965458, 58.620189040381064, -89.28303211581611);
viewer.addObject3D(mesh);
```
Before this would render the custom object in front of ghosted objects:
Now its blended correctly:

fix: bug causing custom 3d objects always to be rendered in front of ghosted objects

---

viewer/src/datamodels/pointcloud/PointCloudNode.ts
viewer/src/public/migration/CognitePointCloudModel.ts

Diff looks a bit weird to me (looks like auto-fix from the linter is applied)but it's only about 
```diff
- getClasses(): number | WellKnownAsprsPointClassCodes[] {
+ getClasses(): Array<number | WellKnownAsprsPointClassCodes> {
```

fix(CognitePointCloudModel): getClasses return type

---

viewer/src/public/migration/Cognite3DViewer.ts

THREE.Scene.dispose() now only outputs an error to console (not fatal).

fix: don't call decrecated function THREE.Scene.dispose

---

viewer/src/__tests__/migration/NodeStyleUpdater.test.ts
viewer/src/__tests__/utilities/NumericRange.test.ts
viewer/src/public/migration/Cognite3DModel.ts
viewer/src/public/migration/NodeStyleUpdater.ts
viewer/src/utilities/NumericRange.ts

This improves performance when the user repeatedly calls `Cognite3dModel.setNodeColorByTreeIndex` and other node style modification functions by batching calls to `requestNodeUpdate`.
A good test case is the following (which can be used in the documentation):
```
const start = performance.now();
const promises = [];
for (let i = 0; i < 1000000; i++) {
promises.push(model.setNodeColorByTreeIndex(i, 255, 255, 255));
}
Promise.all(promises).then(() => {
window.alert('Took ' + (performance.now() - start) + ' ms');
});
```
In my test the time is reduced from 4.5 s to about 1 s.

fix: improve performance of all node styling functions in Cognite3DModel

---

documentation/docs/migration-guide.md
examples/src/pages/DistanceMeasurement.tsx
examples/src/pages/Filtering.tsx
examples/src/pages/Migration.tsx
examples/src/pages/Picking.tsx
examples/src/pages/SSAO.tsx
examples/src/pages/SectorWithPointcloud.tsx
examples/src/pages/SideBySide.tsx
examples/src/pages/Simple.tsx
examples/src/pages/SimplePointcloud.tsx
examples/src/pages/Testable.tsx
examples/src/pages/TwoModels.tsx
examples/src/pages/WalkablePath.tsx
viewer/src/__tests__/viewer/public/RevealManager.test.ts
viewer/src/index.ts
viewer/src/public/RevealManager.ts
viewer/src/public/createRevealManager.ts
viewer/src/public/migration/Cognite3DViewer.ts
viewer/src/public/migration/types.ts
viewer/src/utilities/metrics.ts
viewer/src/utilities/networking/CdfModelDataClient.ts
viewer/src/utilities/networking/LocalModelDataClient.ts
viewer/src/utilities/networking/types.ts
viewer/src/utilities/networking/utilities.ts

Send application ID to MixPanel to be able to see what apps use Reveal. Also, clean up events to avoid duplicates and track when user has navigated to keep a track of the activity per session.

feat: report application ID to MixPanel and improve events

---

viewer/src/utilities/metrics.ts

Avoid sending user identifiable information to MixPanel to comply with GDPR.

fix: avoid sending data to MixPanel that can be used to identify users

---

viewer/src/utilities/spinnerStyles.css

`box-sizing: border-box` should be set. Usually, apps set it globally for everything, but not always though. It affects spinner size.

fix: adjust spinner styles

---

viewer/package.json

we updated it in dev dependencies but it remains fixed to 0.117.x in peers. It causes an unmet peer dependency warning if newer of three.js is installed.

chore: update three.js version in peer dependencies

---

examples/src/pages/Migration.tsx
viewer/package.json
viewer/src/__tests__/models/cad/SectorScene.test.ts
viewer/src/datamodels/cad/sector/SectorScene.ts
viewer/src/datamodels/cad/sector/types.ts
viewer/src/public/migration/Cognite3DModel.ts
viewer/src/public/migration/Cognite3DViewer.ts
viewer/src/public/migration/CogniteModelBase.ts
viewer/src/utilities/Box3.ts
viewer/yarn.lock

This avoids many cases where fitToModel() zooms out to an "empty view" because there are junk geometry far away from the main model.
Examples (left is before, right after):

feat: fitCameraToModel now uses K-means clustering for determining bounds of CAD models

---

documentation/docusaurus.config.js
documentation/yarn.lock

The search index is updated every 24h. 
~Works like a charm~ even at localhost. Doesn't look good in PR previews though. Base path issues. We have `/reveal-docs` as the base path, but in PR previews it should be different to work right. Anyway, should be fine in prod version 😄 
I also tried to upgrade docusaurus to a newer version but they got search broken at alpha.70. I reported it to the docusaurus team and probably will upgrade things later once they have it fixed.
The API key is not a secret. It supposed to be placed in js script at the page body, so I think it's fine to have it just the way it is now.

docs: add algolia search

---

.github/workflows/ci.yml

This reverts commit 1fc957e48ab1e5d8c2a87a9b651bca3922d5eca0.
The plugin is too chatty and ends up being spam.

Revert "chore: report NPM package size in CI builds (#1326)"

---

f3df/src/renderables.rs
i3df/src/renderables.rs
parser-worker/package.json
parser-worker/webpack.config.js
parser-worker/yarn.lock

While testing CSP thingies updated parser-worker webpack version. Looks fine. 
My changes have nothing to do with the rust (I've just updated the webpack) but I see build failure with some warnings, so removed that 'unnecessary cast'
<details>
<summary>The error (a warning actually)</summary>
```
error: casting integer literal to `u8` is unnecessary
--> openctm/src/lib.rs:165:36
|
165 |         let mut packed_data = vec![0 as u8; packed_data_size_with_header];
|                                    ^^^^^^^ help: try: `0_u8`
|
= note: `-D clippy::unnecessary-cast` implied by `-D warnings`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_cast
error: casting integer literal to `u8` is unnecessary
--> openctm/src/lib.rs:170:31
|
170 | …
```

chore(parser-worker): use webpack5

---

documentation/docs/installation.mdx
documentation/versioned_docs/version-1.x/installation.mdx
viewer/src/__tests__/dataModels/cad/internal/CadModelUpdateHandler.test.ts

Mentioning cdf-hub-bundles as @sindresh suggested.

 docs: cdf-hub-bundles as an easy option for cognite developers to get parser-worker + remove unused vars in test

---

.dependabot/config.yml

From my experience migration from 4.x to 5.x isn't smooth at all, so I ended up doing a rollback of husky for another project.

chore: ignore husky@5.x updates

---

viewer/src/datamodels/cad/rendering/EffectRenderManager.ts
viewer/src/datamodels/cad/sector/SectorNode.ts
viewer/src/datamodels/cad/sector/sectorUtilities.ts
viewer/src/public/migration/Cognite3DViewer.ts

For a complex model with a lot of individual objects in the scene, this reduces rendering time from ~35ms to ~31 ms:
**Before:**
**After:**

improvement: avoid calling updateMatrixWorld for entire scene graph each frame [REV-129]

---

viewer/src/datamodels/cad/CadManager.ts
viewer/src/datamodels/cad/CadModelUpdateHandler.ts
viewer/src/datamodels/cad/sector/CachedRepository.ts
viewer/src/datamodels/cad/sector/Repository.ts
viewer/src/public/RevealManager.ts
viewer/src/public/migration/Cognite3DModel.ts
viewer/src/public/migration/Cognite3DViewer.ts
viewer/src/public/migration/NodeIdAndTreeIndexMaps.ts
viewer/src/public/types.ts

Updating these maps accounted for 30% of the allocations we do during sector loaded, so we deemed this not worth it.
Note that this can cause us to need more lookups to map between nodeId and treeIndex, but I believe that this isn't a problem in practice, especially since most users are using *ByTreeIndex() functions which doesn't require mapping (expect for fetching bounding boxes and a few exceptions which are rather rare).

improvement: don't update treeIndex<>nodeId maps every time a sector is loaded to avoid allocation hot path

---

viewer/src/datamodels/cad/sector/CachedRepository.ts
viewer/src/utilities/MostFrequentlyUsedCache.test.ts
viewer/src/utilities/MostFrequentlyUsedCache.ts

Before:
`{consumedSectorHit: 516, consumedSectorMiss: 3423, ctmHit: 797, ctmMiss: 176}`
Cache size: 123.435 Kb
After:
`{consumedSectorHit: 516, consumedSectorMiss: 3423, ctmHit: 708, ctmMiss: 265}`
Cache size: 10.791 Kb

improvement: replace huge CTM LRU cache with slim most frequently used cache to save memory

---

examples/src/pages/Migration.tsx
viewer/src/datamodels/cad/sector/SectorNode.ts
viewer/src/tools/DebugLoadedSectorsTool.ts

Recently loaded sectors are colored green, old sectors red.

improvement: add ability to color sector bounding boxes by loaded timestamp for debugging

---

viewer/src/utilities/metrics.ts

chore: don't generate a new distinct_id for each session to avoid high MixPanel costs (#1425)

---

.github/workflows/ci.yml
documentation/docs/examples/cad-3dobjects.mdx
viewer/src/glsl/post-processing/outline-detect-combine.frag

Combined with regular geometry (0.7 opacity):
Combined with ghosted geometry (0.3 opacity):
Combined with highlighted object (0.3 opacity):

feat: add support for transparency in custom objects

---

README.md
documentation/docs/installation.mdx
examples/package.json
examples/src/pages/Migration.tsx
examples/src/pages/e2e/cad/UserRenderTargetTestPage.tsx
examples/yarn.lock
viewer/package.json
viewer/src/datamodels/cad/picking.ts
viewer/src/datamodels/cad/rendering/EffectRenderManager.ts
viewer/src/datamodels/cad/sector/culling/ByVisibilityGpuSectorCuller.ts
viewer/src/datamodels/cad/sector/culling/OrderSectorsByVisibilityCoverage.ts
viewer/src/datamodels/pointcloud/PotreeGroupWrapper.test.ts
viewer/src/datamodels/pointcloud/PotreeGroupWrapper.ts
viewer/src/public/migration/Cognite3DViewer.ts
viewer/src/tools/DebugCameraTool.ts
viewer/src/utilities/WebGLRendererStateHelper.test.ts
viewer/src/utilities/WebGLRendererStateHelper.ts
viewer/yarn.lock

Bump ThreeJS to version 0.125.0 to fix security vunerability 1639. 
See https://www.npmjs.com/advisories/1639
Note! This is a PR for version 1 and the upcoming 1.5.4 hotfix.

chore: bump threejs to v125 (#1421)

---

viewer/package.json
viewer/src/datamodels/pointcloud/PotreeGroupWrapper.ts
viewer/src/public/migration/Cognite3DViewer.ts
viewer/src/public/migration/NodeIdAndTreeIndexMaps.ts
viewer/yarn.lock

I had to defer updating comlink from 4.3.0 -> 4.3.1 as this introduced a regression with parsing sectors.

chore: update direct dependencies

---

viewer/src/utilities/workers/WorkerPool.ts

I made a mistake with version check, 2 mistakes actually 🤦 
1) `in` operator doesn't work on worker. Comlink magic confused me. 
2) Turned out I accidentally uploaded the parser-worker WIP version to cognite CDN as 1.1.0. That's why if you navigate [here](https://apps-cdn.cogniteapp.com/@cognite/reveal-parser-worker/1.1.0/reveal.parser.worker.js) and search for "getVersion" you will find it, but it was originally planned to be a part of 1.1.1 version. But it's not critical at all. It just confused me when I tried to understand why I see that version mismatch error. Turned out it just never worked (see 1)

fix: proper version check of parser-worker

---

viewer/src/utilities/workers/WorkerPool.ts

There is no real worker instance in tests so it falls back to the default version which is 1.1.0.
I'll also cherry-pick it into 1.x after merge

chore: don't check worker version in tests

---

documentation/docs/components/customScope.ts
documentation/src/plugins/remark-runnable-reveal-demo.js
documentation/versioned_docs/version-1.x/examples/cad-2doverlay.mdx
documentation/versioned_docs/version-1.x/examples/cad-3dobjects.mdx
documentation/versioned_docs/version-1.x/examples/cad-basic.mdx
documentation/versioned_docs/version-1.x/examples/cad-colors.mdx
documentation/versioned_docs/version-1.x/examples/cad-explode.mdx
documentation/versioned_docs/version-1.x/examples/cad-ghostmode.mdx
documentation/versioned_docs/version-1.x/examples/cad-highlighting.mdx
documentation/versioned_docs/version-1.x/examples/cad-nodefiltering.mdx
documentation/versioned_docs/version-1.x/examples/cad-transform-override.mdx
documentation/versioned_docs/version-1.x/examples/clipping.mdx
documentation/versioned_docs/version-1.x/examples/combine-models.mdx
documentation/versioned_docs/version-1.x/examples/node-visiting.mdx
documentation/versioned_docs/version-1.x/examples/pointcloud-intersections.mdx
documentation/versioned_docs/version-1.x/examples/pointcloud.mdx

In our docs we use direct import for demo wrappers
```
import { DemoWrapper } from '@site/versioned_docs/version-1.x/components/DemoWrapper';
<DemoWrapper name="Cognite3DViewerDemo" />
```
That's why docs work OK now for 1.x and next. Different versions of reveal used correctly.
But customScope passed to live examples wasn't versioned. Because to create live example we use custom markdown syntax in our docs. 
```md
```jsx runnable
code goes here
```
That `runnable` part is transformed by our `documentation/src/plugins/remark-runnable-reveal-demo.js`. Its responsibility is to convert `jsx runnable` into 
```jsx
import { LiveCodeSnippet } from '...';
<LiveCodeSnippet>{`code goes here`}</LiveCodeSnippet>
```
And LiveCodeSnippet is the component that passes `customScope` to live examples. So …
```

chore: fix customScope for 1.x docs

---

viewer/src/tools/Cognite3DViewerToolBase.ts

This should make the class visible in client projects, avoiding error
```
ERROR: node_modules/@cognite/reveal/tools/HtmlOverlayTool.d.ts:6:10 - error TS2305: Module '"./Cognite3DViewerToolBase"' has no exported member 'Cognite3DViewerToolBase'.
```

fix: remove @internal from Cognite3DViewerToolBase

---

viewer/.eslintrc.js
viewer/src/datamodels/cad/styling/ByAssetNodeSet.ts

noticed class methods camelCase vs PascalCase related comments in one of the review, so added eslint rule to enforce that convention.

chore: add eslint naming rule

---

documentation/docs/examples/cad-styling-custom.mdx

react-live doesn't play well with arrow function that starts with `throw` without brackets

docs: fix example in cad-styling-custom.mdx

---

viewer/package.json
viewer/yarn.lock

We import 'assert', but the module is only a indirect dev dependency so it will fail for clients that have build setups that doesn't include the assert module.

fix: add assert as a direct dependency to make sure it's available in client projects

---

viewer/src/datamodels/cad/styling/AssetNodeCollection.ts
viewer/src/datamodels/cad/styling/IntersectionNodeCollection.ts
viewer/src/datamodels/cad/styling/InvertedNodeCollection.ts
viewer/src/datamodels/cad/styling/PropertyFilterNodeCollection.ts
viewer/src/datamodels/cad/styling/SinglePropertyFilterNodeCollection.ts
viewer/src/datamodels/cad/styling/TreeIndexNodeCollection.ts
viewer/src/datamodels/cad/styling/UnionNodeCollection.ts

This issue causes import to cause compile errors because serialize() is exported in base class, but not implementations.

fix: remove @internal from serialize() implementations

---

documentation/docs/components/LiveCodeSnippet.tsx
documentation/docs/examples/cad-save-viewerstate.mdx
documentation/docs/examples/cad-styling-custom.mdx
documentation/package.json
documentation/yarn.lock
viewer/src/public/migration/Cognite3DModel.ts

basically, the fix for classes here is passing `transpileOptions` to `LiveProvider` as 
```
<LiveProvider
code={children}
transpileOptions={{
transforms: {
classes: false,
asyncAwait: false
}
}}
```
but it's not supported in react-live (at least yet, but I made a [PR](https://github.com/FormidableLabs/react-live/pull/260) hope to see it merged someday). Meanwhile, I just listed a github branch as a dependency so we can use it even before it's merged.

docs: allow classes and async/await in live examples

---

.github/workflows/preview-documentation-cleanup.yml
.github/workflows/preview-documentation.yml

That's how the current docs preview repo looks like. It's huge, I think that's why it's slow, not because of git history. I'll do manual cleanup there, but I hope that little workflow will remove each PR preview once it merged.
UPD: @larsmoa actually I got a second thought on it, and maybe history still matters the most here. If something ever were committed to the git it remains in the git, so I have doubts that this cleanup will help anyhow 🙁  but let's see still

chore: add workflow to cleanup docs previews

---

.github/workflows/preview-documentation.yml

sorry I wiped out all the existing PR previews. Just rerun preview workflow to get them back. 
I guess `force_orphan` option doesn't work as I expected, but I guess it will once [v4 will be published](https://github.com/peaceiris/actions-gh-pages/issues/455). I expected commit history to be squashed but contents must be kept.

chore: dont use force_orphan option, it wipes out everything

---

documentation/docs/examples/cad-basic.mdx
viewer/core/src/datamodels/cad/CadManager.ts
viewer/core/src/datamodels/cad/CadModelUpdateHandler.ts
viewer/core/src/datamodels/cad/rendering/EffectRenderManager.ts
viewer/core/src/public/migration/Cognite3DModel.ts

Hidden models will no longer be visible on screen and sectors will not be loaded.
Note that we don't unload data associated with hidden models. To also reclaim memory, use `Cognite3DViewer.removeModel()`

fix: setting Cognite3DModel.visible has no effect

---

viewer/core/src/glsl/math/floatBitsSubset.glsl

We only work with bits 0-7 so no need to have more iterations.

fix: reduce constant to shave of a few nanoseconds in the rendering loop

---

examples/src/pages/Migration.tsx
viewer/packages/tools/src/DebugLoadedSectorsTool.ts

This enables better distinguishing the shape and size of each individual sector.

feat: DebugLoadedSectorsTool now supports randomly coloring sectors

---

viewer/core/src/glsl/post-processing/outline-detect-combine.frag

fix:handle non-determinant depth values after resizing when MSAA is enabled causing custom objects to be invisible

---

.github/workflows/preview-documentation.yml

Last fix was incorrect and now created a new comment on each run.

fix: pin comment-on-pr package to 1.2 to fix duplicated comments about preview docs

---

README.md
examples/.env
examples/.env.example
examples/src/pages/Clipping.tsx
examples/src/pages/Geomap.tsx
examples/src/pages/Migration.tsx
examples/src/pages/SSAO.tsx
examples/src/pages/SectorWithPointcloud.tsx
examples/src/pages/Simple.tsx
examples/src/pages/SimplePointcloud.tsx
examples/src/pages/TwoModels.tsx
examples/src/pages/WalkablePath.tsx
examples/src/routes.tsx
examples/src/utils/example-helpers.ts

Allows for easier switching between projects. URLs for using the test examples now have the form
```
https://localhost:3000/migration?env=europewest11-3d&project=3ddemo&modelId=2890599736800729&revisionId=8160779262643447
https://localhost:3000/migration?env=greenfield-3d&project=3ddemo&modelId=4304523256471874&revisionId=1692652455232986
```

Add authentication environments

---

viewer/packages/utilities/src/indexset/IndexSet.test.ts
viewer/packages/utilities/src/indexset/IndexSet.ts

In index set inversion, specifically
Wish that we had just used the first-inclusive-last-exclusive convention for NumericRanges to begin with :/

Fix off-by-one-error in IndexSet

---

viewer/.eslintrc.js
viewer/core/src/public/migration/Cognite3DViewer.ts
viewer/core/src/public/migration/RenderController.ts
viewer/core/src/utilities/Spinner.ts
viewer/packages/cad-geometry-loaders/src/sector/culling/TakenSectorTree.ts
viewer/packages/cad-styling/src/CombineNodeCollectionBase.ts
viewer/packages/camera-manager/src/ComboControls.ts
viewer/packages/camera-manager/src/Keyboard.ts
viewer/packages/rendering/src/rendering/EffectRenderManager.ts
viewer/packages/rendering/src/transform/NodeTransformTextureBuilder.ts
viewer/packages/rendering/src/transform/TransformOverrideBuffer.ts
viewer/packages/tools/src/AxisView/AxisViewTool.ts
viewer/packages/tools/src/Geomap/Geomap.ts
viewer/packages/utilities/src/datastructures/DynamicDefragmentedBuffer.ts

Avoids us having `private` variables that only is modified in the constructor.

refac: add prefer-readonly eslint rule and fix

---

examples/src/pages/Migration.tsx
viewer/core/src/public/RevealManager.ts
viewer/core/src/public/migration/Cognite3DViewer.ts
viewer/packages/rendering/package.json
viewer/packages/rendering/src/rendering/EffectRenderManager.ts
viewer/yarn.lock

Logs how long each render step in EffectRenderManager takes to console. Note that the measurements are not very precise and causes reduced render performance, but serves as a good tool to debug relative performance. 
Can be turned on in the Migration UI:

feat: add ability to debug how long the different rendering stages takes

---

.devcontainer/Dockerfile
.devcontainer/README.md
.devcontainer/devcontainer.json

This PR adds support to load Reveal as a devcontainer, in VSCode.

chore: add devcontainer setup

---

viewer/packages/cad-styling/src/NodeAppearanceProvider.test.ts
viewer/packages/cad-styling/src/NodeAppearanceProvider.ts
viewer/packages/rendering/src/CadMaterialManager.test.ts
viewer/packages/rendering/src/rendering/NodeAppearanceTextureBuilder.test.ts

Fixes an issue with timeline where the styling intermittently would be reset to the default styling

improvement: apply all node style changes within same 'tick' at the same time

---

viewer/package.json
viewer/yarn.lock

We encountered problems running anything point cloud related in Firefox. Turns out it was because of a custom GLSL-definition of the `round()` function in `potree-core`.
This has now been fixed in `potree-core` 1.5.1.

fix: bump potree-core to fix point cloud issue on Firefox

---

examples/yarn.lock
parser-worker/RevealParserWorker.ts
viewer/package.json
viewer/yarn.lock

This avoids copying buffers, saving some time when transfering them.
See https://github.com/GoogleChromeLabs/comlink#comlinktransfervalue-transferables-and-comlinkproxyvalue
Note! This PR doesn't really change anything as we will need to release a new parser-worker before it has effect. In order to test this, run it locally and follow procedures in parser-worker/README.md for testing local worker.

improvement: transfer buffers from parser web worker to main thread

---

viewer/packages/cad-geometry-loaders/src/sector/sectorUtilities.ts

In a regression introduced in #1513, geometry filter culling of geometry didn't correctly work, causing too much clipped geometry to be loaded (and processed/rendered), reducing performance and visual quality.
See below for a comparison of the same view point (the blue box is the active geometry filter, but we disable clipping filters to also show loaded geometry outside this box).
Before fix:
2420 draw calls
After fix:
670 draw calls
Fixes REV-259.

fix: too little geometry was culled during load when a geometry filter was active

---

documentation/yarn.lock

Fixes errors in documentation ( https://cognitedata.atlassian.net/browse/REV-258 )

fix: update documentation's yarn.lock to use Reveal 2.2.2

---

viewer/.eslintrc.js

chore: change eslint 'header' rule to allow 2021 and 2022 copyright notice

---

viewer/packages/cad-parsers/src/cad/filterPrimitivesCommon.ts
viewer/packages/cad-parsers/src/cad/filterPrimitivesV9.test.ts

There was a problem with many primitives being rendered outside the geometry clipping box. The issue turned out to be caused by a `Float32Array` which uses an already-existing buffer holding primitive values. The array was not constructed using the correct offset into the underlying buffer, which becomes a problem when the buffer contains different primitive types (which it generally does).
We did have one test that was supposed to catch problems like this (`Two different primitive types in same buffer: one of each accepted` in the `filterGeometryOutsideClipBox` suite), but it seems like it succeeded by chance because the erroneously read primitive values happened to yield a bounding box intersecting the geometry filter. This test has now been changed to a combination that fails on this …

fix: primitive filtering bounding boxes being bogus

---

documentation/yarn.lock
viewer/packages/camera-manager/src/ComboControls.ts

When clicking any UI element like Spinner logo or other UI elements in Reveal, keyboard controls doesn’t work until the 3D canvas is left or right clicked. Jira reference https://cognitedata.atlassian.net/browse/REV-278

fix: focus lost when clicked outside canvas

---

documentation/versioned_docs/version-2.x/API Reference.md
examples/src/utils/CadBudgetUi.ts
viewer/core/src/datamodels/cad/CadManager.ts
viewer/core/src/public/RevealManager.ts
viewer/core/src/public/migration/types.ts
viewer/packages/cad-geometry-loaders/app/index.ts
viewer/packages/cad-geometry-loaders/index.ts
viewer/packages/cad-geometry-loaders/src/CadModelBudget.ts
viewer/packages/cad-geometry-loaders/src/CadModelUpdateHandler.ts
viewer/packages/cad-geometry-loaders/src/sector/SectorLoader.test.ts
viewer/packages/cad-geometry-loaders/src/sector/culling/ByScreenSizeSectorCuller.test.ts
viewer/packages/cad-geometry-loaders/src/sector/culling/ByVisibilityGpuSectorCuller.test.ts
viewer/packages/cad-geometry-loaders/src/sector/culling/ByVisibilityGpuSectorCuller.ts
viewer/packages/cad-geometry-loaders/src/sector/culling/takensectors/TakenV8SectorMap.ts
viewer/packages/cad-geometry-loaders/src/sector/culling/takensectors/TakenV9SectorMap.ts
viewer/packages/cad-geometry-loaders/src/sector/culling/types.ts
viewer/test-utilities/src/createDetermineSectorInput.ts

\- Remove draw calls and max download size as it doesn't work well in V9
\- Simplified to only work on a single number which makes things more clear to users
\- Makes it easier to automatically adjust this in the future
\- Adjusted the default budget

improvement: simplify CAD model budget by only controlling "renderCost"

---

viewer/packages/cad-parsers/src/cad/triangleMeshes.ts
viewer/packages/rendering/src/GeometryBatchingManager.test.ts
viewer/packages/rendering/src/GeometryBatchingManager.ts
viewer/packages/rendering/src/rendering/EffectRenderManager.ts
viewer/packages/rendering/src/rendering/createSimpleGeometryMesh.ts
viewer/packages/rendering/src/rendering/primitives.ts
viewer/packages/sector-loader/src/GltfSectorRepository.ts
viewer/packages/utilities/index.ts
viewer/packages/utilities/src/counterMap.ts
viewer/packages/utilities/src/datastructures/DynamicDefragmentedBuffer.ts
viewer/packages/utilities/src/indexset/IndexSet.ts

The fix seems to be to properly add `mesh.userData.treeIndices`.

fix: Setting default node appearance to ghosted hides "default"-rendered geometry

---

viewer/packages/tools/src/HtmlOverlay/HtmlOverlayTool.test.ts
viewer/packages/tools/src/HtmlOverlay/HtmlOverlayTool.ts

Fixes an issue causing composite HTML elements from HtmlOverlayTool to not be removed from DOM when calling HtmlOverlayTool.dispose()

fix: composite overlays was not removed when calling clear() or dispose()

---

examples/src/pages/Migration.tsx
examples/yarn.lock
viewer/core/src/public/migration/Cognite3DViewer.test.ts
viewer/core/src/public/migration/Cognite3DViewer.ts
viewer/core/src/public/migration/types.ts

Added proper name for CameraControlsOptions type variable in migration example and some other places.

fix: variable naming in migration example and some other places

---

viewer/core/src/utilities/ViewStateHelper.ts

There is a bug in the documentation about viewer state. The second example throws an error when run: https://cognitedata.github.io/reveal-docs/docs/examples/cad-save-viewerstate/ It stems from an attempt at calling `clone` on the input vector objects, but they only contain data and not member methods.
This change converts the input data to actual `THREE.Vector3`s, solving the problem.

fix: error when saving viewer state

---

viewer/packages/metrics/src/MetricsLogger.ts

Sometimes happens when CadManager fails parsing a sector.

fix: error when trackError() was called with undefined error from CadManager

---

examples/yarn.lock
viewer/core/src/public/migration/Cognite3DViewer.ts
viewer/packages/camera-manager/src/CameraManager.ts
viewer/packages/utilities/index.ts
viewer/packages/utilities/src/events/InputHandler.ts
viewer/packages/utilities/src/events/index.ts

When disposing of Cognite3DViewer externally added event listeners were not disposed of which caused trouble in dev-server hot reload.

fix: Externally added event listeners were not disposed of when disposing of Cognite3DViewer

---

viewer/packages/cad-geometry-loaders/src/CadModelUpdateHandler.ts

Dont trigger 'not loading' whenever camera moves as we now support loading while camera moves

fix: issue causing loading indicator to not update while camera was moving

---

viewer/packages/rendering/src/GeometryBatchingManager.ts
viewer/packages/sector-loader/src/GltfSectorRepository.ts

The `GeometryBatchingManager` maintains a number of buffer arrays representing instance meshes and different primitive types, stored in a map using some string ID as key. In some cases, the key for an instance mesh, which is always a number stored as a string, would coincide with the key for a primitive, which is also a number (but seemingly is thought not to be).
A fix is therefore to always make sure the primitive array buffer ID does not contain just a number.

fix: certain models cause computer crashes

---

examples/src/pages/Migration.tsx
examples/src/utils/CameraUI.ts

This is very useful when debugging and you want to store an exact camera position to share or to use for reproducing an issue. Produces URLs ala https://localhost:8080/migration?project=3d-test&env=greenfield-3d&modelId=5244774438818744&revisionId=2249063501234508&camPos=238.93704593199658%2C65.7797568736406%2C-338.87591274763025&camTarget=193.05550578419502%2C42.334793193169986%2C-275.8093275879768
(notice parameters camPos and camTarget).

feat: add UI for storing and restoring camera from/to URL

---

viewer/packages/cad-geometry-loaders/src/CadModelUpdateHandler.ts
viewer/packages/cad-styling/src/NodeAppearanceProvider.test.ts
viewer/packages/cad-styling/src/NodeAppearanceProvider.ts

Causes setting prioritized hint for node collections to trigger sector loading so that the result becomes visible at once.

Trigger sector load on assigning priority [REV-295]

---

viewer/packages/rendering/src/rendering/NodeAppearanceTextureBuilder.test.ts
viewer/packages/rendering/src/rendering/NodeAppearanceTextureBuilder.ts

The problem seems to stem from implementation mistakes in the NodeAppearanceTextureBuilder. This would both make [0, 0, 0]-color values overwrite custom colors (which they should not), and ensure color would always be overwritten by overlapping sets, regardless of whether they were set in the incoming NodeAppearance object or not.

fix: style color update

---

viewer/packages/rendering/src/rendering/NodeAppearanceTextureBuilder.test.ts
viewer/packages/rendering/src/rendering/NodeAppearanceTextureBuilder.ts

Basically replicates https://github.com/cognitedata/reveal/pull/1816 for the 3.0 alpha branch.
According to Christopher, this should not contribute too much to the pain it is to rebase.

fix: update without color on superset of nodecollection resets color

---

.github/workflows/preview-documentation.yml

This ensures that only one job is publishing preview docs at the same time, avoiding CI to fail because multiple PRs are deploying docs at the same time.

chore: only deploy preview docs from one PR concurrently

---

viewer/packages/cad-parsers/src/metadata/CadModelMetadataRepository.test.ts
viewer/packages/cad-parsers/src/metadata/CadModelMetadataRepository.ts
viewer/packages/cad-parsers/src/metadata/parsers/CadMetadataParserGltf.test.ts
viewer/packages/cad-parsers/src/metadata/parsers/CadMetadataParserV8.test.ts
viewer/test-utilities/index.ts
viewer/test-utilities/src/createSceneSectorMetadata.ts

Reveal is supposed to choose geometry file format depending on the priority given in CadModelMetadataRepository. Instead, it chooses the first output in the output list that matches one of the two formats (v8 / v9). 
In practice, this seems to virtually never be an issue since v9 is often (always?) first, but anyway.

fix: model format priority

---

viewer/packages/utilities/src/cache/MemoryRequestCache.test.ts
viewer/packages/utilities/src/cache/MemoryRequestCache.ts

This is because the default number of sectors to remove on cleanup is 0 for small cache sizes, so that the cache remains full after cleanup.

fix: GltfSectorRepository fails on small cache size

---

viewer/packages/rendering/src/glsl/sector/instancedMesh.vert

Also transitively fixes the explode tool issue in the documentation.

fix: instanced mesh is not transformed by transform override

---

viewer/packages/cad-model/src/PickingHandler.ts

Fixes the "white screen" issue when picking / mouse scrolling

fix: clearing wrong render target

---

viewer/packages/camera-manager/src/ComboControls.ts
viewer/packages/camera-manager/tests/ComboControls.test.ts

Adds a override in the update of the camera controls to allow for setting the camera state even though the controls are disabled.
- **I am not proud of this due to having to implement this in the controls though setting the camera state should not touch the controls. Also virtually impossible to test due to the tight coupling with DOM events.**
- **Tried my best but had to give up due to the horrible coupling of logic and DOM.**
- **I have not, but that would require a large amount of work, almost to the point of totally re-designing the entire controls.**
- **I have, and my conclusion is that it is awful.**

fix: add a force override overload for updating the camera state

---

viewer/packages/tools/src/Geomap/GeomapTool.ts

Fixed geomap tool metrics, the usage was zero as this tool was tracing `AxisViewTool` rather than itself.
[REV-394](https://cognitedata.atlassian.net/browse/REV-394)

fix: metrics tracing for geomap tool usage

---

examples/src/utils/InspectNodeUi.ts
examples/src/utils/PointCloudObjectStylingUI.ts
examples/yarn.lock
viewer/package.json
viewer/packages/pointclouds/src/PointCloudNode.ts
viewer/yarn.lock

Fixed `sdk-playground` version because it was updated with breaking changes. Also, fixed accidental import problems from latest rebase from master.
Quick fix for some obvious errors, tested to be working properly, not actually proud because rebase went not so good.

chore: Fix triple import error and sdk-playground version from latest master rebase

---

documentation/package.json
documentation/yarn.lock

Hotfix since renovate bot incorrectly bumped the documentation threejs version.

fix: backport threejs for documentation to fix v1 doc

---

documentation/docs/examples/cad-2doverlay.mdx
viewer/packages/tools/src/HtmlOverlay/HtmlOverlayTool.test.ts
viewer/packages/tools/src/HtmlOverlay/HtmlOverlayTool.ts

HTML elements in Overlay Tool can be made to hide or unhide with `visible()`. This improvement will help in MeasurementTool when user need to hide/unhide elements of the measurement labels.
[REV-400](https://cognitedata.atlassian.net/browse/REV-400)

improvement: hide/show HTML overlay elements

---

viewer/packages/api/src/public/migration/renderOptionsHelpers.test.ts
viewer/packages/api/src/public/migration/renderOptionsHelpers.ts
viewer/packages/utilities/src/isMobileOrTablet.ts

3.1.0 introduces a regression such that mobile / tablet gets ssao shading when no options are supplied. This fixes that, as well as adds an additional check for matching iPads.
For more context see #2236

fix: mobile default settings should not include ssao, add iPad fix

---

viewer/packages/rendering/app/index.ts
viewer/packages/rendering/src/glsl/post-processing/edge-detect.glsl
viewer/packages/webpack.config.js

Whilst performance testing with EX devices, it showed a massive FPS hit from the edges visualization which turned out to be because of the loops. Manually unrolling them restored performance.
Also added an addition "Triangle count" statistic to the renderer testapp. And removed un-needed host setting in webpack config (not needed after webpack 5 migration).

fix: manually loop unroll in shader to improve performance

---

.github/workflows/ci.yml
examples/src/pages/Migration.tsx

Attempt to fix check for duplicate messages on PRs with documentation preview enabled.
PR includes only a change in CI script, so most points don't apply.

fix: Not working check for duplicate comment in documentation preview PRs

---

viewer/package.json
viewer/packages/pointclouds/src/potree-three-loader/loading/EptBinaryLoader.ts
viewer/packages/pointclouds/src/potree-three-loader/workers/eptBinaryDecoder.worker.ts
viewer/packages/pointclouds/src/potree-three-loader/workers/parseEpt.ts
viewer/packages/utilities/index.ts
viewer/packages/utilities/src/workers/workerize-transferable/.eslintrc.js
viewer/packages/utilities/src/workers/workerize-transferable/README.md
viewer/packages/utilities/src/workers/workerize-transferable/index.ts
viewer/packages/utilities/src/workers/workerize-transferable/message-types.ts
viewer/packages/utilities/src/workers/workerize-transferable/on-main.ts
viewer/packages/utilities/src/workers/workerize-transferable/on-worker.ts
viewer/packages/utilities/src/workers/workerize-transferable/util.ts
viewer/tsconfig.json
viewer/tsconfig.typedoc.json
viewer/webpack.config.js
viewer/yarn.lock

Adds workerize-loader as successor to worker-loader. This adds webpack 5 support as well as adds a small RPC layer on top of loaded workers and makes communication with workers a lot easier.
See: https://github.com/developit/workerize-loader for more info.
Shortcomings / workarounds:
* Workerize loader / webpack still produces a non-inline version of the worker when building, which we don't need. So I added a webpack plugin to delete any free floating workers post-build. (added an issue here: https://github.com/developit/workerize-loader/issues/128)
* Memory transfer to / from workers are initially not supported by workerize-loader, a little library was made for this however(https://github.com/naoak/workerize-transferable). This is written and compiled to ESM, which jest didn't like (I …

feat: add workerize for cleaner interop with workers

---

viewer/packages/sector-parser/app/SectorParser.VisualTest.ts
viewer/packages/sector-parser/app/testMaterials.ts

Small refactor to properly handle color override data texture. This is needed for textureFetch logic in the shader which #2364  introduces.

fix: sector parser test now properly computes color data override texture

---

viewer/packages/rendering/src/glsl/base/determineNodeAppearance.glsl
viewer/packages/rendering/src/glsl/sector/instancedMesh.frag
viewer/packages/rendering/src/glsl/sector/instancedMesh.vert
viewer/packages/rendering/src/glsl/sector/mesh.frag
viewer/packages/rendering/src/glsl/sector/mesh.vert
viewer/packages/rendering/src/glsl/sector/primitives/circle.frag
viewer/packages/rendering/src/glsl/sector/primitives/circle.vert
viewer/packages/rendering/src/glsl/sector/primitives/cone.frag
viewer/packages/rendering/src/glsl/sector/primitives/cone.vert
viewer/packages/rendering/src/glsl/sector/primitives/eccentricCone.frag
viewer/packages/rendering/src/glsl/sector/primitives/eccentricCone.vert
viewer/packages/rendering/src/glsl/sector/primitives/ellipsoidSegment.frag
viewer/packages/rendering/src/glsl/sector/primitives/ellipsoidSegment.vert
viewer/packages/rendering/src/glsl/sector/primitives/generalCylinder.frag
viewer/packages/rendering/src/glsl/sector/primitives/generalCylinder.vert
viewer/packages/rendering/src/glsl/sector/primitives/generalring.frag
viewer/packages/rendering/src/glsl/sector/primitives/generalring.vert
viewer/packages/rendering/src/glsl/sector/primitives/sphericalSegment.frag
viewer/packages/rendering/src/glsl/sector/primitives/sphericalSegment.vert
viewer/packages/rendering/src/glsl/sector/primitives/torusSegment.frag
viewer/packages/rendering/src/glsl/sector/primitives/torusSegment.vert
viewer/packages/rendering/src/glsl/sector/primitives/trapezium.frag
viewer/packages/rendering/src/glsl/sector/primitives/trapezium.vert
viewer/packages/rendering/src/glsl/sector/simple.frag
viewer/packages/rendering/src/glsl/sector/simple.vert

Related to #2363 , read that for more information about the issue.
This may be tested by adding a model where tree-indexes are surpassing 3 million, and doing some selection or similar. 
We tested this by just doing
```cs
while(treeindex < 3_000_000) treeIndex++;
```
before running any 3d model through the pipeline. And then applying a highlight, or hide NodeAppearance on click, to apply it to a specific node.
Co-authored-by: @vero-so 

fix: remove TreeIndex interpolation in fragment shaders

---

.github/workflows/ci.yml

Unit tests do not depend on viewer being built, as it will built it itself using ts-jest. So removing this dependency to increase paralellism during CI.

fix: remove build viewer dependency and download viewer step for unit tests

---

examples/webpack.config.js

The way examples symlinks reveal is currently wrong and causes it to wrongfully resolve dependencies in the /viewers node_modules. This can cause dependencies to be resolved even though they should not.
Before this change:
After this change:

fix: wrong resolve of viewer symlink

---

viewer/packages/pointclouds/src/potree-three-loader/rendering/PointCloudMaterial.ts

Fixes a memory leak where texture is not properly disposed.

fix: properly dispose old classifiction texture when creating a new one

---

viewer/README.md
viewer/package.json

Allow passing arguments to jest when running `yarn test:visual`. This allows to e.g. run a single visual test:
`yarn test:visual -- -t="Rendering.VisualTest.ts"`
or any other option supported by the Jest API.
Not done, but reviewer should test this.

chore: allow passing arguments to jest when running visual tests

---

examples/src/pages/Migration.tsx
examples/src/utils/NodeStylingUI.ts
viewer/packages/cad-styling/src/AssetNodeCollection.ts
viewer/packages/cad-styling/src/NodeCollection.ts

Fix issue in AssetNodeCollection causing getAreas() to return bounds in CDF space, not ThreeJS. This causes features such as prioritizedForLoadingHint not to work correctly.
Also added debug tool to show bounds of nodes filtering to example UI.
Framework for unit tests not in place here - will add test in #2389.

fix: issue causing AssetNodeCollection.getAreas() to return coordinates in "CDF space" and not "ThreeJS space"

---

documentation/docs/examples/cad-styling-nodes.mdx

Add boxes around areas matched in example to show possibilities to highlight information of interest.

doc: show bounds of matched nodes in example for SinglePropertyFilterNodeCollection

---

viewer/packages/pointclouds/src/PotreeNodeWrapper.ts

This ensures that pointclouds are redrawn after a point class has changed visibility. Without this change, the user must e.g. move the camera to re-trigger a redraw and see the class change.

fix: redraw point cloud on classification change

---

.github/workflows/cleanup-on-close.yml

Delete preview docs when PR is closed to reduce time it takes to deploy preview docs. See #2462 for test PR used to test that preview docs are deleted on PR close/merge, and https://github.com/cognitedata/reveal/actions/runs/3092854918 that was ran when closing the PR.
Will not, but docs are no longer available after PR has been closed/merged.
Nope, test is in CI

chore: delete preview docs when PR is closed/merged

---

.github/workflows/ci-cleanup-on-close.yml

Avoid running cleanup job while other cleanup jobs are running or preview doc deploy is running to avoid git issues.
I have added unit and visuals tests to prove that my feature works to the best of my ability.
Will be tested as part of this PR in Github Actions.

chore: ensure preview docs cleanup doesn't interfer with preview deploy or cleanup

---

viewer/packages/cad-model/src/wrappers/Cognite3DModel.test.ts
viewer/packages/cad-model/src/wrappers/Cognite3DModel.ts
viewer/test-utilities/src/createCadModel.ts

getBoundingBoxByNodeId()/TreeIndex() didn't modify out parameter, so only return value works. Exposed in unit test and fixed.
Exposed and fixed in test, should be enough.

fix: expose and fix bug causing getBoundingBoxByNodeId/TreeIndex not to modify out parameter

---

documentation/yarn.lock
viewer/yarn.lock

Upgraded using `yarn up -R <dependency>` which only works with Yarn 3.
[Prototype Pollution in minimist ](https://github.com/cognitedata/reveal/security/dependabot/145)[Critical](https://github.com/cognitedata/reveal/security/dependabot?q=is%3Aopen+severity%3Acritical)
#145 opened 6 months ago • Detected in minimist (npm) • viewer/yarn.lock
[Terser insecure use of regular expressions before v4.8.1 and v5.14.2 leads to ReDoS ](https://github.com/cognitedata/reveal/security/dependabot/192)[High](https://github.com/cognitedata/reveal/security/dependabot?q=is%3Aopen+severity%3Ahigh)
#192 opened 2 months ago • Detected in terser (npm) • viewer/yarn.lock
[Inefficient Regular Expression Complexity in chalk/ansi-regex ](https://github.com/cognitedata/reveal/security/dependabot/143)[High](https://g …

chore: security upgrades for viewer/

---

viewer/yarn.lock

Fix yarn lock not up to date after merging #2524 .
A bit weird this wasn't caught in that PR's CI, though.

fix: run yarn lock from geojson removal

---

viewer/packages/cad-model/src/wrappers/Cognite3DModel.ts
viewer/packages/tools/src/Cognite3DViewerToolBase.ts
viewer/packages/tools/src/HtmlOverlay/HtmlOverlayTool.ts
viewer/packages/tools/src/Measurement/MeasurementTool.ts

When running `yarn start` or `yarn build` in `documentation`, `tsdoc` starts complaining by a few unrecognized tags in the TSDoc for various classes. This rectifies all warnings related to @see/@link

chore: fix tsdoc warnings related to @see

---

renovate.json

Validated using renovate-config-validator (https://docs.renovatebot.com/getting-started/installing-onboarding/). Fixes #2547
```
>  renovate-config-validator renovate.json                                                                                                                                                                  (base)
INFO: Validating renovate.json
INFO: Config validated successfully
```

chore: broken Renovate configuration

---

viewer/packages/data-providers/src/pointcloud-stylable-object-providers/cdfAnnotationsToObjects.ts
viewer/packages/pointclouds/src/PointCloudNode.test.ts
viewer/packages/pointclouds/src/PointCloudNode.ts
viewer/packages/pointclouds/src/PotreeNodeWrapper.ts
viewer/packages/pointclouds/src/potree-three-loader/tree/PointCloudOctree.ts
viewer/test-utilities/index.ts
viewer/test-utilities/src/createPointCloudModel.ts

Point clouds were not translated properly and had their bounding boxes translated wrongly when a custom transformation was applied to them. This fixes that issue, and makes sure that stylable bounding boxes also receive the appropriate transformation when traversed by the user.
A fundamental mistake in the previous code, is that it uses `updateMatrix` on the model, which computes the local matrix from `scale`, `position` and `rotation`, overwriting the matrix we just set. (See https://threejs.org/docs/#manual/en/introduction/Matrix-transformations)

fix: point cloud custom transformation

---

examples/src/pages/Migration.tsx
examples/src/utils/PointCloudObjectStylingUI.ts
examples/yarn.lock
viewer/packages/pointclouds/src/PotreeGroupWrapper.ts

A couple of fixes for point clouds that I deemed too small for their own PRs

improvement: various fixes for point clouds

---

documentation/docs/examples/pointcloud-styling.mdx
examples/src/utils/PointCloudObjectStylingUI.ts
viewer/index.ts

Exports a previously hidden type, which is used in the `traverseStylableObjects` call in `CognitePointCloudModel`.

fix: export point cloud object metadata

---

viewer/packages/rendering/src/glsl/sector/instancedMesh.frag
viewer/packages/rendering/src/glsl/sector/instancedMesh.vert
viewer/packages/rendering/src/glsl/sector/mesh.frag
viewer/packages/rendering/src/glsl/sector/mesh.vert
viewer/packages/rendering/src/glsl/sector/primitives/circle.frag
viewer/packages/rendering/src/glsl/sector/primitives/circle.vert
viewer/packages/rendering/src/glsl/sector/primitives/cone.frag
viewer/packages/rendering/src/glsl/sector/primitives/cone.vert
viewer/packages/rendering/src/glsl/sector/primitives/eccentricCone.frag
viewer/packages/rendering/src/glsl/sector/primitives/eccentricCone.vert
viewer/packages/rendering/src/glsl/sector/primitives/ellipsoidSegment.frag
viewer/packages/rendering/src/glsl/sector/primitives/ellipsoidSegment.vert
viewer/packages/rendering/src/glsl/sector/primitives/generalCylinder.frag
viewer/packages/rendering/src/glsl/sector/primitives/generalCylinder.vert
viewer/packages/rendering/src/glsl/sector/primitives/generalring.frag
viewer/packages/rendering/src/glsl/sector/primitives/generalring.vert
viewer/packages/rendering/src/glsl/sector/primitives/sphericalSegment.frag
viewer/packages/rendering/src/glsl/sector/primitives/sphericalSegment.vert
viewer/packages/rendering/src/glsl/sector/primitives/torusSegment.frag
viewer/packages/rendering/src/glsl/sector/primitives/torusSegment.vert
viewer/packages/rendering/src/glsl/sector/primitives/trapezium.frag
viewer/packages/rendering/src/glsl/sector/primitives/trapezium.vert
viewer/packages/rendering/src/glsl/sector/simple.frag
viewer/packages/rendering/src/glsl/sector/simple.vert
viewer/packages/rendering/src/glsl/treeIndex/treeIndexPacking.glsl

N/A
This works around another issue with tree index precision, this time on adreno gpus when passing values in structs: https://github.com/KhronosGroup/WebGL/issues/3351
Tested working on Adreno 660, Chrome Windows, and will verify on iPad when its been charged.
I do not think any automated tests will catch these issues if they are not ran on device.
The code is deployed here, with large (>5 000 000) tree indexes. Clicking a part should hide it. Not its neighbors, and not display noise. Also coloring by tree index should work as expected, this did not work at all on Adreno with the previous struct based code.
https://proud-pond-057d1ea03-nihreveal.westeurope.1.azurestaticapps.net/?modelUrl=primitives_hda

Use vec2 instead of struct for packing TreeIndexes

---

.github/workflows/publish-to-npm-on-release.yml

Cherry picking publish workflow into 3.2.x release branch.

chore: add workflow that deploys to NPM on Github release (#2586)

---

viewer/README.md
viewer/webpack.config.js

https://cognitedata.atlassian.net/browse/REV-561
`yarn build` then `du -sh dist/index.js`
`yarn build && du -sh dist/index.js` on unix-based systems.

improvement: reduce bundle size by avoiding webworker and JS files

---

viewer/Cargo.lock
viewer/packages/pointclouds/wasm/Cargo.toml
viewer/packages/pointclouds/wasm/src/lib.rs
viewer/packages/pointclouds/wasm/src/parse_inputs.rs

--
Remove warnings related to `into_serde()` being deprecated for `wasm_bindgen` in the Rust code.
`yarn build:wasm` ** check that there are no warnings.
`yarn build:wasm` ** check that there are no warnings.

fix: rust warnings for into_serde()

---

renovate.json

All NPM-related Renovate PRs have crashed and been unable to update their lockfile lately.
This tries to fix that by restricting Renovate's node version to stop at v16, as we observed similar issues locally when using NodeJS v18
It hasn't
Screw around, find out.

chore: lock Renovate's node version to v16

---

documentation/package.json
documentation/yarn.lock

Bumps reveal 3.x in documentation.
Open 3.x documentation and check reveal version (by mouse hover on cognite logo) in live example.

chore: bump reveal version to 3.2.1 in documentation

---

viewer/packages/api/src/public/migration/Cognite3DViewer.test.ts
viewer/packages/api/src/public/migration/Cognite3DViewer.ts

https://cognitedata.atlassian.net/browse/REV-494
Remove `getScene()` from Cognite3DViewer due to mutating this can cause undefined behaviour.

refactor: remove getScene from API

---

viewer/packages/cad-styling/src/NodeCollectionDeserializer.test.ts
viewer/packages/cad-styling/src/NodeCollectionDeserializer.ts

https://cognitedata.atlassian.net/browse/REV-550
Fixes an issue where areas during deserialization of TreeIndexNodeCollection(s) are assumed to be box3, when they can simply be a JSON blob, causing a type missmatch.
For more context see: https://cognitedata.slack.com/archives/C01MZ6TPCH2/p1665996407443199

fix: create a box3 when deserializing areas in treeindex collection

---

documentation/package.json
documentation/yarn.lock
examples/package.json
examples/yarn.lock
viewer/package.json
viewer/packages/pointclouds/src/potree-three-loader/tree/PointCloudOctreePickerHelper.ts
viewer/packages/rendering/src/render-pipeline-providers/DefaultRenderPipelineProvider.ts
viewer/packages/utilities/src/SceneHandler.ts
viewer/yarn.lock

Renovate decided to auto-merge this. So this fixes incomplete types, docs, etc.

fix: threejs types version

---

viewer/packages/camera-manager/src/StationaryCameraManager.ts

https://cognitedata.atlassian.net/browse/REV-604
Fixes clicking axis cross tool would moving you out of the 360 image.
Using the Viewer.tsx example, load (in 3d-test):
modelId: `4923307033982497`
revisionId: `3100284276970593`
Using the dropdown dat.gui load 360 images with the follow parameters:
- site_id is `helideck-site-2`
- translation offset is  `(11, 49, 32)`
- rotation (defined with axis rotation and  radians) is axis: `(0, 1, 0)` and radians `3.08923`
Then click the axis view tool.

fix: axis cross manipulates stationary camera position

---

viewer/Cargo.toml

Renovates often has trouble updating Cargo lock on its own (e.g. https://github.com/cognitedata/reveal/pull/2739). This might be related to the Cargo crate being part of a workspace (residing in viewer/). The reason Renovate fails to see this, may be because the workspace members in the parent cargo toml are listed with a wildcard pattern. Specifying the crate location more precisely may help Renovate find the right lock file.

chore: be more specific about workspace directory

---

documentation/docs/examples/image360.mdx
examples/src/utils/Image360UI.ts
examples/yarn.lock
viewer/api-entry-points/core.ts
viewer/packages/360-images/index.ts
viewer/packages/360-images/src/Image360Collection.ts
viewer/packages/360-images/src/Image360Icon.ts
viewer/packages/api/src/public/migration/Cognite3DViewer.ts
viewer/reveal.api.md

https://cognitedata.atlassian.net/browse/REV-605
https://cognitedata.atlassian.net/browse/REV-621
https://cognitedata.atlassian.net/browse/REV-622
Adds a Image360Collection type that wraps a list of 360 images such that we can add additional per-collection funcionality in the future without breaking the API.
Also fix small nits such as off the outer rim of the 360 image icon being a little bit off, as well as reducing the max size of the icon.

feat: add Image360Collection return type for easier extendability in the future

---

viewer/packages/camera-manager/src/ComboControls.ts

Ensure `setViewTarget` calls on `CompoControls` triggers a `cameraChange` event. This ensures the scene is redrawn continuously while the camera interpolates between two view targets.
Manually, by clicking around in models and seeing smooth camera movement

fix: trigger update event when ComboControls receives new target

---

viewer/packages/api/src/public/migration/Cognite3DViewer.ts

https://cognitedata.atlassian.net/browse/REV-624
I was able to reproduce something similar in Firefox. I found that `originalDomeStyle` is not properly copied from `domElement.style`, so when the state of the domElement is reset all properties are still undefined and the dom is left as it was while the screenshot was rendered. 
Code:
```
const originalDomeStyle = { ...this.domElement.style };
console.log(this.domElement.style.position);
console.log(originalDomeStyle.position);
```
Result Chrome:
```
relative
relative
```
Result Firefox:
```
relative
undefined
```
Tested on Chrome and FireFox. Since I do not own any macOS/iOS devices I only have the assumption that this will also be a fix for those. I will ask a macOS/iOS friend to test :)
Go to 'Creating screenshots ' under 'Loading CAD …

bug: Screenshot resizing viewer canvas on macOS & iOS

---

viewer/packages/api/src/public/migration/Cognite3DViewer.ts

https://cognitedata.atlassian.net/browse/REV-589
When measurement labels are too close to each other they are combined into a different looking label. For some reason this label is not drawn correctly when we render screenshots.
In examples---->create few measurements where labels overlap----->create screenshot with UI

fix: incorrect combined measurement label in screenshot

---

viewer/packages/api/src/api-helpers/Image360ApiHelper.ts

https://cognitedata.atlassian.net/browse/REV-642
Fixes issue when resetting camera position to (0, 0, 0) when clicking escape key when not in 360 image.
Clicking escape button in examples should not have any effect.

fix: only add exit 360 image key listener when entering 360 image

---

documentation/docs/examples/rendering-resolution.mdx
viewer/packages/api/src/public/migration/types.ts
viewer/packages/rendering/src/ResizeHandler.test.ts
viewer/packages/rendering/src/ResizeHandler.ts

https://cognitedata.atlassian.net/browse/REV-662
Earlier, the camera-move downscale factor was based on the render resolution threshold, which may have been the default value or some value set by the user. 
With this, the factor will be directly applied to the number of physical pixels in the render area, making 1 use the full resolution, and e.g. 0.25 approximately halve the resolution in each dimension.
- open examples
- resize the window to be small
- adjust the slider in Camera -> Camera move resolution factor to some low number
- observe that the resolution is visibly lower, even if the resolution cap is presumably much larger than the number of physical pixels covering the canvas.
[REV-662]: https://cognitedata.atlassian.net/browse/REV-662?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMD …

improvement: scale-down-resolution now relative to physical canvas size

---

viewer/packages/api/src/public/migration/Cognite3DViewer.ts

https://cognitedata.atlassian.net/browse/REV-680
When 360 images are loaded into viewer without CAD or point cloud models, the 360 images are not visible.
Tested in `examples`
- Run `examples` and load https://localhost:3000/migration?project=3d-test&env=greenfield-3d&modelId=4923307033982497&revisionId=3100284276970593
- Add 360 images in the example options with below values
- site_id is helideck-site-2
- translation offset is  (11, 49, 32)
- rotation is axis: (0, 1, 0)
- radians is 3.08923
- In Developer tool->Console run viewer.removeModel(viewer.models[0])- 
- Now click on the 360 sprite icon to enter 360 image view

fix: 360 images are invisible/clipped when loaded without CAD/Point cloud model

---

documentation/docs/examples/click-reactions-cad.mdx
documentation/versioned_docs/version-3.x/examples/click-reactions-cad.mdx
documentation/versioned_docs/version-4.x/examples/click-reactions-cad.mdx

https://cognitedata.atlassian.net/browse/REV-574
The doc example tried to access nodeID in the intersection result, which is not a valid field. Changing it to retrieve the node ID another way.
In the documentation, CAD clicking site, check that node ID shows up when running the first example snippet.

docs: include nodeId in example intersection result properly

---

viewer/packages/360-images/src/Image360LoadingCache.ts
viewer/packages/360-images/src/Image360VisualizationBox.ts
viewer/packages/360-images/unit-tests/Image360LoadingCache.test.ts

https://cognitedata.atlassian.net/browse/REV-717
Fixes an issue where currently opened / entered 360 images could be purged from cache.
unit test :) 
But also the image you are in should not be exited when hovering on > 10 icons of other images.

fix: entered 360 image being purged from cache

---

viewer/packages/rendering/src/glsl/post-processing/pure-depth-ssao.frag
viewer/packages/rendering/src/render-passes/SSAOPass.ts

https://cognitedata.atlassian.net/browse/REV-318
Fixes the visual noise on large-scale models.
This does not make SSAO independent of depth range, as the Jira issue states, but makes the bias stronger on high ranges, to avoid the noise issue, which seems to stem from resolution limitations in the depth buffer.
SSAO is still tuned to "normal"-scale models, as can be seen in the oversized model below.
Also fixes an error in the generation of random unit hemisphere vectors.
These images are taken with interior (https://localhost:3000/?env=greenfield-3d&project=3d-test&modelId=8257821301169759&revisionId=7934734851519456&camPos=107.44678591593261%2C30.27114915044054%2C-290.1136229159823&camTarget=104.25858462418007%2C30.263734642188922%2C-289.98314277533814) and an oversized component …

fix: SSAO noise on large-scale models

---

viewer/packages/camera-manager/src/ComboControls.ts

https://cognitedata.atlassian.net/browse/REV-202
Camera was rotating too fast in keyboard navigation mode when it was "looking" too close to down/up. Now, speed is the same across any direction and keyboard navigation feels much more stable.
In Reveal examples, navigating with the keyboard.
1. Open any model in Reveal example, try to navigate around with keyboard. 
2. When closer to any model geometry, click on it and try to navigate with the keyboard again.

fix: Wrong rotation speed with keyboard navigation when camera looking down/up.

---

viewer/packages/tools/src/HtmlOverlay/HtmlOverlayTool.ts
viewer/packages/tools/src/Measurement/MeasurementLine.ts
viewer/packages/tools/src/Measurement/MeasurementManager.ts
viewer/packages/tools/src/Measurement/MeasurementTool.ts

https://cognitedata.atlassian.net/browse/REV-579
Measurement line meshes and labels are clipped when slicing/clipping is used in the viewer.
In examples
1. Load https://localhost:3000/migration?project=3d-test&env=greenfield-3d&modelId=4579637123115827&revisionId=5523802070299592
2. Add few measurements from Options-->Measurements
3. Clipping -> Global
4. Check X and Flip X
5. Slide back and forth and observe measuring line & labels appear/disappear

fix: clip measurement line & labels

---

viewer/packages/tools/src/Measurement/MeasurementTool.ts

https://cognitedata.atlassian.net/browse/REV-729
This should have been taken care in [REV-579](https://cognitedata.atlassian.net/browse/REV-579)
[REV-579]: https://cognitedata.atlassian.net/browse/REV-579?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: measurements are not restored when clipping plane is removed

---

viewer/packages/api/src/api-helpers/Image360ApiHelper.ts

https://cognitedata.atlassian.net/browse/REV-767
Fixes an issue where multiple 360 images can be entered / opened if you click another 360 images before the first one completes loading.
Open any 360 image set, throttle your network speed in your browser and click two 360 images. Previously this would open both (once the finish downloading). Current behaviour should be to transition into the last clicked.

fix: disallow opening multiple 360 images

---

viewer/packages/api/src/api-helpers/Image360ApiHelper.ts

https://cognitedata.atlassian.net/browse/REV-794
I now throttle the amount of calls to `preload` when hovering using `debounceTime`. I am using debounce with both leading and trailing, so the first icon to be hovered will send a request right away. This makes the delay value less critical as it will not affect the download of the first image set.
I added a console.log that was printed on hover and one on preload. I then loaded Hibernia_RS2 and looked at how the functions were called. See task for movie.
Do what I did. Or just play around in Hibernia_RS2 and look for anything suspicious.

fix: Entering a clicked 360 Image is slow after hovering many icons

---

viewer/packages/data-providers/src/image-360-data-providers/Cdf360ImageEventProvider.ts

fix: wrong separator when parsing 360 image events

---

viewer/packages/rendering/src/glsl/pointcloud/pointcloud.vert

https://cognitedata.atlassian.net/browse/REV-847
Improved the styling in point cloud by blending with more styled color saturation & reducing original color for final output color
In examples
`cd examples && yarn && yarn start`
In example, `GUI---->Point cloud details #1----->Default styling---->change Color && Apply`

improvement: point cloud style blending

---

viewer/packages/pointclouds/src/potree-three-loader/tree/PointCloudOctreePicker.ts
viewer/packages/pointclouds/src/potree-three-loader/tree/PointCloudOctreePickerHelper.ts

https://cognitedata.atlassian.net/browse/REV-857
When clicking while using adaptive point sizing, the click would often snap to a point that is relatively far from the clicked position on the screen. 
This was due to adaptive point size LoD computations failing, yielding very large points. Then the closest point within a large radius of the click position would take priority.
This PR fixes the LoD computation by ensuring the pick material uses the same visibility data texture as the actual pick material. 
By clicking

fix: adaptive point sizing giving too large points in picking

---

viewer/packages/360-images/src/collection/DefaultImage360Collection.ts
viewer/packages/360-images/src/collection/Image360CollectionFactory.ts
viewer/packages/api/src/api-helpers/Image360ApiHelper.ts

https://cognitedata.atlassian.net/browse/REV-852
Now throws if user attempts to add the same 360 image collection more than once.
In examples, attempt to add the same image360set twice, notice an error being thrown.

fix: throw error if same image 360 collection is added twice

---

viewer/packages/360-images/src/entity/Image360RevisionEntity.ts

https://cognitedata.atlassian.net/browse/REV-878
After some investigation we found that the `fullResolutionCompleted` promise sometimes can be resolved before `firstCompleted`, resulting in the revision being added to the cache before `this._textures` has been set. This fixes this problem, but we suspect that the code here can be improved for both readability and stability: https://cognitedata.atlassian.net/browse/REV-880
Using the Hibernia_RS2 image set. 
The best way to reproduce this is to spam-click icons.

bug: Fail to transition to 360 image boxes due to textures not being set on revision

---

viewer/packages/rendering/src/glsl/pointcloud/pointcloud.frag
viewer/packages/rendering/src/glsl/pointcloud/pointcloud.vert

https://cognitedata.atlassian.net/browse/REV-881
https://cognitedata.atlassian.net/browse/REV-883
Fixes Paraboloid shape type for point cloud rendering which was broken and when EDL is enable for paraboloid shape, the depth value is more prominent than other point shapes, so fixed the same as other point shape depth.
In Reveal examples
1. Load [Reveal examples](https://localhost:3000/migration?project=3d-test&env=greenfield-3d&modelId=4579637123115827&revisionId=5523802070299592&edl=true&camPos=-151.0207655458611%2C77.05650411313886%2C54.59477449304217&camTarget=-151.43219465886696%2C76.9145944469877%2C54.12480300534449)
2. GUI ---> Options---> `pointShape` ----> `Paraboloid`

fix: paraboloid shape in point cloud rendering

---

viewer/packages/360-images/src/Image360Facade.ts

https://cognitedata.atlassian.net/browse/REV-945
Fixes an edge case where mutiple 360 images are in the same position which are not revisions.
`site_id: Akterdekk` has some 360 images that overlap exactly and are not revisions of each other. Before this fix you get stuck / cannot click anything than the other icon which overlaps.

fix: add minimum threshold to prevent getting stuck when two icons are overlapping

---

viewer/packages/api/src/public/migration/Cognite3DViewer.ts

Fixes a small syntax error in `dispose` which broke some parts of the typedoc generation.

fix: remove syntax error in jsdoc

---

renovate.json5

As of recent changes, we now automerge patch and minor versions of dependencies. This makes sure that threejs doesn't automerge as well... it sometimes brakes API even in minor versions...

chore: disable automerging of threejs

---

viewer/packages/360-images/src/collection/DefaultImage360Collection.ts
viewer/packages/360-images/src/collection/Image360Collection.ts
viewer/packages/data-providers/src/Image360Provider.ts
viewer/packages/data-providers/src/image-360-data-providers/Cdf360ImageEventProvider.ts
viewer/packages/data-providers/src/image-360-data-providers/Local360ImageProvider.ts
viewer/packages/data-providers/src/types.ts
viewer/reveal.api.md

Add method for getting all assets associated with a 360 image collection. Needed for the next release of Data Explorer
- Open image set XOM-HCU1_north_v02
- Run this function in e.g. `Image360UI`
- Observe that it has two matches

feat: get asset IDs associated with image 360 

---

viewer/packages/pointclouds/src/PointCloudManager.ts
viewer/packages/rendering/src/PointCloudMaterialManager.ts

https://cognitedata.atlassian.net/browse/REV-969
Make sure global clipping planes are applied to point cloud models upon load. Before, it would be necessary to e.g. adjust the clipping planes again after load, as to make it effective on the point cloud.
CAD models don't have this issue.
- Load CAD in examples: https://localhost:3000/?project=3d-test&env=greenfield-3d&modelId=8411313177673164&revisionId=3695367058006389
- Adjust Y clipping plane to cut about half the model
- Add point cloud model, model id: 5263029421485530, revision id: 7116592220967518
- Rotate around to see the newly added point cloud (it is some distance away from the CAD model)
- Observe that it is not sliced. To confirm, touch the slicer slightly, and see that half the point cloud model vanishes instantly

fix: apply clipping planes on newly loaded point clouds

---

react-components/package.json
react-components/src/components/RevealContainer/RevealContainer.tsx

Expands the div that Reveal mounts to such that it covers 100% of its parent.

fix(react-components): div wrapper not expanding to fit parent

---

viewer/package.json
viewer/yarn.lock

Fixes error importing threejs.
Once these two make it in, we should be able to bump again:
https://github.com/tweenjs/tween.js/pull/661
https://github.com/tweenjs/tween.js/pull/659

fix: backport three due to commonjs import error

---

viewer/packages/api/src/public/migration/Cognite3DViewer.ts

It seems that Image360ApiHelper.resetRedraw() was unused, and I believe here is the spot to use it.
This should avoid rendering every frame, which causes both performance and battery problems after 360 images have been used.
NOT Tested by me. May have side effects!

Bug: Avoid continuous rendering after 360 images was used

---

react-components/package.json
react-components/src/components/RevealContainer/RevealContainer.tsx
react-components/stories/Reveal3DResources.stories.tsx

Exposes some hand picked viewer options from Cognite3DViewerOptions.

feat(react-components): expose viewer options

---

viewer/packages/360-images/src/collection/DefaultImage360Collection.ts

N/A
When toggling image visibility there is no redraw after the fix in #3463. This adds a forced redraw after the image visibility is changed.
There may still be more issues with _needsRedraw, but most of the interactions with 360 images from the 360ImageApi manages this correctly. Will add more PRs as I find stuff :)
N/A
Toggle a image collection visibility without any movement. Images should dissappear and reappear.

fix: Missing redraw on Image Icon Visibility change

---

react-components/src/components/RevealToolbar/RevealToolbar.tsx
react-components/src/index.ts

Export toolbar buttons only as toolbar properties, e.g. `RevealToolbar.SlicerButton` instead of just `SlicerButton`.

fix: don't export toolbar buttons directly

---

documentation/yarn.lock
react-components/yarn.lock
viewer/yarn.lock

bump some transitive dependencies to fix a "high" CVE

fix: bump transitive dependency to fix a -high- CVE

---

react-components/src/components/RevealContainer/RevealContainer.tsx
react-components/src/components/RevealToolbar/RevealToolbar.tsx
react-components/src/higher-order-components/withSuppressRevealEvents.tsx
react-components/src/index.ts
react-components/stories/Toolbar.stories.tsx

Adds a higher order component which suppresses event propagation to Reveal. Also adds using this HOC to wrap the toolbar.
In the toolbar example in storybook, hover over the toolbar and try scrolling the mouse wheel. Before this change, the viewer would zoom, but now event propagation stops.

feat: add withSuppressRevealEvents HOC

---

react-components/src/components/ViewerAnchor/ViewerAnchor.tsx
react-components/src/higher-order-components/withSuppressRevealEvents.tsx
react-components/stories/ViewerAnchor.stories.tsx

Fix two small issues with ViewerAnchor:
- Make it appear on first render
- Suppress events targeting the viewer anchor
NB: This causes another issue - the "ViewerAnchor" div will still be present in the DOM at its original position, even though the child component may have been translated. They will both suppress events, even if the parent is invisible.

fix: viewer anchor adjustments

---

react-components/src/components/Reveal3DResources/Reveal3DResources.tsx
react-components/src/components/Reveal3DResources/queryMappedData.ts
react-components/src/components/Reveal3DResources/types.ts
react-components/stories/HighlightNode.stories.tsx

"Only" send 4 requests when getting 3D node data. The actual data is no longer returned, only the external ID of the node. The preview card will fetch the data itself.

fix: only 4 requests

---

react-components/src/components/Image360HistoricalDetails/Image360HistoricalDetails.tsx
react-components/src/components/RevealToolbar/LayersButton.tsx
react-components/src/components/RevealToolbar/LayersContainer/CadModelLayersContainer.tsx
react-components/src/components/RevealToolbar/LayersContainer/Image360LayersContainer.tsx
react-components/src/components/RevealToolbar/LayersContainer/PointCloudLayersContainer.tsx

FDX errors when trying to import the default export from lodash. Might be able to configure the tsconfig for FDX to make it work, but it is just easier to use named imports.

fix(react-components): used named imports for lodash

---

react-components/src/higher-order-components/withSuppressRevealEvents.tsx

Change type signature of withSuppressRevealEvents to allow wrapping components without intrisic attributes.

fix(react-components): mimic react.memo type signature with withSuppressRevealEvents HOC

---

viewer/packages/cad-geometry-loaders/src/CadModelUpdateHandler.ts
viewer/packages/cad-geometry-loaders/src/sector/SectorLoader.ts
viewer/packages/cad-model/src/wrappers/CadNode.ts
viewer/packages/cad-styling/src/NodeAppearanceProvider.ts
viewer/packages/cad-styling/visual-tests/Highlighted.VisualTest.ts
viewer/packages/rendering/src/CadMaterialManager.ts

If you add / remove a styled node collection and immidiatly remove the model, reveal will throw an error. Maintain is experiencing this issue and has been pushing to get it resolved.
Assign a styled node collection and remove the model. Before this fix, this would error.
I am not able to create a unit test for this, as the event is debounced such that there is no place for me to catch the error.

fix: node appearance provider still issuing events after cad node disposal

---

react-components/src/components/RevealToolbar/RevealToolbar.tsx

Remove the "focus selected asset" button from the default RevealToolbar.
Reveal react-components doesn't have a concept of "selected" asset, and it is unclear how that would be supported in a good, general way.

chore: remove focus button

---

react-components/src/components/RevealToolbar/LayersButton.tsx
react-components/src/hooks/use3DModelName.tsx

`use3DModelName` hook was triggering API was not caching the result of the query and even though query key remain same. This was a result of `staleTime` was set to default `0` causing it not to cache the result. This PR fixes the issue
In storybook
- `cd react-components && yarn && yarn build && yarn storybook`
- After the models are loaded, in `Network Tab` check for any API result calls when click on the `Reveal viewer`

fix(react-components): useModelName hook cache

---

react-components/src/common/i18n/index.tsx
react-components/src/components/RevealToolbar/RevealToolbar.tsx

`I18nWrapper` translation gets override by `defaultNamespace` property from `reveal-react-components` in `FDX`, to overcome this issue `addNamespace` property should be used to append `reveal-react-components` translation into `FDX`
In `FDX` and storybook
- `cd react-components && yarn && yarn build`
- `yalc` link `reveal-react-components` to `fusion` and run `flexible-data-explorer`

fix(react-components): translation config updated to enable FDX to append translation from react-component

---

react-components/src/components/ViewerAnchor/ViewerAnchor.tsx
react-components/stories/ViewerAnchor.stories.tsx

https://cognitedata.atlassian.net/browse/UX-1376
Add stickiness-property to viewer-anchor, to allow for it to clamp to the edge of the viewer instead of flying away.
Using the `ViewerAnchor` story.
Use the `ViewerAnchor` story.

feat: allow vieweranchor to have stickiness

---

react-components/src/components/NodeCacheProvider/NodeCacheProvider.tsx
react-components/src/components/RevealKeepAlive/RevealKeepAlive.tsx
react-components/src/components/RevealKeepAlive/RevealKeepAliveContext.ts

https://cognitedata.atlassian.net/browse/UX-1456
Make sure the `FdmNodeCache` is kept alive in the `RevealKeepAlive` context, alongside the Reveal viewer itself. This makes clicks responsive across the session, and it does not need to load the model asset mappings multiple times.
With FDX
- Build branch and connect to FDX through e.g. `yalc`
- Start FDX
- Open 3D view of model with mapped nodes
- Keep the network tab open as you click on different mapped nodes
- Notice that the first click on a node spawns multiple requests, subsequent ones spawn none (except for the `graphql` query from the node preview card).
- Navigate away from the 3D view, e.g. by clicking `Open` on the preview card for a node
- Then navigate back again, e.g. by clicking the 3D-view icon in the top right
- Click some …

feat: include node cache in keep-alive context

---

viewer/packages/tools/src/Measurement/MeasurementTool.ts

https://cognitedata.atlassian.net/browse/REV-990
Recent changes in measurement tool interaction (https://github.com/cognitedata/reveal/pull/3616, https://github.com/cognitedata/reveal/pull/3636) removed the capability to move the camera while in measurement mode. This capability will be restored with this PR, but will simultaneously revert the feature where the measurement tool would block click events triggering on models from other listeners. That feature will be re-introduced with #3726 in a new minor version
In examples

fix: revert measurement blocking

---

react-components/yarn.lock

https://github.com/cognitedata/reveal/security/dependabot/324
Bumps [@babel/traverse](https://github.com/babel/babel/tree/HEAD/packages/babel-traverse) from 7.22.8 to 7.23.2.

chore(deps): bump @babel/traverse from 7.22.8 to 7.23.2 in /react-components

---

react-components/src/hooks/useCalculateModelsStyling.tsx

Sometimes, when loading the scene in FDX, the styling that indicates what 3D nodes are asset-mapped on CAD models is not applied.  The reason for this seems to be related to a peculiar behavior FDX displays when mounted in the Fusion shell. In short, model components are mounted twice.
To my understanding, as an effect of that, asset-mapped styling is applied to both models, but when grouping computed styling, we risk that the all styles that apply to both models, are grouped together and applied to only one of them. This is fixed in this PR by not simply categorizing on grounds of a "modelId/revisionId" key, but using strict equality checks on the `AddModel` objects. 
This also ensures that different instances of the same model have their styling …

fix(react-components): "mapped"-styling not always set on right model

---

viewer/package.json

Needs to be a normal dependency such that users get the correct types.

fix: add sparse-octree as dependency to preserve types

---

viewer/package.json
viewer/yarn.lock

`npx api-extractor` does not seem to work in a Linux environment with api-extractor version 7.38.1, but works in 7.38.0.
Tracking issue: https://github.com/microsoft/rushstack/issues/4413
Locally, on my Linux machine.

chore: downgrade API extractor to fix CI

---

viewer/packages/cad-model/src/batching/MultiBufferBatchingManager.ts
viewer/packages/sector-loader/src/GltfSectorLoader.ts

N/A
Avoids calculating the bounding sphere on first render for every sector
The sphere is not really used due to frustumCulled = false. But using the apporixmate _may_ be better for performance than just adding a `new Sphere()` in origio.
BUT:
* This changes the geometry property, and does not do it in the GLTF parsing. This feels a bit wrong 🤔 . 
* We could also replace boundingBox, but its not used anywhere. 
Tested by observing the absense of computeBoundingSphere in the profiler. No visual changes observed. Also tested with `new Sphere()` instead of the approximate sphere, with no visual changes. (Probably due to the frustum culling is disabled)
With a larger model, check the rendering pass for similar images to this in the main branch, and then test the same model with this branch …

improvement: Add approximate bounding sphere

---

viewer/packages/pointclouds/src/ClassificationHandler.ts
viewer/packages/pointclouds/src/CognitePointCloudModel.ts
viewer/packages/pointclouds/src/PointCloudNode.ts
viewer/reveal.api.md

Add color in getClasses return value for point clouds
It hasn't

feat: add class color in `getClasses` return value

---

react-components/src/hooks/useSceneConfig.ts

An image collection does not need a Cdf3dModel with `externalId` of type number to work, this is only necessary for CAD and Point Cloud models
Have tested in storybook

(fix): Image collection does not need number modelid

---

viewer/packages/cad-model/src/wrappers/CogniteCadModel.test.ts
viewer/packages/cad-model/src/wrappers/CogniteCadModel.ts
viewer/packages/cad-styling/src/NodeAppearanceProvider.ts

Fix a bug where it is incorrectly assumed that `lodash.sortBy` sorts in-place. It instead creates a new array.
- Add a few collections with importance 0 with the examples UI
- Add a big collection overlapping (some of) the others, but with negative importance
- It should not override the styling set by previous collections

fix: sort styled node collections by importance

---

react-components/src/hooks/useSearchMappedEquipmentAssetMappings.tsx

There's a bug in the asset-search code related to limits.
The code works in two steps - it first fetches assets that satisfy the search query. It then filters these assets based on the mappings available in the 3D model(s). 
Previously, we used the same limit in both these queries, which in many cases causes the result from the first step to be trimmed down to a lower number, like 0. This tries to mitigate it somewhat by always returning the max number of results, 1000, from the first search.
Linked into fusion-shell and this PR: https://github.com/cognitedata/fusion/pull/4867

fix(react-components): don't limit search result that will be filtered

---

viewer/packages/api/src/public/migration/Cognite3DViewer.ts
viewer/reveal.api.md

Make it possible to change the position of a datamodels backed 360 collection. This is useful for e.g. aligning 360 collections in a Scene.
Have created a custom Reveal build and tested different 360 collection transformations in the SceneContainer storybook.

feat: Make it possible to change the position of a datamodels backed 360 collection

---

react-components/src/components/NodeCacheProvider/PointCloudAnnotationCache.ts

In Search (FDX), when an point cloud mapped asset which is has multiple annotation in it is selected, some of the annotation were not used to calculate the union of boundingbox which caused the camera to show incorrect view, this PR fixes the issue.
In Search

fix(react-components): missing some point cloud annotation boundingbox when asset selected

---

viewer/packages/camera-manager/src/Flexible/FlexibleControlsOptions.ts
viewer/packages/tools/src/HtmlOverlay/BucketGrid2D.ts

Attempt at fixing MathUtils issue in react-components test

chore: attempt at fixing MathUtils issue

---

react-components/src/components/Widgets/WindowWidget.tsx
react-components/src/components/Widgets/elements.ts

https://cognitedata.atlassian.net/browse/BND3D-3778
Removed border imprint of split window widget, enabled dragging of split window in minimized state and add resizing in height (Y-axis) & width (X-axis)
In Storybook
- `yarn && yarn build && yarn storybook`
- Select `SplitWindow` example
- When window is minimized, the window should be able to drag and in expanded state, the window is allowed to resize in X, Y & XY axis

fix(react-components): border imprint of split window widget and enabled dragging when minimized

---

react-components/package.json
react-components/src/components/RevealToolbar/RevealToolbar.tsx
react-components/src/components/RevealTopbar/RevealTopbar.tsx
react-components/stories/Topbar.stories.tsx

I don't know why, but I can not import these buttons in fusion. So I hope this will help

fix(react-components): export SetFlexibleControlsType and SetOrbitOrFirstPersonControlsType properly, and bump to 0.38.0

---

viewer/packages/api/src/api-helpers/Image360ApiHelper.ts

https://cognitedata.atlassian.net/browse/BND3D-3987
Call to `viewer.exit360Image()` even before `viewer.enter360Image()` is called for the first time resets the camera position and rotation to origin, This PR fixes the edge case
In examples and `Search` fusion
- `cd examples && yarn && yarn start`
- Load `celanese1` 360 image data set from the `GUI`
- `Click` on any 360 image `Icon` to enter into it, immediately press `Esc` key even before camera completely enter into the 360 image

fix: camera position, rotation reset when image 360 exit is invoked before enter image 360 is called for the first time

---

viewer/packages/camera-manager/src/StationaryCameraManager.ts

https://cognitedata.atlassian.net/browse/BND3D-3992
Start dragging only if inside the dom element of the stationary camera manager

(fix): Fix an event bug in StationaryCameraManager [BND3D-3992]

---

viewer/packages/api/src/api-helpers/Image360ApiHelper.ts
viewer/packages/camera-manager/index.ts
viewer/packages/camera-manager/src/Flexible/FlexibleCameraManager.ts
viewer/packages/camera-manager/src/Flexible/FlexibleCameraMarkers.ts
viewer/packages/camera-manager/src/Flexible/FlexibleControls.ts
viewer/packages/camera-manager/src/Flexible/FlexibleControlsOptions.ts
viewer/packages/camera-manager/src/Flexible/FlexibleControlsRotationHelper.ts
viewer/packages/camera-manager/src/Flexible/IFlexibleCameraManager.ts
viewer/packages/camera-manager/src/Flexible/moveCamera.ts
viewer/packages/tools/src/AxisGizmo/AxisGizmoTool.ts
viewer/reveal.api.md

No Jira ticket
This is a refactor to get rid of the Stationary Camera manager, since it behaved a little different then the FlexibleCamera Manager. Now the Use arrows and AxisGizmo is working inside the 360 image.
Use a model with 3D images. Jump in and out of the images. Zoom and pan. Use arrows and AxisGizmo to navigate.

refactor: Use the flexible camera manager in 360 images

---

react-components/src/components/SceneContainer/SceneContainer.tsx

When `scene` is changed, new scene's camera position & rotation were not loaded as `useEffect` was not getting trigger due to related dependency missing.
In Fusion
- `yalc` link to fusion
- Change the scene in `Search`

fix(react-components): loading of camera position & rotation on scene load not triggering

---

viewer/packages/camera-manager/src/Flexible/FlexibleControls.ts
viewer/packages/camera-manager/src/Flexible/FlexibleControlsOptions.ts
viewer/reveal.api.md

@greenbech found a few issues and suggestions:
* Bug: When camera state uses a rotation, the navigation do not work properly afterwards. This was caused by a old hack in the code, and is now removed. The hack is not longer necessary because the old AxisTool is not in used anymore. 
* Increase speed rotation x 2 with keyboard
* Increase speed rotation x 4 with keyboard + shift
* Do not need to automatically switch to first person mode when using the keyboard arrows only.

Smaller fixes on the flexible camera control

---

react-components/src/hooks/useReveal3dResourcesFromScene.ts

360 image transform should not be unpacked into it's components when added to type `AddResourceOptions`. This makes all 360 image collections added from Scene to have the identity transform
Have aligned a 360 collection and verified that the position is correct.
Open `Anders Ground Plane Scene` in the `Scenecontainer` storybook and see that it has a position in the corner of the groundplane. Open it in master and see that it is in the center
Image of correct placement

fix(react-components): Transform of 360 in Scene

---

react-components/src/components/SceneContainer/SceneContainer.tsx

Loading `Search` with `Copy URL` is not positioning the camera to URL value and was setting the camera to `SceneConfiguration` position and rotation, In this PR, I have removed loading scene default camera position, rotation and moved it to be handled in the application (`Search`).
In `Search`
- `yalc` link `react-component` to `fusion`
- Load `Search` and `Browse to 3D` page
- Switch between different `scenes`, camera should be positioned to `Scene's default camera position & rotation`
- Select `List view` & back to `3D view`, camera position & rotation should be maintained as previous.
- Select `Copy URL to share` from Toolbar and load it in New tab/window, camera position & rotation should be maintained as in URL.

fix(react-components): remove setting camera position, rotation from SceneContainer

---

viewer/packages/tools/src/HtmlOverlay/HtmlOverlayTool.test.ts
viewer/packages/tools/src/HtmlOverlay/HtmlOverlayTool.ts

https://cognitedata.atlassian.net/browse/BND3D-4109, check parent bug ticket for details
DOM has not been updated to reflect the changes to `htmlElement` before `getComputedStyle()` is called in `HTMLOverlayTool` while adding `htmlElement` which was causing issue when loading `measurement label` from `URL` link in `Search` application.
Have added a `timeout` to make sure the DOM has updated to reflect the changes.
In `Search`
- `yalc` push `viewer`
- `yalc` add in `fusion`
- Load Search and Browse to 3D page
- Select Distance measuring tool from Toolbar
- Create a point to point measurement
- Select Copy URL to share from Toolbar
- Open new browser tab/window and paste the url and Enter

fix: adding label into HTMLOverlayTool while loading viewer with URL state through measurement

---

react-components/src/components/RevealToolbar/LayersContainer/LayersContainer.tsx
react-components/src/components/RevealToolbar/LayersContainer/ModelLayersList.tsx

When zero model is added into viewer for a specific type (`cad/point-cloud/360 image`), then `Layer Button` submenu for this specific type would render a empty item was shown (ref: below image)
In this PR, an empty element is returned to fix the issue

fix(react-components): empty/blank menu item rendering for zero models in a resource type for Layer Button

---

react-components/package.json
react-components/src/architecture/base/renderTarget/RevealRenderTarget.ts
react-components/src/components/RevealContext/RevealContext.tsx
react-components/stories/utilities/RevealStoryContainer.tsx

Don't register AxisGizmo tool by default, and enable event listeners if not using the flexible camera manager.

fix(react-components): don't add axis gizmo and use event listeners if no flexible camera manager and bump to 0.46.1

---

viewer/packages/api/src/public/migration/Cognite3DViewer.ts
viewer/reveal.api.md

Add option to invoke early return on hitting 360 icon in "any-intersection" method

feat(experimental): optionally handle 360 icon intersection

---

react-components/src/components/CacheProvider/AssetMappingCacheProvider.tsx
react-components/src/components/CacheProvider/NodeCacheProvider.tsx
react-components/src/components/CacheProvider/PointCloudAnnotationCacheProvider.tsx
react-components/src/hooks/useClickedNode.tsx

This makes clicking interact properly with the new measurements in the react-components.

fix(react-components): use "any intersection" in useClickedNode

---

react-components/src/architecture/base/renderTarget/ToolController.ts
react-components/src/hooks/useClickedNode.tsx

Don't activate the "useClickedNodeData" hook when the current active tool is not the navigation tool. This means that no other tool can be active for useClickedNodeData to work.

fix(react-components): don't select objects when clicking in measurement

---

viewer/packages/cad-model/src/wrappers/CadNode.ts

https://cognitedata.atlassian.net/browse/BND3D-4264
Cad node is updating the renderlayers based on when the node appearance provider triggers a change, but the material manager throttles (yields), and may have stale data when the render layers are computed. So correct behaviour is to rather listen for when the material manager updates.
Can be reproduced with the follow visual test setup (Default.VisualTest.ts)
```ts
export default class DefaultVisualTest extends ViewerVisualTestFixture {
public async setup({ models, viewer }: ViewerTestFixtureComponents): Promise<void> {
const model = models[0] as CogniteCadModel;
const a = new TreeIndexNodeCollection([1]);
const b = new TreeIndexNodeCollection([2]);
const appearance: NodeAppearance = { renderInFront: true, color: new Color('red') }; …
```

fix: renderlayers get updated with stale data from material manager

---

viewer/packages/rendering/src/ResizeHandler.ts

This change enforces a minimum buffer size of 1 pixel in both dimensions to ensure that if the canvas element is contained within a resizable element, it never ends up with a width or height of 0, which causes GL errors, e.g.:
`[.WebGL-000012EC00717100] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete: Attachment has zero size.`
I've tested this in situ on an application which has the canvas contained within a flexible container, which fills the available remaining space, and also on the Reveal example viewer. The issue arises when the canvas element gets shrunk down so that it's width or height end up at 0.
If you modify the returned template at the end of the `Viewer.tsx` class, you can replicate this by expanding the resizable div to …

fix: Enforce minimum buffer size on resize

---

react-components/src/components/Image360CollectionContainer/Image360CollectionContainer.tsx
react-components/src/components/Image360CollectionContainer/constants.ts
react-components/src/components/Reveal3DResources/Reveal3DResources.tsx
react-components/src/components/Reveal3DResources/types.ts
react-components/src/components/SceneContainer/SceneContainer.tsx
react-components/src/index.ts

Expose a way for users to control the 360 icon culling parameters - max radius for 360 visualization, and max amount of 360 icons

feat(react-components): let user control 360 icon culling options

---

react-components/src/components/CacheProvider/RevisionFdmNodeCache.ts
react-components/src/components/CacheProvider/requests.ts
react-components/src/query/useSearchMappedEquipmentFDM.tsx

Fix an issue where there could exist multiple 3D model FDM instances for the same CDF model, in different spaces. It is necessary to know all of these when fetching relevant edges.

fix(react-components): include all relevant models in edge query

---

viewer/packages/api/src/public/migration/Cognite3DViewer.ts

The bounding box was not updated when new models was added. Could probably done it other places as well, since reveal doesn't care about it's bounding box.  To wait for animate() to be run, it is too late

(fix) Fix bounding box problems

---

viewer/packages/api/src/public/migration/Cognite3DViewer.ts
viewer/packages/utilities/src/customObject/CustomObject.ts
viewer/packages/utilities/src/customObject/ICustomObject.ts
viewer/reveal.api.md

* Added 2 function in ICustomObject and implemented in CustomObject 
* Refactored in some intersection to use useDepthTest  and added a predicate to filter intersections
* beforeRender  is needed to speed up the rendering for the architecture
* useDepthTest   will fix a bug in the architecture
* All are tested on the architecture  and works as intended

feat: Fixes for the architecture

---

react-components/src/architecture/concrete/clipping/commands/ApplyClipCommand.ts
react-components/src/architecture/concrete/measurements/MeasurementTool.ts
react-components/src/architecture/concrete/primitives/line/LineDomainObject.ts
react-components/src/components/Architecture/CommandButton.tsx

- If using clipping, do not show measurements that do not overlap with the clip box
- Use primary  to toggle on or off the cropping, since this is the most important in the toolbar

feat (react-components): Use primary button for cropping and do not show measurements completely outside the bounding box

---

viewer/packages/rendering/src/glsl/sector/primitives/cone.frag

Fix a bug where cones would sometimes have too large arc angle.
Before: 
After: 
In technical terms, the variable `theta` is initialized to a number between `-pi` and `pi`. The code would then add `2 pi` if it was less than the starting angle of the arc, to ensure that it is larger than that starting angle. However, there is a chance that `theta` can be e.g. `-pi/2` and the starting angle could be `7/4 pi`, in which case adding `2 pi` will not make `theta` large enough. Thus, we run the same computation again to be sure that `theta` is larger that the starting angle.
In react-components storybook. Model 
```
modelId: 1728775548730849,
revisionId: 3207495738912031,
```
in 3d-test, greenfield
camera parameters
```
position: new …
```

fix: cone rendering sometimes overshooting

---

viewer/packages/camera-manager/src/Flexible/FlexibleCameraManager.ts
viewer/packages/camera-manager/src/Flexible/FlexibleControls.ts
viewer/packages/camera-manager/src/Flexible/FlexibleControlsOptions.ts
viewer/packages/camera-manager/src/Flexible/IFlexibleCameraManager.ts
viewer/reveal.api.md

* Expose the options out of Reveal
* Made a new speed option. Default this is 0
Can not test this yet. Another PR in components

feat: Make options for  FlexibleControls available outside Reveal + Add speed option

---

react-components/src/components/Architecture/Toolbar.tsx

fix(react-components): Don't recreate toolbar buttons on rerender

---

react-components/src/components/Architecture/CommandButton.tsx
react-components/src/components/Architecture/DomainObjectPanel.tsx

A few more refactors to make the code conform slightly more to normal React conventions

refactor(react-components): refactor info panel

---

react-components/src/components/CadModelContainer/CadModelContainer.tsx
react-components/src/components/Image360CollectionContainer/Image360CollectionContainer.tsx
react-components/src/components/Image360Details/Image360Details.tsx
react-components/src/components/Image360HistoricalDetails/Panel/Image360HistoricalPanel.tsx
react-components/src/components/PointCloudContainer/PointCloudContainer.tsx
react-components/src/components/RevealToolbar/LayersContainer/WholeLayerVisibilityToggle.tsx
react-components/src/components/RevealToolbar/LayersContainer/elements.ts
react-components/src/hooks/useImage360Collections.ts
react-components/src/utilities/getViewerResourceCount.ts
react-components/stories/Image360Details.stories.tsx

~~Migrate components according to Cogs.js adoption plan.~~
This grew a bit out of it's original plans, but the change seems sort-of necessary: The Image360 panel would not always show up when entering 360 panels because of some React re-rendering shenanigans - the 360 image container is temporarily unmounted after getting added, and we did not properly react to when it was added anew. This PR fixes the second problem - the 360 is still mounted twice, but we now correctly react to it (by using the `use360Collections` hook, and making sure the resource count includes 360 images). 
Aside from that, I've simplified two occurrences of cogs.js chips as part of the cogs-adaption.

fix(react-components): adopt Cogs chips and fix 360 image details panel appearance

---

react-components/src/query/useModelsForInstanceQuery.ts
react-components/src/utilities/createAddOptionsKey.ts

https://cognitedata.atlassian.net/browse/BND3D-4461
Some asset queries have a lot of mappings to the same model, all of which are returned individually from the hook. This deduplicates the result before that happens
Tested with asset `multipleModelAssetWith2000Nodes` in 3d-test (instance page 3D widget previously threw 429's all over the place)

fix(react-components): deduplicate result models from `useModelsForInstanceQuery`

---

viewer/packages/api/src/utilities/ViewStateHelper.ts

Thread: https://cognitedata.slack.com/archives/C8A0QGMLN/p1721723669208189
TLDR: `getCurrentState` was returning sets of Vector3 with the required fields rather than simple POJOs. IMHO this is slightly bad form even though Typescript allows it, so this PR remaps the Vector3s to POJOs. 
Didn't

fix: return simple pojo and not Vector3

---

react-components/package.json
react-components/src/components/Architecture/CommandButton.tsx
react-components/src/components/Architecture/CommandButtons.tsx
react-components/src/components/Architecture/RevealButtons.tsx

Make sure option commands get option buttons etc.

fix(react-components): correctly differentiate between command types

---

viewer/package.json
viewer/packages/pointclouds/src/PointCloudManager.ts

Don't load pointcloud data if the pointcloud is hidden

fix: don't consider hidden pointclouds when computing sectors to load and bump to 4.16.1

---

react-components/package.json
react-components/src/hooks/useSceneDefaultCamera.tsx
react-components/stories/SceneContainer.stories.tsx

[BND3D-4470](https://cognitedata.atlassian.net/browse/BND3D-4470)
Preserves the current pivot point when moving the camera to Scene Home position. Currently, when moving the camera to the Scene Home position, the pivot point can be hidden as it's very or in a spot which is not close to the geometry of the model(s). In the future, we should make the Scene store position, rotation and pivot point.
Have been tested in the storybook for SceneContainer
1. Open SceneContainer storybook
2. Open Anders Scene as it has set a camera position
3. Set a pivot point on one of the models
4. Move the camera far away
5. Press the Reset to Home button
6. See that the pivot point is preserved
[BND3D-4470]: https://cognitedata.atlassian.net/browse/BND3D-4470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhY …

feat(react-components): Preserve camera pivot point on Reset to Home

---

react-components/package.json
react-components/src/hooks/useSceneDefaultCamera.tsx

Improves Scene home camera position.
* If default camera position is not provided, use a default if no models are present, of not, fit to models
* Fixes bug where rotation was not calculated correctly when rotating camera instead of providing camera target
Have built the package locally and tested it in Fusion
Build locally and use in Fusion. Verify that Scene home camera is correct

fix(react-components): Improve Scene home camera button and bump to 0.55.2

---

react-components/src/query/useSearchMappedEquipmentAssetMappings.tsx

fix(react-components): return type for asset search query & duplicate assets

---

documentation/versioned_docs/version-4.x/api/@cognite/reveal/type-aliases/CameraControlsOptions.md
viewer/packages/api/src/api-helpers/Image360ApiHelper.ts
viewer/packages/camera-manager/src/Flexible/FlexibleCameraManager.ts
viewer/packages/camera-manager/src/Flexible/FlexibleControls.ts
viewer/packages/camera-manager/src/Flexible/moveCamera.ts

No JIRA ticket
This PR fixes some typos. Found by using this extension (which I recommend everyone to use): https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker
Not tested.
No need to test.

chore: Fix various typos

---

react-components/package.json
react-components/src/components/CacheProvider/RevisionFdmNodeCache.ts
react-components/src/data-providers/FdmSDK.ts
react-components/src/data-providers/legacy-fdm-provider/createMappedEquipmentQuery.ts
react-components/src/query/useSearchMappedEquipmentAssetMappings.tsx

Fix a couple of small bugs in the code:
- `RevisionFdmNodeCache.ts`: remove `assert` and instead ignore invalid values to make code more resilient (I've seen this `assert` trigger a couple of times in the wild)
- Make sure mapped-equipment-query has `undefined` filter, if the incoming filter is empty
- Don't send "asset ID Search" request if there are no assets. Saves a query which would have an empty response
In the Fusion UI

fix(react-components): various small fixes and bump react-components to 0.55.4

---

react-components/src/architecture/base/commands/BaseFilterCommand.ts
react-components/src/architecture/base/commands/mocks/MockFilterCommand.ts
react-components/src/architecture/base/concreteCommands/PointCloudFilterCommand.ts
react-components/src/architecture/base/undo/Transaction.ts
react-components/src/architecture/concrete/clipping/commands/ApplyClipCommand.ts
react-components/src/components/Architecture/FilterButton.tsx
react-components/src/components/Architecture/FilterItem.tsx
react-components/src/components/Architecture/utilities.ts

I have changed the way to get the point cloud only.  The new way is more secure for not having bugs.

fix(react-components): Fix PointCloudFilterCommand because it didn't show up in Search

---

react-components/src/index.ts
react-components/src/query/useSearchMappedEquipmentAssetMappings.tsx

https://cognitedata.atlassian.net/browse/BND3D-4550
Exported `useAssetMappedNodesForRevisions` hook to solve `No search result` in `Search`, where loading state from the hook is used to add loading screen message
In `Search`
- yalc link `react-components` to `Search` fusion code in `pramodcog/BND3D-4460` branch
- Load 3D page and expand `Asset Search` panel in left

fix(react-components): export useAssetMappedNodesForRevisions hook to check for loading state of asset mapping

---

react-components/src/architecture/base/commands/BaseCommand.ts
react-components/src/architecture/base/commands/BaseTool.ts
react-components/src/architecture/base/domainObjectsHelpers/CommandChanges.ts
react-components/src/architecture/concrete/observations/ObservationsTool.ts
react-components/src/architecture/index.ts
react-components/src/index.ts

* 3D management need to use some of the basics in the architecture, so I exported all base classes and some of the utility classes/functions used by the actitecture.
* Also updated the listeners for commands. The reason for this is that you can listen to if a tool is activated or deactivated.

feat (react-components): Export the base classes and some utility from the new architecture

---

react-components/src/architecture/base/commands/BaseCommand.ts
react-components/src/architecture/base/commands/BaseSettingsCommand.ts
react-components/src/architecture/base/commands/mocks/MockSettingsCommand.ts
react-components/src/architecture/base/concreteCommands/SettingsCommand.ts
react-components/src/architecture/concrete/config/StoryBookConfig.ts
react-components/src/architecture/index.ts
react-components/src/components/Architecture/CommandButtons.tsx
react-components/src/components/Architecture/RevealButtons.tsx
react-components/src/components/Architecture/SettingsButton.tsx

This PR is just a refactor. No change in the applications.
Made a base class for SettingsCommand, called BaseSettingsCommand. This enable the possibility to make several settings buttons with different types of settings.
Also added possible Alt shortcut, which can be combined with Ctrl or Shift.

fix(react-components): Just make a base class for SettingsCommand and add ALT shortcut in the architecture

---

react-components/src/architecture/base/concreteCommands/SetPointShapeCommand.ts

This bug fix a the point shape option. It was cased by a typo, and I didn't test it properly.

fix (react-components): Fix type error in SetPointShapeCommand

---

react-components/src/architecture/concrete/clipping/SliceDomainObject.ts
react-components/src/architecture/concrete/primitives/line/LineView.ts
react-components/src/architecture/concrete/primitives/plane/PlaneCreator.ts
react-components/src/architecture/concrete/primitives/plane/PlaneRenderStyle.ts

This is based on feedback on a meeting today:
* Increase selection radius for lines. Before it was hard to pick them.
* Increate transparence of the clipping planes.
* Change color of the clipping planes to be less saturated. Also switch the side colors.
* When new plane is made, make sur that it is clipped in front of you.

fix(react-components): Smaller adjustment in clipping and measurement after meeting with user

---

react-components/src/components/CacheProvider/AnnotationModelUtils.ts
react-components/src/components/RuleBasedOutputs/hooks/useExtractUniqueAssetIdsFromMapped.tsx
react-components/src/index.ts
react-components/src/query/useSearchAssetsMapped360Annotations.tsx
react-components/src/query/useSearchMappedEquipmentAssetMappings.tsx
react-components/src/utilities/buildFilter.ts
react-components/stories/SearchHooks.stories.tsx

When a single character in provided as search input key, Asset search hook was returning no result if the Project contains very large number of Assets as the hook would filter the Asset based on 3D model asset mapping. This PR fixes the issue.
Here I have also removed initialAssetMapping call and it should be handle in application to list the initial 1000 asset mapping in the search list
In `storybook` and `Search`
- Run `Search` example in `storybook`
- Input `Node-` key string and click on `Search` button after `Asset contextualized` button is active
- Yalc link react-components to search code in fusion and can test in the search input

fix(react-components): No result when single character search input in asset search hook

---

react-components/src/components/CacheProvider/RevisionFdmNodeCache.ts

I've seen this `assert` trigger in the wild sometimes, so better get rid of it

fix(react-components): remove unsafe use of assert

---

react-components/src/components/Widgets/WindowWidget.tsx
react-components/src/components/Widgets/constants.ts
react-components/stories/SplitWindow.stories.tsx

https://cognitedata.atlassian.net/browse/BND3D-4567
Added optional support in Widget (Split) window header to render a component ideally `Button` from application
In storybook
- Run storybook: `yarn && yarn build && yarn storybook`
- Select `SplitWindow` example, `Open in New Tab` button will appear in the split window header

feat(react-components): Added optional support in Split window header to render a component

---

react-components/src/architecture/index.ts
react-components/src/components/Architecture/RevealButtons.tsx
react-components/src/components/Architecture/SettingsButton.tsx

* Fix to show the  point cloud filter in the settings drop down
* Add a class in the index file 8forgot this class)
* Expose RevealButtons.PointCloudFilter so it can be reused

fix(react-component): Tiny fix to visualize the point cloud filter in the settings drop down

---

react-components/src/components/Architecture/FilterButton.tsx
react-components/src/components/Architecture/OptionButton.tsx
react-components/src/components/Architecture/SettingsButton.tsx
react-components/src/components/Architecture/useClickOutside.tsx

Open storybook
Open mock settings (bug icon)
When the settings is open, click outside: Then the drop down should disappear.
Open some of the dropdown in the settings. Selection here should not caused the setting to disappear.
- [x ] I have thoroughly thought about the architecture of this implementation.

fix(react-components): Fix issue with outside click of the settings menu used by the settings button

---

react-components/package.json
react-components/src/components/RevealToolbar/ResetCameraButton.tsx
react-components/src/components/RevealTopbar/RevealTopbar.tsx

https://cognitedata.atlassian.net/browse/BND3D-4506
When in 360 Image mode and Home button is clicked, though the camera position resets to Scene Default position, the camera state would still be 360 image mode, this PR fixes the issue 
In storybook
- `yarn && yarn build && yarn storybook` in react-component
- Run `Topbar` example
- Enter into `360 Image mode` & click on `Home` button at top right

fix(react-components): camera state when Home button is clicked in active 360 image mode

---

viewer/packages/api/src/public/migration/Cognite3DViewer.ts
viewer/reveal.api.md

the function `fitCameraToModels `only take all the models, even invisible and doesn't use the `customobject `at all. In order not to break the code, I made an alternative which is `fitCameraToSceneBoundingBox`.  This uses the getSceneBoundingBox.
I also change the `recalculateBoundingBox `to use only visible object. See comment in that function. I believe that was the intension of the original code. It might break the code.... An alternative would be to make another function for doing this.
I saw this bug during a demo today. The user had many models, but only one was visible. The navigation was pretty hard and the fit all button didn't work as expected.

(fix): Update recalculateBoundingBox  in Cognite3DViewer

---

react-components/src/architecture/base/domainObjects/DomainObject.ts
react-components/src/architecture/concrete/measurements/MeasurementTool.ts
react-components/src/architecture/concrete/observations/ObservationsDomainObject.ts
react-components/src/components/Architecture/DomainObjectPanel.tsx

See this conversation: https://cognitedata.slack.com/archives/G0115JQ8JM8/p1724831633376919
* I also did some refactoring in the `ObservationsDomainObject`, because the `Quantity `was missing
* Fix missing "Copy to clipboard" button.
Open storybook/architecture
Make a crop box or a measurement.

feat(react-components): Move m/ft button to the domain object card

---

react-components/src/architecture/base/commands/BaseFilterCommand.ts
react-components/src/architecture/base/commands/mocks/MockFilterCommand.ts
react-components/src/architecture/base/concreteCommands/PointCloudFilterCommand.ts
react-components/src/components/Architecture/FilterButton.tsx
react-components/src/components/Architecture/OptionButton.tsx
react-components/src/components/Architecture/SettingsButton.tsx
react-components/src/components/Architecture/constants.tsx

Renamed some virtual functions to` ...Core` and made them protected.  This is because I wanted update to be centralized in the according non virtual function. This force the updating when `setChecked `and `toggleAllChecked `are called.
In addition I fixed the width to be width to prevent shifting between 1 and 2 lines.
Open storybook/architecture. Click in bug icon on the right toolbar

fix(react-components): Fix filter menus and som styling of the other autogenerated options

---

viewer/package.json
viewer/packages/360-images/visual-tests/Image360.VisualTest.ts
viewer/packages/api/src/api-helpers/Image360ApiHelper.ts
viewer/packages/camera-manager/src/Flexible/moveCamera.ts
viewer/packages/camera-manager/src/StationaryCameraManager.ts

Related to the recent tweenjs upgrade

fix: some tweenjs animations not triggering

---

react-components/src/architecture/base/domainObjects/DomainObject.ts
react-components/src/components/Architecture/DomainObjectPanel.tsx

Henrik had some comments when looking at it in the Context editor.
Open StoryBook/architecture
Click on Measurements
Add a measurement
See the panel

fix(react-components): Style the DomainObjectPanel different so it fits better on Fusion

---

react-components/src/components/Architecture/FilterButton.tsx
react-components/src/components/Architecture/OptionButton.tsx
react-components/src/components/Architecture/SettingsButton.tsx
react-components/src/components/RevealToolbar/HelpButton.tsx
react-components/src/components/RevealToolbar/LayersButton.tsx
react-components/src/components/RevealToolbar/RuleBasedOutputsButton.tsx
react-components/src/components/RevealToolbar/SelectSceneButton.tsx
react-components/src/components/RevealToolbar/SetFlexibleControlsType.tsx
react-components/src/components/RevealToolbar/SettingsButton.tsx
react-components/src/components/RevealToolbar/SlicerButton.tsx

https://cognitedata.atlassian.net/browse/BND3D-4600
Tooltip are active for dropdown (children) elements when mouse hovered in Toolbar option which has dropdown elements
In storybook
- run `yarn && yarn build && yarn storybook`
- Select `Architecture` example
- Select `MockSetting`/`Filter` button from `Toolbar` and `hover` over dropdown element, tooltip should not be active

fix(react-components): tooltip still active when hovering over child elements

---

react-components/src/components/CadModelContainer/CadModelContainer.tsx
react-components/src/utilities/isSameModel.ts

Fix a bug where changing the geometryFilter input to the `CadModelContainer` would not update (remove/re-add) it correctly.
In Storybook (and a double-check for unnecessary removes in FDX). In CadModelContainer.stories.tsx in react-components, replace the bottom part of `CadModelContainerStoryContent` with this:
```
const [geometryFilter, setGeometryFilter] = useState<GeometryFilter | undefined>({
boundingBox: new Box3(new Vector3(-100, 0, -100), new Vector3(200, 10, 200)),
isBoundingBoxInModelCoordinates: true
});
useEffect(() => {
setTimeout(() => {
setGeometryFilter(undefined);
console.log('Set new geometry filter');
setTimeout(() => {
setGeometryFilter({
boundingBox: new Box3(new Vector3(-100, 0, -100), new Vector3(200, 10, 200)), …
```

fix(react-components): update model when geometry filter changed

---

react-components/package.json
react-components/src/components/Reveal3DResources/useRemoveNonReferencedModels.ts
react-components/tests/unit-tests/components/Reveal3DResources/useRemoveNonReferencedModels.test.tsx
react-components/tests/unit-tests/components/RevealCanvas/hooks/useCameraStateControl.test.ts
react-components/tests/unit-tests/fixtures/cadModel.ts
react-components/tests/unit-tests/fixtures/viewer.ts

https://cognitedata.atlassian.net/browse/BND3D-4613
use3dModel was not returning updated value when unreferenced model was removed.
In Search

fix(react-components): resources count when unreferenced model is removed

---

react-components/package.json
react-components/src/components/CacheProvider/AssetMappingAndNode3DCache.ts
react-components/src/components/CacheProvider/AssetMappingPerModelCache.ts
react-components/src/components/CacheProvider/Node3DPerNodeIdCache.ts
react-components/src/components/CacheProvider/PointCloudAnnotationCache.ts
react-components/src/components/CacheProvider/idAndKeyTranslation.ts
react-components/src/components/CacheProvider/utils.ts
react-components/src/data-providers/legacy-fdm-provider/fdmEdgesToCadConnections.ts
react-components/src/data-providers/utils/mergeQueryResult.ts
react-components/src/query/useSearchMappedEquipmentFDM.tsx
react-components/src/utilities/convertAssetMetadataToLowerCase.ts

Minor refactoring in-between the features and bugs

refactor(react-components): minor refactors

---

react-components/package.json
react-components/src/hooks/scenes/use3dScenes.tsx
react-components/src/hooks/scenes/useSceneConfig.ts
react-components/src/utilities/tryGetModelIdFromExternalId.ts

Support newer scene -> 3d connection convention

feat(react-components): support newer scene -> 3d-model connection and bump to 0.59.0

---

react-components/src/components/RevealContext/RevealContext.tsx

https://cognitedata.atlassian.net/browse/BND3D-4635
The react query would refetch data when page/window/tab was focused causing unnecessary request, this caused an issue in `Search` application when `Bowser` tab is switched, which would trigger fetching again even when `queryKey` has not changed
In `Search` application
`yalc` link to `Search`

fix(react-components): react query triggers refetching when window is focused

---

viewer/packages/tools/src/AxisGizmo/AxisGizmoOptions.ts

Change to XYZ view in the Axis Gizmo. Just like blender. As in blender the negative axis don't have any label. That is done by purpose.
Blender:
run examples on viewer and you will see.

fix: Change to XYZ view in the Axis Gizmo as default, just like blender

---

react-components/src/components/RevealToolbar/LayersContainer/useModelHandlers.tsx
react-components/src/data-providers/index.ts
react-components/src/query/useSearchMappedEquipmentFDM.tsx
react-components/stories/SearchHooks.stories.tsx

https://cognitedata.atlassian.net/browse/BND3D-4651
https://cognitedata.atlassian.net/browse/BND3D-4597
While fetching datamodel search data, hook was returning data with latest version while would cause issue if application chooses specific version, this PR fixes issue by accepting datamodel version along with externalId & space.
And have also addressed, enabling point cloud model visibility when no CAD model is in the Scene, same for 360 Image as well.
In `Search`
`Yalc` link to `fusion` repo and run `Search` application with `cog-demo` project

fix(react-components): search hook to consider data model version

---

react-components/src/components/RevealToolbar/AssetContextualizedButton.tsx
react-components/src/components/RevealToolbar/RuleBasedOutputsButton.tsx

https://cognitedata.atlassian.net/browse/BND3D-4620
For only data model assets in `Search`, when `Asset contextualized` button is clicked, it would go to disable state, this PR fixes the issue
In `Search`
- `yalc` link to `fusion` repo and run `Search` application
- Load `cog-quickstart` and browse to 3D page
- Click on `Show asset contextualized` button

fix(react-components): asset contextualized button in disable state when clicked

---

react-components/package.json
react-components/src/components/CacheProvider/NodeCacheProvider.tsx
react-components/src/components/CacheProvider/requests.ts

https://cognitedata.atlassian.net/browse/BND3D-4726
In Search, when an DM mapped 3D node is clicked, it was unable to list the details in Preview panel due to mismatch in the data model version loaded in Search and react-components. Here I have enabled to return all views associated with the clicked asset so that in Search we can filter to match the data model version.
In Search
- yalc link to Search

fix(react-components): return all views for clicked DM mapped asset

---

react-components/src/architecture/base/domainObjectsHelpers/PopupStyle.ts
react-components/src/components/Architecture/CommandButton.tsx
react-components/src/components/Architecture/CommandButtons.tsx
react-components/src/components/Architecture/DomainObjectPanel.tsx
react-components/src/components/Architecture/DropdownButton.tsx
react-components/src/components/Architecture/FilterButton.tsx
react-components/src/components/Architecture/RevealButtons.tsx
react-components/src/components/Architecture/SegmentedButtons.tsx
react-components/src/components/Architecture/SettingsButton.tsx
react-components/src/components/Architecture/Toolbar.tsx
react-components/src/components/Architecture/constants.ts
react-components/src/components/Architecture/index.ts
react-components/src/components/Architecture/types.ts
react-components/src/components/Architecture/utilities.ts

The placement variable is now used instead of isHorizontal. It means the placement of the toolbar the button is in.
This will automatically set the tooltip at correct position.
Default is left, so in fusion we have to set this property at the top toolbar only. That what it was before, so no real changes.
The toolbar that will be generated automatically based on position will be correct now.
Also set tooltip delay to 500ms, which is normal.
Open storybook/architecture
Check the tooltips.
Open Measurement
Check also the tooltip there

feat(react-components) Fix tooltip placement and make it possible to set it outside react components

---

react-components/src/components/Image360Details/Image360Details.tsx

fix(react-components): Remove the exit button. Now it is in the top toolbar instead

---

react-components/package.json
react-components/src/architecture/base/commands/BaseTool.ts
react-components/src/architecture/base/concreteCommands/NavigationTool.ts
react-components/src/architecture/base/renderTarget/CommandsController.ts
react-components/src/architecture/concrete/annotations/commands/AnnotationsCreateTool.ts
react-components/src/architecture/concrete/annotations/commands/AnnotationsSelectTool.ts
react-components/src/architecture/concrete/example/ExampleTool.ts
react-components/src/architecture/concrete/primitives/tools/PrimitiveEditTool.ts
react-components/src/components/Architecture/FilterButton.tsx
react-components/src/components/Architecture/SettingsButton.tsx

* New version 0.64.2
* Rename onHover to onHoverByDebounce, since it was like that.
* Make a new onHover  without debounce. 
* Use the new on NavigationTool to hover on the 360 markers.
* Fix updating issue when open settingsbutton. 
* Fix closing when click on open settingsbutton.
1. Open settingsbutton with a point cloud location. Check that it has all settings
2. Show some 360 markers and hover around.

fix(react-components): Fix update issue when open SettingsButton and fix slow hover on 360 images

---

react-components/package.json
react-components/src/components/CacheProvider/index.ts
react-components/src/components/Reveal3DResources/Reveal3DResources.tsx
react-components/src/components/Reveal3DResources/types.ts

Adds an optional onResourcesIsLoaded callback for when a model is loaded regardless of the count to identify whether it was added or not, as used in the other onResourcesAdded callback.
This initiative is initially being used to execute cameraNavigation.fitCameraToAllModels(); when a model is loaded via Single Model Selection at SingleModelResourceContainer that is being implemented in the PR: https://github.com/cognitedata/fusion/pull/8080

feat(react-components): add callback when a model is loaded

---

react-components/src/hooks/index.ts
react-components/src/hooks/scenes/types.ts
react-components/src/hooks/scenes/use3dScenes.tsx

Exposes some other types used by the Single Model and Scene Resources feature in FDX.
Also, it moves the SceneData type into the types file. 
It is going along with the PR: 
https://github.com/cognitedata/fusion/pull/8080
- [X I have added PR type (Feat, Bug, Chore, Test, Docs, Style, Refactor) to the PR title.

feat(react-components): expose new types for the Single Model and Scene Resources features used by FDX

---

react-components/src/architecture/concrete/pointsOfInterest/PointsOfInterestTool.ts
react-components/src/architecture/concrete/pointsOfInterest/PointsOfInterestView.ts
react-components/src/architecture/concrete/pointsOfInterest/color.ts
react-components/src/components/Architecture/pointsOfInterest/PoiInfoPanelContent.tsx

This has the implication that `useClickedNodeData` will not be activated by default when clicking to create a PoI, which means it won't open any side panel in e.g. Search.
Also:
- Reduced PoI size by 50 %
- Made selected PoI blue
- made close button ghosted

fix(react-components): make poi-tool an edit tool++

---

react-components/package.json
react-components/src/hooks/useClickedNode.tsx
react-components/src/query/core-dm/typeGuards.ts
react-components/src/query/core-dm/usePointCloudVolumeMappingForAssetInstances.ts
react-components/src/utilities/queryKeys.ts

https://cognitedata.atlassian.net/browse/BND3D-4716
Hook to get asset instance and it's view
In storybook and `Search` application
- `yalc` link to `fusion` branch `pramodcog/BND3D-4712
`

fix(react-components): added hook to get coreDM point cloud volume data for clicked asset

---

react-components/src/architecture/concrete/pointsOfInterest/color.ts
react-components/src/components/Architecture/pointsOfInterest/PoiInfoPanelContent.tsx

fix(react-components): some poi fixes: selected poi with blue color

---

react-components/package.json
react-components/src/architecture/concrete/pointsOfInterest/PointsOfInterestSectionCommand.ts
react-components/src/architecture/concrete/pointsOfInterest/index.ts
react-components/src/hooks/useClickedNode.tsx
react-components/stories/HighlightNode.stories.tsx

Up to now, it's been impossible to know if the fields of the `useClickedNodeData` return value have been pending, or if there was no result, as the fields would be `undefined` in both cases.
This PR encances useClickedNodeData to return `null` for fields that evaluates to no result.
This is used for a usability improvement in Fusion, where we wait with closing the side panel on click until we're sure whether the new click gave a new instance for the panel.

feat(react-components): distinguish whether clicked node data is pending or empty, bump 0.73.6

---

react-components/package.json
react-components/src/components/RevealContext/RevealContext.tsx
react-components/src/components/RevealToolbar/SlicerButton.tsx

https://cognitedata.atlassian.net/browse/BND3D-5051
Fixed slider UI issue and also exposed logMetrics option in RevealContext props as PowerBI has throwing error due to security restrictions.
In storybook
Run Toolbar storybook and select Slider button

fix(react-components): slider UI issue and exposed logMetrics option in RevealContext props

---

react-components/package.json
react-components/src/components/CadModelContainer/CadModelContainer.tsx
react-components/src/components/PointCloudContainer/PointCloudContainer.tsx
react-components/src/components/RevealToolbar/SlicerButton.tsx

https://cognitedata.atlassian.net/browse/BND3D-4996
In `Search` app, when switching between list view to 3D, all Cad and point-cloud model was added each time. The issue was related to check in `isSameModel` where `transform` value from `viewer.model` passed was incorrect.
In `Search` app
Use `yalc` link

fix(react-components): cad & point cloud models getting added multiple time due to incorrect transforms

---

react-components/package.json
react-components/src/query/useSearchMappedEquipmentAssetMappings.tsx

https://cognitedata.atlassian.net/browse/BND3D-5057
When there are `100000` or more assets in the project and user `search` for a specific `asset` with string `query` in search inputs in 3D page of `Search` application, it is taking long duration to filter the `assets`, this PR improves the filtering of searched query assets in the search hook
In Search application
- `yarn build` react-components
- update `package.json` file in `fusion` repo with  `"@cognite/reveal-react-components": "file:../reveal/react-components"`
- `run pnpm install && pnpm nx serve flexible-data-explorer`
- Open 3D page in `Search` application with more than `40000` assets in project ( like `cog-3d`)
- search for a string in 3D search, results should be listed much quicker than production build

fix(react-components): improved performance of asset search slowness

---

react-components/src/architecture/base/domainObjects/DomainObject.ts
react-components/src/architecture/concrete/annotation360/Image360AnnotationDomainObject.ts
react-components/src/architecture/concrete/annotations/BoxGizmoDomainObject.ts
react-components/src/architecture/concrete/annotations/CylinderGizmoDomainObject.ts
react-components/src/architecture/concrete/axis/AxisDomainObject.ts
react-components/src/architecture/concrete/clipping/ClipFolder.ts
react-components/src/architecture/concrete/clipping/ClipTool.ts
react-components/src/architecture/concrete/measurements/MeasurementFolder.ts
react-components/src/architecture/concrete/measurements/MeasurementTool.ts

Measurement and Crop box get a specific parent.
Add icon where it was missing so correct icon show up in the tree

Feat(react-components): Prepare the existing domain object for the tree view

---

viewer/package.json
viewer/packages/360-images/src/Image360Facade.ts
viewer/packages/api/src/public/migration/Cognite3DViewer.ts

](https://cognitedata.atlassian.net/browse/BND3D-5179)
The intersection point was calculated wrong (wrong coordinate system and also substracted the camera position)
Use example app in Reveal and scroll mouse when mouse hover over the 360 icons.

fix: Fix bug in intersection between ray and 360 image icon [BND3D-5179]

---

react-components/package.json
react-components/src/architecture/concrete/annotation360/Image360AnnotationDomainObject.ts

Fixes bug where Three JS color was instantiated using a string instead of a number thus making the color default to white

fix(react-components): Fix wrong color type in image360 annotation domain object

---

react-components/tests/unit-tests/fixtures/fdmNodeCache.ts
react-components/tests/unit-tests/fixtures/renderTarget.ts

Remove `lint` warning in test files in `react-components`

chore(react-components): removed lint warning in test files

---

.github/workflows/react-components-ci.yml

https://cognitedata.atlassian.net/browse/BND3D-5450
Trigger react components CI step in CD as well to update codecov base branch. Currently the base commit on codecov is very old, due to coverage reports being connected to a specific commit which gets squashed away. Simply running the codecov in CD should tag commits in the master branch with codecov info.

chore: make react-components CI trigger during CD for codecov updates

---

.github/workflows/react-components-ci.yml

https://cognitedata.atlassian.net/browse/BND3D-5450
This makes the dorny/paths-filter@v3 step only run during PRs. For CD codecov reports(and rest of steps) should be done regardless. Currently updating the base commit for codecov never happens due to the step failing in during CD. This PR attempts to rectify this.

chore: only run changes step on PR

---

react-components/package.json
react-components/yarn.lock

~~Due to inconceivable shenaniganery in the `@cognite/signals` package, we're just making it a regular dependency.~~
`@cognite/reveal-react-components` has problems with resolving `@cognite/signals` properly as a peer dependency in Fusion. We make it a `dependency` again to simplify the setup for now, but we will bring this up with the `signals` developers in the future to see if there's a way around this.
Follow-up task: https://cognitedata.atlassian.net/browse/BND3D-5489

chore(react-components): make signals a dependency

---

react-components/package.json
react-components/yarn.lock

Having caret on the cogs-lab version causes duplications when used in the monorepo, because it is an alpha package.

chore(react-components): allow greater-than version of cogs-lab, and bump to 0.76.1

---

react-components/package.json
react-components/src/architecture/base/utilities/extensions/rayExtensions.test.ts
react-components/src/architecture/base/utilities/extensions/vectorExtensions.test.ts
react-components/src/architecture/concrete/primitives/box/BoxView.test.ts
react-components/src/components/Reveal3DResources/hooks/useRemoveNonReferencedModels.test.tsx
react-components/src/components/RevealCanvas/ViewerContext.test.tsx
react-components/src/components/RevealToolbar/LayersButton/components/LayersButtonsStrip.test.tsx
react-components/src/components/RevealToolbar/LayersButton/components/ModelLayerSelection.test.tsx
react-components/src/components/RevealToolbar/LayersButton/components/ModelLayersButton.test.tsx
react-components/src/components/RevealToolbar/LayersButton/components/ModelLayersList.test.tsx
react-components/src/components/RevealToolbar/LayersButton/components/WholeLayerVisibilitySelectItem.test.tsx
react-components/src/components/RevealToolbar/LayersButton/hooks/useModelHandlers.test.tsx
react-components/src/components/RevealToolbar/LayersButton/hooks/useSyncExternalLayersState.test.tsx

Use the new test-utils import alias in some places that were missed in #5044 
In addition, I had to introduce a second alias, as the first one only covers `.ts`-files, but there is a `.tsx`-files in the utils that we also want to export. If there's a better way to support this than adding a second import, I'd be interested to know.
By running the tests

refactor(react-components): more test util import path replacements

---

.github/workflows/ci.yml
.github/workflows/react-components-ci.yml

Added two distinct flags (viewer and react-components) to differentiate coverage reports in Codecov.
Fixed the missing token issue by ensuring CODECOV_TOKEN is correctly passed in the workflow.
Tested during CI with the PR creation
Make sure https://app.codecov.io/gh/cognitedata/reveal shows both modules info

chore: add codecov token and set codecov project flags

---

react-components/src/architecture/base/domainObjects/DomainObject.test.ts
react-components/src/architecture/base/utilities/colors/colorExtensions.test.ts
react-components/src/architecture/base/utilities/colors/colorExtensions.ts
react-components/src/architecture/base/utilities/colors/colorMap.test.ts
react-components/src/architecture/base/utilities/colors/colorMaps.test.ts
react-components/src/architecture/base/utilities/colors/getNextColor.test.ts
react-components/src/architecture/base/utilities/colors/getNextColor.ts
react-components/tests/tests-utilities/primitives/primitiveTestUtil.ts

- This s mostly unit tests
- Added `isGreyScale `to `ColorsExtensions` since this is a nice utility functions and used it in some test.
- Use  `isGreyScale ` in the color test for `DomainObject`. Removed the sum part of the test because it doesn't catch any bugs anywhy.

test(react-components): Make unit test for the color code

---

react-components/src/components/Architecture/BannerComponent.test.tsx
react-components/src/components/RevealToolbar/LayersButton/LayersButton.test.tsx
react-components/src/components/RevealToolbar/LayersButton/LayersButton.tsx
react-components/vite.config.ts

Fixes an issue where the drop down spawned from the Layers Button mounts outside of the dom hierachy of the component. In Unified-3d, this causes it to mount outside of the style scope which breaks styles.
Is needed for [BND3D-5620](https://cognitedata.atlassian.net/browse/BND3D-5620)
Added unit test.
[BND3D-5620]: https://cognitedata.atlassian.net/browse/BND3D-5620?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: layers drop down mounting outside of layers button parent

---

react-components/src/components/Architecture/DropdownButton.test.tsx
react-components/src/components/Architecture/DropdownButton.tsx

https://cognitedata.atlassian.net/browse/BND3D-5561
This bug was caused by some other refactoring. It is only in the user interface code, not in the business  layer.
I have refactor the `DropdownButton` component so it is clear by moving some code to inner component. IsVisible is used in the `DropdownButton`, and removed from the inner components.
Now the option closes when selected, as it normally should do for option menus of this sort.
Since it wasn't under unit test, I also added unit test for this part. I have used some time to understand making test for react-components, and I think the test should cover the feature in this component. The test is for usage when **usedInSettings = false**, the opposite is already make a unit test for.
1. `yarn storybook`
2. Open **Architecture/Main** …

fix(react-component): Fix various issues with the DropdownButton not used in settings (standalone in a toolbar) [BND3D-5561]

---

react-components/package.json
react-components/yarn.lock

Bump typescript to version 5.8.3

chore(react-components): bump typescript to version 5.8.3

---

react-components/src/data-providers/core-dm-provider/CoreDm3dDataProvider.test.ts
react-components/src/data-providers/core-dm-provider/CoreDm3dDataProvider.ts
react-components/tests/tests-utilities/dms/createDmsNodeItem.ts

Fix bug where CAD mappings would not be downloaded at all in cases where the scene includes at least one DM point cloud. 
This was visible when clicking a contextualized CAD node in the scene to highlight it, and then reload the page. The CAD node would in most cases no longer be highlighted. 
Through Fusion
- Go to DM project in Unified 3D
- Click 3D DM Cad-node
- Refresh
- CAD node should remain highlighted

fix(react-component): cad mapping stopped by DM pointcloud

---

viewer/rust-toolchain.toml

related to https://cognitedata.atlassian.net/browse/BND3D-5792
publishing failed due to `package `wasm-bindgen-wasm-conventions v0.2.95` cannot be built because it requires rustc 1.76 or newer, while the currently active rustc version is 1.73.0`
So updating the current rustc version.

chore: update rustc compiler version

---

react-components/src/architecture/concrete/reveal/RevealModelsUtils.test.ts
react-components/src/architecture/concrete/reveal/cad/CadDomainObject.test.ts
react-components/src/architecture/concrete/reveal/cad/CadDomainObject.ts
react-components/src/architecture/concrete/reveal/pointCloud/PointCloudDomainObject.test.ts
react-components/src/architecture/concrete/reveal/pointCloud/PointCloudDomainObject.ts

https://cognitedata.atlassian.net/browse/BND3D-5792
Fixes an issue where if a model that has already been removed, is removed again, then we would throw an error.
Note that 360 images do not need this fix, as Reveal already handles this internally.
Unit tests.

fix: throwing errors when trying to remove an already removed model

---

react-components/src/architecture/concrete/reveal/signal/getRevealDomainObjectsSignal.test.ts
react-components/src/architecture/concrete/reveal/signal/getRevealDomainObjectsSignal.ts
react-components/src/hooks/index.ts
react-components/src/hooks/useRevealDomainObjects.test.tsx
react-components/src/hooks/useRevealDomainObjects.ts
react-components/src/utilities/signal/DisposableSignal.ts
react-components/src/utilities/signal/useDisposableSignal.test.ts
react-components/src/utilities/signal/useDisposableSignal.ts

Part of the work for https://cognitedata.atlassian.net/browse/BND3D-5790
Introduces the hook `useRevealDomainObjects` which is implemented with a signal, and updates whenever (relevant) changes to the DomainObject hierarchy occurs. I intend this to be a generally useful function with a few use cases in existing hooks coming up in a subsequent PR.
This also introduces a pattern involving `DisposableSignal`, a signal that contains a callback and that comes with an attached dispose-function, which is relevant if e.g. the signal is based on an event listener to properly unregister the listener when the signal is no longer needed. The `useDisposableSignal` hook streamlines this part.
The reason for requiring `DisposableSignal` to return a callback in the signal, is that it allows us to avoid …

feat(react-components): create useRevealDomainObjects function

---

react-components/src/components/CacheProvider/cad/CadInstanceMappingsCacheImpl.test.ts
react-components/src/components/CacheProvider/cad/CadInstanceMappingsCacheImpl.ts
react-components/src/components/CacheProvider/cad/ClassicCadAssetMappingCache.ts
react-components/src/components/CacheProvider/cad/ClassicCadAssetMappingCacheImpl.test.ts
react-components/src/components/CacheProvider/cad/ClassicCadAssetMappingCacheImpl.ts
react-components/src/components/CacheProvider/cad/ClassicCadAssetMappingPerAssetIdCache.ts
react-components/src/components/CacheProvider/cad/ClassicCadAssetMappingPerModelCache.test.ts
react-components/src/components/CacheProvider/cad/ClassicCadAssetMappingPerModelCache.ts
react-components/src/components/CacheProvider/cad/ClassicCadAssetMappingPerNodeIdCache.ts
react-components/src/components/CacheProvider/cad/ClassicCadNode3DPerNodeIdCache.ts
react-components/src/components/CacheProvider/cad/assetMappingTypes.test.ts
react-components/src/components/CacheProvider/cad/assetMappingTypes.ts
react-components/src/components/CacheProvider/cad/rawAssetMappingTypes.test.ts
react-components/src/components/CacheProvider/cad/rawAssetMappingTypes.ts
react-components/src/components/CacheProvider/cad/types.ts
react-components/src/components/CacheProvider/idAndKeyTranslation.test.ts
react-components/src/components/CacheProvider/idAndKeyTranslation.ts
react-components/src/components/CacheProvider/types.ts
react-components/src/components/RuleBasedOutputs/RuleBasedOutputsSelector.tsx
react-components/src/components/RuleBasedOutputs/hooks/useExtractUniqueAssetIdsFromMapped.tsx
react-components/src/components/RuleBasedOutputs/hooks/useExtractUniqueClassicAssetIdsFromMapped.tsx
react-components/src/hooks/cad/modelWithAssetMappings.ts
react-components/src/hooks/useCreateAssetMappingsMapPerModel.tsx
react-components/src/query/network/searchClassicCadAssetsWithFilters.ts
react-components/src/query/useSearchMappedEquipmentAssetMappings.tsx
react-components/tests/tests-utilities/fixtures/sdk.ts

Closes https://cognitedata.atlassian.net/browse/BND3D-4989
Changes the classic CAD cache to also handle hybrid asset mappings; asset mappings that may contain DMS IDs in addition to / instead of classic asset IDs.
All changes:
- Introduced `rawAssetMappingTypes.ts` which defines the bridging between asset mappings from the CDF API and our internal types. It provides a more accurate CDF asset mapping type (where `assetId` is optional) and translation functions
- Refactored `assetMappingTypes` with reusable typeguards operating on wider types, used by the other type guards in the file. Also added a utility for getting the instance from an asset mapping.
- Renamed and added another model-key utility in `idAndKeyTranslation`
- Renamed `getNodesForAssetIds` on the `CadInstanceMappingsCache` to …

chore(react-components): implement hybrid functionality in classic asset cache

---

react-components/src/components/Reveal3DResources/hooks/useCalculateCadStyling.test.tsx
react-components/src/components/Reveal3DResources/hooks/useCalculateCadStyling.tsx
react-components/stories/HighlightNode.stories.tsx

https://cognitedata.atlassian.net/browse/BND3D-5825
Added support for hybrid CAD asset mapping cad node highlighting on click
Feature video ref
https://github.com/user-attachments/assets/73d7d694-808c-457e-99a0-df21d06d268b
In Storybook
- run `yarn && yarn build && yarn storybook`
- Load `HighlightNode` storybook example
- Click on highlighted `Tank` node which is hybrid asset.

feat(react-components): support for hybrid cad asset mapping styling on selected asset

---

react-components/src/query/index.ts
react-components/src/query/useHybridMappingsForAssetInstances.context.ts
react-components/src/query/useHybridMappingsForAssetInstances.test.tsx
react-components/src/query/useHybridMappingsForAssetInstances.ts
react-components/src/utilities/queryKeys.ts

Added support for fetching asset mapping for hybrid mapping instances. This is part of [Hybrid CAD: Instance-to-bounding box query](https://cognitedata.atlassian.net/browse/BND3D-5828). Here I have added new hook `useHybridMappingsForAssetInstances()` which return hybrid asset mapping data to be used in `Unified-3D` for clicked assets to style nodes and zoom to 3D Nodes when selected from FRS panel list.
Video Ref:
https://github.com/user-attachments/assets/f55a71a4-cf69-424b-98b4-af6e535a7b24
In `Unified-3D` through local build
- In `react-components` folder run `yarn && yarn build`
- Link this local build of `react-components` to `fusion` branch `pramodcog/add-boungdingbox-selected-hybrid-asset`
- Load `unified-3d` application with `3d-test` …

feat(react-components): support for fetching asset mapping for hybrid instances

---

react-components/src/architecture/base/commands/BaseCommand.ts
react-components/src/architecture/base/concreteCommands/DeleteDomainObjectCommand.ts
react-components/src/architecture/base/domainObjects/DomainObject.ts
react-components/src/architecture/base/renderTarget/RevealRenderTarget.ts
react-components/src/architecture/base/undo/Transaction.ts
react-components/src/architecture/base/undo/UndoManager.ts
react-components/src/architecture/base/utilities/types.ts
react-components/src/architecture/concrete/annotation360/DeleteSelectedImage360AnnotationCommand.ts
react-components/src/architecture/concrete/annotations/commands/AnnotationsDeleteCommand.ts
react-components/src/architecture/concrete/clipping/commands/ApplyClipCommand.ts
react-components/src/architecture/concrete/example/commands/DeleteAllExamplesCommand.ts
react-components/src/architecture/concrete/pointsOfInterest/DeletePointsOfInterestCommand.ts
react-components/src/components/Architecture/CommandButton.tsx
react-components/src/components/Architecture/CommandButtons.tsx
react-components/src/components/Architecture/DropdownButton.tsx
react-components/src/components/Architecture/FilterButton.tsx
react-components/src/components/Architecture/SegmentedButtons.tsx
react-components/src/components/Architecture/SettingsButton.tsx
react-components/src/components/Architecture/hooks/useCommandProps.tsx
react-components/src/components/Architecture/types.ts
react-components/src/components/Architecture/utilities.ts

1. Now, the `uniqueId `is made from Guid (before it was made from a counter)
2. Let buttonType return `ByttonType `type instead of string
3. Move `ButtonType  `and `UniqueId `to architecture/utility/types.ts
I relay on the unit tests

refactor(react-components): Change type of uniqueId and buttonType in the entire code

---

react-components/package.json
react-components/yarn.lock

Bump react components to `0.85.1`. Also bump peer dependency `reveal` to latest version

chore(react-components): Bump react components to 0.85.1

---

examples/src/pages/Viewer.tsx
viewer/packages/data-providers/src/DataSourceType.ts
viewer/packages/data-providers/src/pointcloud-stylable-object-providers/CdfPointCloudStylableObjectProvider.test.ts
viewer/packages/data-providers/src/pointcloud-stylable-object-providers/CdfPointCloudStylableObjectProvider.ts
viewer/packages/data-providers/src/pointcloud-stylable-object-providers/cdfAnnotationsToObjects.ts
viewer/packages/data-providers/src/pointcloud-stylable-object-providers/pointcloud-volume-data-providers/CdfPointCloudDMStylableObjectProvider.ts
viewer/packages/data-providers/src/pointcloud-stylable-object-providers/types.ts
viewer/packages/pointclouds/src/PointCloudNode.test.ts
viewer/packages/pointclouds/src/PointCloudNode.ts
viewer/packages/pointclouds/src/PointCloudPickingHandler.ts
viewer/packages/pointclouds/visual-tests/PointCloudColorStyling.VisualTest.ts
viewer/reveal.api.md
viewer/test-utilities/src/createPointCloudModel.ts

Closes https://cognitedata.atlassian.net/browse/BND3D-5947
Introduces the new `instanceField` in point cloud volume metadata, to enable users of Reveal to use hybrid contextualization in point clouds. This involves both returning this field as part of the stylable objects available from the point clouds, and in point cloud intersection results.
Note that only the first commit in the history actually contains the functional changes. The rest are small refactorings, chore work and tests
In examples
- Start the `examples` dev server and navigate to https://localhost:3549/?project=3d-test&env=greenfield-3d&modelId=8778813986451799&revisionId=2950725735925141 (from cog-3d, 3d-test)
- Click the left-most annotation here: 
- Observe in the console that the annotation contains an instanceRef
- …

feat: point cloud bounding volumes with DM instanceRef

---

viewer/packages/360-images/src/Image360Facade.test.ts
viewer/packages/360-images/src/Image360Facade.ts

https://cognitedata.atlassian.net/browse/BND3D-6065
Fixes an issue where hovering/clicking on 360-icons would yield no response when the 360-collection has a non-identity transform, for certain camera angles+positions
In Fusion
- Open scene with transformed 360-collections (`anders: test 360 collection rotation` in 3d-test is fine)
- Confirm that hovering/clicking on all 360-position from all camera positions/angles works

fix: 360 hover not registering for some perspectives

---

react-components/src/components/Image360CollectionContainer/Image360CollectionContainer.context.ts
react-components/src/components/Image360CollectionContainer/Image360CollectionContainer.test.tsx
react-components/src/components/Image360CollectionContainer/Image360CollectionContainer.tsx

https://cognitedata.atlassian.net/issues/?filter=-1&selectedIssue=BND3D-5298
- Refactors the Image360CollectionContainer using the dependency injection pattern with the use of useContext hook
- Adds relevant tests
No new functionalities added but all changes have been tested in storybook and in fusion. 
The component seems to behave as expected - just as before the PR.

refactor: Image360CollectionContainer refactor according to dependency injection pattern
