cognitedata/reveal

viewer/src/models/sector/parseSectorData.ts, viewer/src/models/sector/types.ts, viewer/src/views/threejs/sector/instancedMeshes.ts
Previously, we did not take into account the triangleOffset and
triangleCount parameters.
=> Fix instanced mesh rendering

viewer/jest.config.js, viewer/src/@types/glslify/index.d.ts, viewer/src/__mocks__/glslMocks.js, viewer/src/__tests__/views/threejs/sector/primitives.test.ts, viewer/src/models/sector/types.ts, viewer/src/views/threejs/sector/primitiveGeometries.ts, viewer/src/views/threejs/sector/primitives.ts, viewer/src/views/threejs/sector/primitivesMaterials.ts, viewer/src/views/threejs/sector/shaders.ts, viewer/tsconfig.json
=> Split primitives.ts into several files and add unit test.

viewer/package.json, viewer/webpack.config.js
This reduces the package size significantly.
=> Disable examples when building package

.travis.yml
This should get rid of the redundant push builds in our PRs.
=> Restrict builds to pull requests and merges to master

.travis.yml, examples/package-lock.json, examples/package.json, examples/webpack.config.js, viewer/package-lock.json, viewer/package.json, viewer/webpack.config.js
- Exclude externals in viewer build for speedz
- Restructure webpack.config.js for examples.
=> Enable faster development builds

examples/package-lock.json, examples/package.json, examples/src/utils/renderer-debug-widget.ts, viewer/package-lock.json, viewer/package.json, viewer/src/models/cad/determineSectors.ts, viewer/src/views/threejs/cad/CadNode.ts, viewer/src/views/threejs/cad/createThreeJsSectorNode.ts, viewer/src/views/threejs/cad/primitiveGeometries.ts
This reverts commit b9e95421f86eed70d0195252293da5769874df35.
=> Revert "Bump three, potree-core and Cesium and adapt to changes (#132)

.travis.yml
This should hopefully make dependabot happy and merge PRs into the dependency-updates branch automatically.
=> Tell Travis to also build the dependency-updates branch

viewer/package.json
Make it work on windows with powershell
=> Changed build script for win32 to use powershell

viewer/src/utils/CogniteClient3dExtensions.ts
Fix broken URL to API due to double /.
=> Fix broken URL

examples/src/world-to-screen.ts, examples/webpack.config.js, viewer/src/index.ts, viewer/src/views/threejs/index.ts, viewer/src/views/threejs/worldToViewport.ts
Add initial world to screen example, with a gui to change the given point. Missing features (picking / bounding box ) and add html point to selected object instead of taking it from gui?
=> World To Viewport (AKA world to screen)

viewer/src/cache/RequestCache.ts, viewer/src/models/cad/BasicSectorActivator.ts, viewer/src/views/threejs/cad/SectorNode.ts, viewer/tslint.json
=> Fix lint warnings

Cargo.lock, examples/package-lock.json, examples/src/world-to-screen.ts, viewer/src/__tests__/views/threejs/HtmlOverlayHelper.test.ts, viewer/src/migration/Cognite3DModel.ts, viewer/src/views/threejs/HtmlOverlayHelper.ts, viewer/src/views/threejs/index.ts
Added an overlay helper class.
Added an get bounding box from api to wrapper but since examples don't have old modelId we can't use the v1 endpoint to get bounding box.
=> HtmlOverlayHelper class for helping with Html Overlay

viewer/src/__tests__/views/threejs/cad/discardSector.test.ts, viewer/src/cache/MemoryRequestCache.ts, viewer/src/models/cad/parseSectorData.ts, viewer/src/views/threejs/cad/CadNode.ts, viewer/src/views/threejs/cad/RootSectorNode.ts, viewer/src/views/threejs/cad/discardSector.ts
Do not dispose of materials, since they are shared.
Create a dummy reference to the geometry in case there are lingering
references to the mesh somewhere.
=> Properly discard sectors

viewer/src/views/threejs/cad/CadNode.ts
Sector bounding box rendering now only shows bounding boxes for the loaded sectors.
=> Fix bug causing all sector bounding boxes to be rendered.

viewer/src/culling/ProximitySectorCuller.ts, viewer/src/culling/SectorCuller.ts, viewer/src/views/threejs/cad/CadNode.ts
Remove unused template parameter to make my head spin a bit slower ;)
=> Remove template parameter from SectorCuller and add some doc.

viewer/src/__tests__/models/cad/CadMetadataParserV8.test.ts, viewer/src/__tests__/testUtils/createSectorMetadata.ts, viewer/src/models/cad/CadMetadataParserV8.ts, viewer/src/models/cad/types.ts
This is to support models after a recent change in the optimizer.
=> Metadata parser for V8 format now supports null facesFile.

README.md
Added publish information to reveal root Readme.md
=> Add Publish info to root Readme.md

viewer/README.md, viewer/package.json
* added homepage which leads to viewer subfolder
* restructured readme a bit. Put the code sample higher and make it shorter. 
Could someone add a general description of what reveal is right after the first title in the readme? 🙏
=> Update readme; add homepage

viewer/src/public/RevealManagerBase.ts
Filter out CadNodes with suspended loaded from update pipeline
=> Use CadNode's loading hints in update pipeline

viewer/src/__tests__/views/threejs/cad/consumeSectorDetailed.test.ts, viewer/src/dataModels/cad/internal/rendering/triangleMeshes.ts, viewer/src/dataModels/cad/internal/sector/CachedRepository.ts, viewer/src/dataModels/cad/internal/sector/types.ts
=> Fix a bug causing borked color attributes

examples/package-lock.json, examples/package.json, examples/src/distance-measurement.ts, examples/src/utils/cameraControls.ts, examples/src/world-to-screen.ts, examples/webpack.config.js
also fixed initial render in world-to-screen and added some utility for WASD controls (if you already have something like that somewhere, please let me know)
=> add distance measurement example

examples/src/simple-pointcloud.ts, viewer/src/datamodels/pointcloud/DefaultPointCloudTransformation.ts, viewer/src/public/LocalHostRevealManager.ts, viewer/src/public/RevealManager.ts
Fixed the wrong transformation matrix being used (previously used the same as cad instead of identity)
=> Pointcloud not visible

viewer/README.md, viewer/src/public/migration/Cognite3DModel.ts
rename getBoundingBoxFromApi -> getBoundingBoxFromCdf
=> refactor(Cognite3DModel): rename getBoundingBoxFromApi

viewer/src/public/migration/Cognite3DViewer.ts, viewer/src/public/migration/types.ts, viewer/src/utilities/index.ts, viewer/src/utilities/isMobileOrTablet.ts
Enables antialiasing by default for Cognite3dViewer for PCs, but not mobile/tablet.
=> Enable antialiasing in Cognite3dViewer for PCs

viewer/src/datamodels/pointcloud/PotreeGroupWrapper.ts, viewer/src/datamodels/pointcloud/PotreeNodeWrapper.ts, viewer/src/public/migration/CognitePointCloudModel.ts
Need that to make it possible to change colorType for pointcloud models with Cognite3DViewer in use (in the console).
=> feat(CognitePointCloudModel): add pointColorType get/set, requestRedraw in setters

examples/package.json, examples/src/visual_tests/GithubDiffUploader.js, viewer/package.json
Update comment text on examples workflow failures
Increase timeout for visual tests
Fix serve script
=> Tune CI settings

.dependabot/config.yml, examples/package.json
https://github.com/cognitedata/reveal/issues/834
Should fix these messages
=> chore(examples): disable dependabot for linked deps

.github/workflows/github-pages.yml, documentation/docusaurus.config.js
Publish documentation to repository reveal-docs to avoid this repo to grow too big.
=> chore: publish documentation to separate repository

viewer/.eslintrc.js, viewer/package.json, viewer/src/datamodels/cad/rendering/primitiveGeometries.ts, viewer/src/public/RevealManager.ts, viewer/src/public/createRevealManager.ts, viewer/src/public/migration/Cognite3DModel.ts, viewer/src/public/migration/Cognite3DViewer.ts, viewer/src/public/migration/CognitePointCloudModel.ts, viewer/src/public/migration/NodeIdAndTreeIndexMaps.ts, viewer/src/public/migration/RenderController.ts, viewer/src/public/migration/types.ts, viewer/src/public/types.ts, viewer/src/utilities/RxTaskTracker.ts, viewer/tsconfig.json, viewer/yarn.lock
I personally already hate it. But hopefully, you will find it useful 😅
=> add eslint-plugin-jsdoc

README.md, release-template.md
There is no fancy automatization of anything, I just thought that it might be handy to have for creating release notes.
=> chore: add release-template.md

viewer/package.json, viewer/yarn.lock
bump controls version for the viewer
=> [REV-1] [REV-27] [REV-28] chore(viewer): update three-combo-controls

viewer/src/datamodels/cad/rendering/EffectRenderManager.ts, viewer/src/glsl/post-processing/fxaa.frag, viewer/src/glsl/post-processing/fxaa.vert
=> [REV-39] fix: bug causing viewer to become blurry when resized

examples/yarn.lock
after fresh install I have yarn.lock updated so committing it
=> chore: update yarn.lock in examples

viewer/src/datamodels/cad/rendering/EffectRenderManager.ts
Ghosted geometry was caused by some differences between how clearing render targets is handled in WebGL 1 and WebGL 2.
=> fix: issue causing ghosted geometry being "stuck" after hiding nodes [REV-68]

examples/src/pages/Migration.tsx
=> feat: add more debugging information about sectors

examples/src/pages/Migration.tsx, viewer/src/datamodels/cad/rendering/primitives.ts, viewer/src/datamodels/cad/sector/SimpleAndDetailedToSector3D.ts, viewer/src/datamodels/cad/sector/sectorUtilities.test.ts, viewer/src/datamodels/cad/sector/sectorUtilities.ts
=> Add frustum culling for primitives and faces and render statistics for Migration example 

viewer/src/datamodels/cad/rendering/primitiveGeometries.ts, viewer/src/datamodels/cad/rendering/primitives.test.ts, viewer/src/datamodels/cad/rendering/primitives.ts
Replace broken LOD with fixed geometry for torus segments for simplicity.
=> improvement: replace LOD with fixed geometry for torus segments

documentation/versioned_docs/version-1.x/API Reference.md, documentation/versioned_docs/version-1.x/examples/cad-2doverlay.mdx, documentation/versioned_docs/version-1.x/examples/cad-basic.mdx, documentation/versioned_docs/version-1.x/examples/combine-models.mdx, documentation/versioned_sidebars/version-1.x-sidebars.json, viewer/package.json
Release version 1.5 with major performance improvements.
=> chore(viewer): bump version 1.5.0

.github/workflows/ci.yml, .github/workflows/codeql.yml, .github/workflows/github-pages.yml, .github/workflows/preview-documentation.yml
trying to make it work with deploy keys
=> wip: docs preview experiments 

documentation/docs/examples/clipping.mdx
Was caused by a change in DragControls in r123 of ThreeJS.
=> doc: fix broken example for clipping with an interactive manipulator [REV-151]

viewer/src/datamodels/cad/sector/CachedRepository.ts, viewer/src/datamodels/cad/sector/SimpleAndDetailedToSector3D.ts, viewer/src/datamodels/cad/sector/rxSectorUtilities.ts, viewer/src/datamodels/cad/sector/sectorUtilities.ts, viewer/src/utilities/networking/CdfModelDataClient.ts
=> fix: bug causing sectors to never load after a network failure [REV-152] (#1454)

README.md, documentation/docs/installation.mdx
Update docs with information about how to install ThreeJS
=> doc: update doc for installation

.github/workflows/ci.yml, parser-worker/package.json, parser-worker/yarn.lock
released https://www.npmjs.com/package/@cognite/reveal-parser-worker/v/1.1.1
=> chore: reveal-parser-worker@1.1.1 – breaking comlink update

documentation/package.json, documentation/yarn.lock
that should do the trick with broken docs. I didn't catch it before because master didn't have breaking changes yet so it worked fine.
=> chore: fix docs threejs version

documentation/docs/examples/cad-2doverlay.mdx, documentation/docs/examples/cad-3dobjects.mdx, documentation/docs/examples/cad-basic.mdx, documentation/docs/examples/cad-explode.mdx, documentation/docs/examples/cad-styling-nodes.mdx, documentation/docs/examples/cad-styling.mdx, documentation/docs/examples/cad-transform-override.mdx, documentation/docs/examples/click-reactions-cad.mdx, documentation/docs/examples/click-reactions-pointcloud.mdx, documentation/docs/examples/combine-models.mdx, documentation/docs/examples/node-visiting.mdx, documentation/yarn.lock, viewer/src/datamodels/cad/NodeAppearance.ts
Also fix minor issue in DefaultNodeAppearance.Default
=> doc: fix many uses of async/await that failed. Minor doc improvements

viewer/src/datamodels/cad/styling/SinglePropertyFilterNodeCollection.ts
Ref https://github.com/cognitedata/3d-service/pull/918
=> Conform to newest update to filterNodes endpoint

viewer/src/datamodels/cad/rendering/primitiveGeometries.ts, viewer/src/datamodels/cad/rendering/primitives.test.ts, viewer/src/datamodels/cad/rendering/primitives.ts, viewer/src/utilities/three/BoundingBoxLOD.test.ts, viewer/src/utilities/three/BoundingBoxLOD.ts, viewer/src/utilities/three/index.ts
Before:
After:
(notice the silhouette of the big pipe)
=> feat: introduce LOD rendering of torus geometries to improve quality of certain primitives

documentation/package.json, documentation/yarn.lock, examples/package.json, examples/yarn.lock, viewer/yarn.lock
Updates a bunch of dependencies within the accepted ranges defined in packages.json
=> chore: update dependencies

documentation/docs/examples/cad-3dobjects.mdx, documentation/docs/examples/clipping.mdx, documentation/versioned_docs/version-1.x/API Reference.md, documentation/versioned_docs/version-1.x/examples/cad-3dobjects.mdx, documentation/versioned_docs/version-1.x/examples/clipping.mdx, documentation/versioned_docs/version-2.x/API Reference.md, documentation/versioned_docs/version-2.x/examples/cad-3dobjects.mdx, documentation/versioned_docs/version-2.x/examples/clipping.mdx, examples/src/pages/Migration.tsx, viewer/src/public/migration/Cognite3DViewer.test.ts, viewer/src/public/migration/Cognite3DViewer.ts, viewer/src/tools/DebugLoadedSectorsTool.ts
=> refac: rename Cognite3DViewer.forceRerender() to requestRedraw() (#1594)

viewer/core/src/datamodels/cad/CadMaterialManager.test.ts, viewer/core/src/public/migration/Cognite3DViewer.ts, viewer/core/src/utilities/ViewStateHelper.ts
Fix for https://cognitedata.atlassian.net/browse/ACEPC-105
=> fix: setting view state now unassigns previous styles instead of clearing them

viewer/packages/rendering/src/rendering/EffectRenderManager.ts
=> feat: assign names to render targets that helps debugging in SpectorJS

examples/src/pages/e2e/cad/ReassignNodeStyle.tsx, viewer/core/src/public/migration/Cognite3DModel.test.ts, viewer/core/src/public/migration/Cognite3DModel.ts, viewer/core/src/public/migration/Cognite3DViewer.ts, viewer/core/src/utilities/ViewStateHelper.ts
Also disallow adding the same node collection twice.
=> feat: add Cognite3dModel.updateStyledNodeCollection() and styledNodeCollections

parser-worker/package.json
New parser worker that uses "transfer" to move binary data between parser and main process.
=> release: @cognite/reveal-parser-worker@1.3.0

documentation/package.json, documentation/yarn.lock, viewer/packages/cad-styling/src/TreeIndexNodeCollection.ts, viewer/packages/utilities/src/NumericRange.ts, viewer/packages/utilities/src/indexset/IndexSet.ts
This is in order to fix recent issues seen with live code examples being broken in the documentation: https://cognitedata.atlassian.net/browse/REV-258
NB: There's no knowing if this will actually work :/
=> fix: ensure all doc examples in 2.x work properly

documentation/yarn.lock, viewer/core/src/public/migration/Cognite3DViewer.ts
Previous code for handling such situations was just totally wrong 🙂. Also, fixed small issue with bounding box usage when camera target was changed.
=> fix: proper handling of fast 'clicks' and movement of the mouse at the same time

viewer/packages/rendering/src/GeometryBatchingManager.ts, viewer/packages/utilities/src/datastructures/DynamicDefragmentedBuffer.ts
=> feat: set proper update range for partial geometry updates

viewer/packages/cad-parsers/index.ts, viewer/packages/cad-parsers/src/cad/primitiveGeometries.ts, viewer/packages/rendering/src/rendering/primitives.ts
Due to error in bounding box computation
=> Disable torus segment filtering

examples/src/pages/e2e/cad/ReassignNodeStyle.tsx, viewer/core/src/public/migration/Cognite3DModel.test.ts, viewer/core/src/public/migration/Cognite3DModel.ts, viewer/core/src/public/migration/Cognite3DViewer.ts, viewer/packages/tools/src/Timeline/Keyframe.ts
Removes the need for a seperate updateStyledNodeCollection() function
=> improvement: assignStyledNodeCollection now also handles update

documentation/docs/components/customScope.ts, documentation/docs/examples/geomaptool.mdx, documentation/versioned_docs/version-2.x/components/customScope.ts
Added temporary API keys for all map providers for testing in Docs
=> fix: Added Temporary API keys missing in Docs for all map providers

viewer/packages/cad-geometry-loaders/src/sector/culling/ByScreenSizeSectorCuller.test.ts, viewer/packages/cad-geometry-loaders/src/sector/culling/ByScreenSizeSectorCuller.ts
Node style setting prioritizedForLoadingHint didn't have any effect. Exposed the issue using a unit test and fixed it.
=> fix: issue causing prioritizedLoadingHint to have no effect

viewer/core/src/datamodels/cad/CadModelFactory.ts, viewer/core/src/datamodels/pointcloud/PointCloudManager.ts, viewer/core/src/datamodels/pointcloud/PointCloudMetadata.ts, viewer/core/src/datamodels/pointcloud/PointCloudMetadataRepository.ts, viewer/core/src/public/RevealManager.ts, viewer/packages/metrics/src/MetricsLogger.ts
Collect metrics about model version format to collect data on usage of v8 vs v9 CAD models.
=> improvement: collect metrics for what model versions are loaded

viewer/packages/sector-loader/src/GltfSectorRepository.ts
Allows us to monitor sector loading failure, like we do for v8
=> improvement: track sector loading errors in MixPanel

examples/package.json, examples/yarn.lock, viewer/package.json, viewer/packages/rendering/src/rendering/EffectRenderManager.ts, viewer/yarn.lock
Threejs seems to update fine now, possible I encountered another bug which is fixed now.
=> bump: threejs v136

viewer/core/src/public/migration/Cognite3DModel.ts
=> Fix node style assignment comment

documentation/docs/examples/clipping.mdx, documentation/versioned_docs/version-2.x/examples/clipping.mdx, viewer/packages/camera-manager/src/ComboControls.ts
Resolves issue with the "Interactable clipping plane" example causing navigation to be blocked by the drag controller or the clip plane.
=> doc: fix issue causing navigation to not work with interactable clipping plane example

viewer/core/src/public/migration/Cognite3DViewer.ts
Fixes https://cognitedata.atlassian.net/browse/REV-240
=> fix: typing in Cognite3DModel removeModel

.github/workflows/preview-documentation.yml
Now it really works. I promise.
=> fix(ci): broken preview docs

documentation/package.json, documentation/yarn.lock, examples/package.json, examples/yarn.lock, viewer/package.json, viewer/yarn.lock
updated geo-three library version to fix texture format type change in threejs latest version
=> fix: updated geo-three to fix texture format type error

viewer/yarn.lock
=> chore: fix missing yarn lock update

examples/config-overrides.js, examples/yarn.lock, viewer/package.json, viewer/webpack.config.js
Fixes [REV-352](https://cognitedata.atlassian.net/jira/software/c/projects/REV/issues/REV-352).
=> fix: add tsc alias as a webpack build hook

viewer/core/src/public/migration/Cognite3DViewer.ts, viewer/package.json
- Cherry pick the mixpanel fix
=> chore: bump to reveal 3.0.2

viewer/core/src/public/migration/Cognite3DViewer.ts, viewer/core/src/public/migration/renderOptionsHelpers.ts, viewer/packages/cad-geometry-loaders/src/CadModelUpdateHandler.ts, viewer/packages/cad-model/src/CadManager.ts, viewer/packages/pointclouds/src/PotreeGroupWrapper.ts, viewer/packages/pointclouds/src/potree-three-loader/Potree.ts, viewer/packages/pointclouds/src/potree-three-loader/geometry/PointCloudEptGeometryNode.ts, viewer/packages/pointclouds/src/potree-three-loader/utils/BinaryHeap.ts, viewer/packages/pointclouds/src/potree-three-loader/workers/eptBinaryDecoder.worker.ts, viewer/packages/rendering/src/render-passes/GeometryPass.ts, viewer/packages/rendering/src/render-pipeline-providers/CadGeometryRenderModePipelineProvider.ts, viewer/packages/rendering/src/render-pipeline-providers/CadGeometryRenderPipelineProvider.ts, viewer/packages/rendering/src/render-pipeline-providers/DefaultRenderPipelineProvider.ts, viewer/packages/rendering/src/rendering/primitives.ts, viewer/packages/rendering/src/sector/CadNode.ts, viewer/packages/rendering/src/transform/TransformOverrideBuffer.ts, viewer/packages/rendering/src/utilities/GpuTimer.ts, viewer/packages/rendering/src/utilities/renderUtilities.ts, viewer/packages/sector-parser/src/GltfSectorParser.ts, viewer/packages/sector-parser/tests/GltfSectorParser.test.ts, viewer/packages/utilities/src/DeferredPromise.ts, viewer/packages/utilities/src/calculateVolumeOfMesh.test.ts, viewer/tsconfig.json
Turns on the `strict` option in `tsconfig.json` and makes the build pass.
=> improvement: Make typescript strict

documentation/versioned_docs/version-3.x/API Reference.md, documentation/versioned_docs/version-3.x/components/customScope.ts, documentation/versioned_docs/version-3.x/examples/cad-basic.mdx, documentation/versioned_docs/version-3.x/extending/datasource.mdx, documentation/yarn.lock
Bump reveal 3.x and latest changes
=> chore: bump reveal version 3.x doc

examples/package.json, examples/yarn.lock
Fix linking issues causing watch mode not to work in examples.
=> fix: improper linking of viewer into examples

examples/src/utils/ModelUi.ts
Skipping standard template due to the nature of (i.e. tiny) PR.
=> improvement: better error message when adding model fails

.github/workflows/ci.yml
Fixes an issue in build, causing error
```
ERROR:  Error installing octokit:
The last version of octokit (>= 0) to support your Ruby & RubyGems was 4.25.1. Try installing it with `gem install octokit -v 4.25.1`
octokit requires Ruby version >= 2.7.0. The current ruby version is 2.6.0.0.
```
=> chore: fix broken github actions for preview docs comment on Github

viewer/packages/metrics/src/MetricsLogger.ts
=> fix: missing review fix from #2274

viewer/packages/cad-geometry-loaders/src/sector/culling/ByScreenSizeSectorCuller.ts, viewer/packages/cad-geometry-loaders/src/sector/culling/WeightFunctionsHelper.test.ts, viewer/packages/cad-geometry-loaders/src/sector/culling/WeightFunctionsHelper.ts
Across several models, that is
This fixes https://cognitedata.atlassian.net/browse/REV-440 
=> fix: make sure screen distance min/max accumulates properly

examples/src/utils/CustomCameraManager.ts, viewer/index.ts, viewer/packages/camera-manager/src/CameraManagerHelper.ts
Revert mistaken camera API changes from #2356
=> fix: revert camera helper API change

viewer/packages/rendering/src/pipeline-executors/BasicPipelineExecutor.ts
Fixes an issue where drawing buffer size have a fraction.
=> fix: round calculation of drawing buffer size to an integer

.github/workflows/ci.yml, documentation/docusaurus.config.js, documentation/package.json, documentation/yarn.lock, viewer/packages/api/src/public/migration/Cognite3DViewer.ts
Fixes an issue causing API reference in docs to not include tsdocs comments, caused by new version of typedoc-plugin-markdown. Also fixes an issue causing links and title to be wrong for preview docs due to an upgraded Github Actions plugin.
Also, added timestamp to preview title to make it easier to spot when this breaks.
This reverts commit f7958aa9395376e37713e34bb19d520cb6dfc1d5.
=> doc: fix broken preview docs

viewer/packages/rendering/src/render-pipeline-providers/CadGeometryRenderPipelineProvider.ts
See: https://cognitedata.slack.com/archives/G0115JQ8JM8/p1662968222863869 for context.
=> fix: issue with old frames being visible in highlighted objects

viewer/package.json
Bumping reveal version for release.
=> chore: bump Reveal to 3.2.0

examples/webpack.config.js, examples/yarn.lock
Revert to symlink fix for examples to revive watch mode.
=> fix: revert proper symlinking to revive watching examples

renovate.json
Notify on slack when Renovate creates new PR.
Will be tested next time Renovate creates PR.
=> chore: add 'slack' label to Renovate PRs so they become more visible

renovate.json
Renovate raised issue #2547 
Malformed after PR #2545 
Following the configuration at https://docs.renovatebot.com/configuration-options/#schedule
=> fix: malformed renovate config

viewer/packages/pointclouds/src/potree-three-loader/Potree.ts, viewer/packages/pointclouds/src/potree-three-loader/loading/EptBinaryLoader.ts, viewer/packages/pointclouds/src/potree-three-loader/tree/PointCloudOctreePickerHelper.ts, viewer/packages/rendering/src/glsl/pointcloud/pointcloud.frag, viewer/packages/rendering/src/glsl/pointcloud/pointcloud.vert, viewer/packages/rendering/src/pointcloud-rendering/PointCloudMaterial.ts, viewer/packages/rendering/src/pointcloud-rendering/constants.ts, viewer/packages/rendering/src/pointcloud-rendering/enums.ts, viewer/packages/rendering/src/pointcloud-rendering/types.ts
Removing a lot of the features provided by the `three-loader` library, but that we don't support for our users.
One important exception is parabolic points, which is currently exposed to users as a point shape option, but which is not yet working. The code related to this is therefore preserved. (See https://cognitedata.atlassian.net/browse/REV-545).
=> cleanup: remove unsupported pointcloud features

viewer/Cargo.lock
=> chore: update cargo.lock

.github/workflows/ci.yml, viewer/Cargo.lock, viewer/README.md, viewer/package.json, viewer/packages/pointclouds/package.json
https://cognitedata.atlassian.net/browse/REV-559
To handle long wait times with no output from `wasm-pack`, I've added a preliminary update step that is at least a little more verbose.
In addition, I have added a check for Cargo lock updates in this PR, which will probably make renovate PRs fail, but we should be updating the Cargo lock in those anyway.
-
-
=> chore: improve wasm CI

.github/workflows/ci.yml, viewer/package.json
https://cognitedata.atlassian.net/browse/REV-560
This should, presumably, cause the crates.io cache that `cargo` uses on every build, to stay cached in-between build stages. Updating it is a very expensive operation, so we want to avoid doing this more than once.
This solution was mentioned by @christjt in this thread: https://cognitedata.slack.com/archives/G0115JQ8JM8/p1666269138330529?thread_ts=1666265998.263009&cid=G0115JQ8JM8
--
--
=> chore: add caching to cargo registry in CI

viewer/yarn.lock
--
Fix error in yarn lock that was never supposed to be here :hammer:
=> chore: update yarn lock

.github/workflows/publish-to-npm-on-release.yml
Applying release procedure fix to release/3.2.x branch.
=> fix: backport release workflow

viewer/package.json, viewer/yarn.lock
Revert due to regression. Hitting this: https://github.com/puppeteer/puppeteer/issues/9192
=> fix: revert puppeteer due to failing tests

viewer/packages/cad-geometry-loaders/src/CadManager.ts
https://cognitedata.atlassian.net/browse/REV-566
After removing V8 outputs, removing batched geometry was accedentily also purged...
=> fix: removing batched geometries on sector discarded

viewer/package.json, viewer/packages/data-providers/src/pointcloud-stylable-object-providers/CdfPointCloudStylableObjectProvider.ts, viewer/yarn.lock
https://cognitedata.atlassian.net/browse/REV-541
Ensure that we use the new annotation types from the Cognite SDK.
--
--
=> fix: cleanup annotation types

documentation/package.json, documentation/yarn.lock
Make sure the documentation's SDK for version 4.x is the same that the Reveal 4.x uses, namely the one found in the viewer folder. Has not caused trouble yet, but this ensures it (hopefully) won't.
=> chore: align doc 4.x SDK to that of viewer/

documentation/docs/examples/point-to-point-measurement.mdx, examples/src/utils/MeasurementUi.ts, viewer/packages/tools/src/Measurement/MeasurementManager.ts, viewer/packages/tools/src/Measurement/MeasurementTool.ts
https://cognitedata.atlassian.net/browse/REV-571
It adds ability to hide/unhide all measurements in the viewer
In `examples`, under measurement option, an checkbox is add for hiding/showing the measurements added into the viewer.
Go to `examples`, add measurements, uncheck & check the `Show measurement` option.
Unit test are not added as we need to address it for Measurement Tool as documented in [Unit test for Measurement Tool](https://cognitedata.atlassian.net/browse/REV-439)
=> feat: hide & show measurements

documentation/docs/api_readme.md, documentation/docs/components/LiveCodeSnippet.tsx, documentation/docs/concepts.md, documentation/docs/examples/cad-basic.mdx, documentation/docs/examples/cad-explode.mdx, documentation/docs/examples/cad-save-viewerstate.mdx, documentation/docs/examples/cad-styling-assets.mdx, documentation/docs/examples/cad-styling.mdx, documentation/docs/examples/cad-transform-override.mdx, documentation/docs/examples/click-reactions-cad.mdx, documentation/docs/examples/node-visiting.mdx, documentation/docs/extending/datasource.mdx, documentation/docs/utils/viewerUtilities.ts
Fix Cognite3DModel -> CogniteCadModel in docs.
=> fix: rename Cognite3DModel to CogniteCadModel in docs

.github/workflows/ci.yml
CI builds are failing on the Cargo lock check recently. This might be because subdependencies of dependencies in the `Cargo.toml` get updated patch versions, which are automatically preferred by `cargo update`. Using `--offline` prevents Cargo from trying to check for these miniscule updates.
=> chore: prevent subdependency patch updates failing cargo lock check

viewer/Cargo.lock
=> fix: update cargo lock

documentation/docs/examples/cad-basic.mdx, viewer/packages/api/src/public/migration/Cognite3DViewer.ts, viewer/packages/api/visual-tests/Outline.VisualTest.ts
https://cognitedata.atlassian.net/browse/REV-489
- Added an optional alpha parameter to setBackgroundColor.
- Made color parameter optional so that transparency can be set without the need to provide a color. If no color is provided the current applied color is used.
- Updated documentation to reflect the change.
Note: Today the "Spinner" color is updated based on the background color. The current implementation will not work as well after this change as alpha is not considered in the lightness check. However, this is also a problem with background images, so it has been deemed outside the scope of this task and should be looked at in a separate refactoring.
I have tested this using the "primitives" model.
This can be tested using the documentation:
=> feat: add alpha parameter to setBackgroundColor

examples/yarn.lock, viewer/package.json
=> chore: Bump reveal version to 3.3.0

viewer/packages/rendering/src/glsl/pointcloud/edl.glsl, viewer/packages/rendering/src/glsl/pointcloud/normalize.frag, viewer/packages/rendering/src/render-passes/PostProcessingPass.ts, viewer/packages/rendering/src/render-passes/types.ts, viewer/packages/rendering/src/render-pipeline-providers/DefaultRenderPipelineProvider.ts, viewer/packages/rendering/src/render-pipeline-providers/PointCloudRenderPipelineProvider.ts, viewer/packages/rendering/src/render-pipeline-providers/types.ts, viewer/packages/rendering/src/utilities/renderUtilities.ts
https://cognitedata.atlassian.net/browse/REV-547
This allows for using EDL and point cloud blending together.
By... Enabling EDL and point blending simultaneously
Open examples with your favorite point cloud, enable point blending.
=> feat: enable point blending and EDL together

documentation/docs/migration-guide.md, viewer/api-entry-points/core.ts
Fixup related to #2691 :
- Add `SerializableNodeAppearance` to exports
- Add entry in migration docs about the change
=> fix: three color api fixup

viewer/packages/pointclouds/index.ts, viewer/packages/pointclouds/src/PotreePnextLoader.ts, viewer/test-utilities/src/createPointCloudModel.ts, viewer/visual-tests/test-fixtures/StreamingVisualTestFixture.ts
Solves part of https://cognitedata.atlassian.net/browse/REV-497
Removes the file `PotreePnextLoader.ts` in pointclouds package.
All its exports were used by test modules, which can import directly with a path. They should not be exposed by the package interface.
=> cleanup: remove PotreePnextLoader and pointclouds package exports

viewer/packages/api/src/public/createRevealManager.ts, viewer/packages/pointclouds/index.ts, viewer/packages/pointclouds/src/PointCloudLoadingStateHandler.test.ts, viewer/packages/pointclouds/src/PointCloudLoadingStateHandler.ts, viewer/packages/pointclouds/src/PointCloudManager.ts, viewer/packages/pointclouds/src/PointCloudNode.ts, viewer/packages/pointclouds/src/PotreeGroupWrapper.test.ts, viewer/packages/pointclouds/src/PotreeGroupWrapper.ts, viewer/packages/pointclouds/src/PotreeNodeWrapper.ts, viewer/test-utilities/src/createPointCloudModel.ts
Partially solves https://cognitedata.atlassian.net/browse/REV-498
Refactor and renames `PotreeGroupWrapper` to a class that only keeps track of loading state for point clouds.
By seeing that everything works as expected.
=> refactor: shrink and rename PotreeGroupWrapper

viewer/api-entry-points/core.ts, viewer/packages/camera-manager/app/index.ts, viewer/packages/camera-manager/index.ts, viewer/packages/camera-manager/src/ComboControls.ts, viewer/packages/camera-manager/src/DefaultCameraManager.ts
https://cognitedata.atlassian.net/browse/REV-500
- Removed `get cameraControls` from `DefaultCameraManager`.
- Moved all public properties from `ComboControls` into a new type; `ComboControlsOptions`.
- Created private `ComboControlsOptions` property with default values on `ComboControls`.
- Added getter and setter for `ComboControlsOptions` in `DefaultCameraManager`.
- Created getter and setter for 'enabled' in `ComboControls`.
Note:
- In `ComboControls` there are a lot of temp objects created from 'this'. I have consistently not used this for any of the options and written out the full name, e.g. `this._options.enableKeyboardNavigation`.
- `DefaultCameraManager` now has both a `comboControlsOptions` and a `_cameraControlsOptions` which could be confusing.
Unit & visual test. Temporarily …
=> feat: Remove exposing ComboControls from DefaultCameraManager

documentation/docs/extending/camera-manager.mdx
https://cognitedata.atlassian.net/browse/REV-599
1. Copied latest CameraManager and CustomCameraManager code into docs.
2. Added a 4th point to the list of things to note, describing the expected implementation of activate, deactivate and get enabled (With some extra spacing for readability).
Built documentation and had a look.
Build documentation and have a look. :)
=> docs: Update 'extending/camera-manager' to reflect changes in CameraManager

viewer/test-utilities/src/expects.ts
Just some cleanup
Tests are passing. What more do you need!?
=> chore: cleanup test utilities

examples/src/utils/Image360UI.ts, viewer/api-entry-points/core.ts, viewer/packages/360-images/index.ts, viewer/packages/360-images/src/Image360.ts, viewer/packages/360-images/src/Image360Entity.ts, viewer/packages/360-images/src/Image360Visualization.ts, viewer/packages/api/src/api-helpers/Image360ApiHelper.ts, viewer/packages/api/src/public/migration/Cognite3DViewer.ts
By exporting the full `Image360Entity`, we also exported a constructor (only used internally) with a few arguments that we would prefer to keep within Reveal's bounds.
This extracts an interface that is exported in place of Image360Entity.
=> fix: strip down 360 exports to interfaces only

renovate.json, viewer/package.json, viewer/packages/cad-styling/src/PopulateIndexSetFromPagedResponseHelper.test.ts, viewer/packages/data-providers/src/metadata-providers/CdfModelMetadataProvider.ts, viewer/packages/data-providers/src/utilities/fetchWithStatusCheck.ts, viewer/yarn.lock
Removes `@cognite/sdk-core`. It is unnecessary to keep it as a separate dependency.
=> chore: remove dependency on @cognite/sdk-core

documentation/docs/extending/camera-manager.mdx, examples/src/utils/CustomCameraManager.ts
Seems like I forgot to dispose of the stop event trigger at a couple of places.
Fixed.
It hasn't.
=> fix: add in missing event trigger dispose() in examples

examples/src/utils/PointCloudObjectStylingUI.ts
The range in the object id for point cloud object styling assignment in the UI in examples was off. It's fixed now
=> fix: correct object ID range in styling UI

documentation/docs/migration-guide.md, documentation/versioned_docs/version-4.x/migration-guide.md
This section needs to be added to the docs.
=> doc: classification list signature change

examples/public/index.html
=> chore: remove duplicate script imports in example HTML

viewer/packages/camera-manager/src/DefaultCameraManager.ts
None
I noticed that when gizmos are used in example (Last Clicked Node -> drag and Add GLTF model with gizmo) the camera input is still handled when using the DefaultCameraManager. The manager is deactivated during drag, but the controls are not. This change fixes this.
Note: This is already implemented and working for CustomCameraManager.
I tested in examples project. Using the two gizmos described above. Also switching between Default and Custom camera manager and going in and out of 360 images.
See above.
=> bug: Fixed controls in DefaultCameraManager not being disabled when the manager is deactivated

renovate.json
We seem to have a lot of new dependency updates coming in, too many that we have time to merge them and get new updates through Renovate within the timeframe it is running (which is 06:00 to 09:00 every weekday). It is also limited to 5 PRs in parallel, which make these working hours an unnecessarily harsh restriction, especially when we have long-running dependency PRs, like `moq.ts` and `three` right now. 
I propose to extend the working hours for Renovate to fill more of the working day, to ensure Renovate has time to create all the new PRs it wants.
In addition, after [some discussion](https://cognitedata.slack.com/archives/G0115JQ8JM8/p1671439647560509) in the Slack channel, it seemed to be an opinion towards removing Renovate notifications …
=> chore: expand Renovate work hours and remove Slack label

examples/src/pages/Viewer.tsx, viewer/packages/pointclouds/src/potree-three-loader/Potree.ts
Also, add helpful frustum viewer when suspending loading.
This was used when creating screenshots for issue https://cognitedata.atlassian.net/browse/REV-646
=> chore: enable suspending point clouds from Viewer.tsx

documentation/package.json, examples/package.json, viewer/package.json
=> chore: update contributor list

documentation/docs/examples/click-reactions-pointcloud.mdx, viewer/packages/api/src/public/migration/Cognite3DViewer.ts, viewer/packages/data-providers/src/pointcloud-stylable-object-providers/CdfPointCloudStylableObjectProvider.ts, viewer/packages/data-providers/src/pointcloud-stylable-object-providers/cdfAnnotationsToObjects.ts, viewer/packages/data-providers/src/pointcloud-stylable-object-providers/types.ts, viewer/packages/pointclouds/src/CognitePointCloudModel.ts, viewer/packages/pointclouds/src/PointCloudIntersection.ts, viewer/packages/pointclouds/src/PointCloudNode.ts, viewer/packages/pointclouds/src/PointCloudPickingHandler.ts, viewer/packages/rendering/src/pointcloud-rendering/PointCloudObjectAppearanceTexture.ts, viewer/reveal.api.md
https://cognitedata.atlassian.net/browse/REV-630
This adds `assetId` as an optional output in the result object from point cloud picking. The asset id is taken from the annotation associated with the object in the point cloud that was picked. 
[REV-630]: https://cognitedata.atlassian.net/browse/REV-630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: asset id in point cloud pick result

documentation/package.json, documentation/versioned_docs/version-4.x/package.json
https://cognitedata.atlassian.net/browse/REV-549
Properly get rid of everything in the version-4.x folder before copying in the content in the docs-folder, to make sure that e.g. .md files for deleted classes are gone.
Created artifical file in version-4.x/api, observe it's deleted on update.
=> chore: remove directory on doc update

viewer/packages/pointclouds/src/potree-three-loader/tree/PointCloudOctreePickerHelper.ts, viewer/packages/rendering/src/glsl/pointcloud/pointcloud.vert, viewer/packages/rendering/src/pointcloud-rendering/PointCloudMaterial.ts
https://cognitedata.atlassian.net/browse/REV-626
Don't allow points styled invisible to be clicked.
This is done by properly using the object-to-style texture with the picking material.
See Jira issue
=> fix: don't enable click on invisible point cloud objects

documentation/docs/overview.mdx
https://cognitedata.atlassian.net/browse/REV-67
=> docs: add examples for converting between CDF and Viewer space

viewer/packages/cad-model/src/wrappers/CogniteCadModel.ts, viewer/packages/pointclouds/src/CognitePointCloudModel.ts, viewer/reveal.api.md
https://cognitedata.atlassian.net/browse/REV-652
Description in issue. But in any case - converting from CDF coordinates to model coordinates is pretty tedious right now. This may make it easier.
- Downloaded root node bounding box from CDF
- Transformed with this new method
- Visualized result
=> feat: re-introduce transformation mapping functions

viewer/packages/tools/src/Measurement/MeasurementLine.ts
https://cognitedata.atlassian.net/browse/REV-532
Issue with measurement tool line segments having floating point precision issues for large models.
See Jira ticket for testing and reproducing.
=> fix: measurement tool for large models not being temporally coherent

documentation/docs/examples/cad-basic.mdx, documentation/docs/examples/pointcloud.mdx
A couple of links and model/revision IDs in the documentation were wrong. 
Click the link, find the models
=> docs: correct model ID in examples

viewer/package.json, viewer/packages/pointclouds/src/potree-three-loader/geometry/PointCloudEptGeometry.ts, viewer/yarn.lock
Our only use of `proj` is the `proj()` function, which returns an object that can be used to translate between different (global) coordinate conventions. But we never use the returned value, so it seems like the entire library is unneeded.
=> chore: remove proj4 as dependency

viewer/packages/tools/src/HtmlOverlay/HtmlOverlayTool.ts
https://cognitedata.atlassian.net/browse/REV-582
Clip Html overlay elements on clipping planes, if center point is outside
- Open https://localhost:3000/?env=greenfield-3d&project=3d-test&modelId=5244774438818744&revisionId=2249063501234508
- Node Tagging -> Filter category = PDMS, Filter key = Purp of Zone, Filter property value = BWS
- Create overlays
- Clipping -> Global
- Check Z and Flip Z
- Slide back and forth and observe overlays appearing/disappearing
=> fix: clip HtmlOverlayTool on global clipping planes

viewer/package.json
=> chore: bump reveal version to 4.1.0

viewer/README.md
Removed some outdated instructions in the README
=> chore: clean up insallation instructions in README

viewer/packages/tools/src/Measurement/MeasurementTool.ts
https://cognitedata.atlassian.net/browse/REV-721
The measurement tool listens to `viewer.domElement` event for `Esc` key down event
In `examples` & `documentation`
=> Refactor: updated keydown event to listen viewer.domElement in measurement tool

viewer/package.json
=> chore: bump reveal to 4.1.1

viewer/package.json, viewer/yarn.lock
We now only use it transcendently, or whatever it's called. This should be merged prior to closing https://github.com/cognitedata/reveal/pull/2948
=> chore: remove comlink as dependency

documentation/docusaurus.config.js, documentation/removeTrailingSlash.js, viewer/packages/api/src/api-helpers/Image360ApiHelper.ts
https://cognitedata.atlassian.net/browse/REV-772
For more info see: https://cognitedata.slack.com/archives/C8A0QGMLN/p1676388107005099
=> fix: broken links due to trailing slash

viewer/packages/api/src/api-helpers/Image360ApiHelper.ts, viewer/packages/api/src/public/migration/Cognite3DViewer.ts, viewer/packages/metrics/src/types.ts
https://cognitedata.atlassian.net/browse/REV-764
=> chore: add metrics for 360 image add/enter/transition/exit

viewer/package.json, viewer/yarn.lock
This package seems to be unused.
=> chore: remove @types/expect-puppeteer as dependency

viewer/Cargo.lock
Update Cargo.lock, as it seems to obstruct CI
=> chore: update Cargo lock

viewer/packages/cad-parsers/package.json, viewer/packages/cad-parsers/src/metadata/parsers/CadMetadataParserGltf.ts, viewer/packages/metrics/src/types.ts, viewer/yarn.lock
https://cognitedata.atlassian.net/browse/REV-774
Alert us whenever someone adds a textured model.
To be honest, it hasn't.
=> chore: add metrics related to textured models

viewer/packages/360-images/src/icons/IconCollection.ts, viewer/packages/360-images/src/icons/IconOctree.test.ts, viewer/packages/360-images/src/icons/IconOctree.ts, viewer/packages/360-images/src/icons/InstancedIconSprite.ts
https://cognitedata.atlassian.net/browse/REV-805
360 images are now grouped to the median point in the cluster (closest to bound center). Also added a minimal traversal from root such that there is a max amount of clustering that can happen.
Manual test on the Hibernia_RS2 data set as well as all others available in 3D-test. Also has unit + visual test.
Open Hibernia set an look at 360 image collection from different angle / zoom.
=> feat: cluster icons using a median icon strategy

viewer/yarn.lock
An attempt to fix the "critical" security issues listed in the security tab.
=> fix: bump transitive loader-utils v2 to fix critical prototype pollution issue

documentation/yarn.lock
Bump loader-utils in documentation to mitigate security vulnerabilities
=> fix: bump loader-utils in documentation

viewer/packages/api/src/public/migration/Cognite3DViewer.ts, viewer/reveal.api.md
https://cognitedata.atlassian.net/browse/REV-806
Add 'cameraStop' event directly on the viewer, in the same way we have a 'cameraChange' event. Now both events exist both on the viewer and on the CameraManager.
Add a line in `Viewer.tsx` that console logs something in  a callback registered on the `cameraStop` event on the viewer.
=> feat: add cameraStop event to viewer

viewer/package.json
It's happening :crossed_fingers:
=> chore: bump 4.2.0

viewer/Cargo.lock, viewer/package.json, viewer/packages/pointclouds/src/potree-three-loader/tree/PointCloudOctreePicker.ts, viewer/packages/pointclouds/src/potree-three-loader/tree/PointCloudOctreePickerHelper.ts
Same as #3116 , but for release branch.
=> fix: adaptive point picking being unprecise

.github/workflows/ci.yml
Fix the recent error in preview doc
=> chore: change include file syntax in gha-find-replace

viewer/packages/360-images/src/annotation/BoxAnnotationData.ts, viewer/packages/360-images/src/annotation/ImageAnnotationData.ts, viewer/packages/360-images/src/annotation/ImageAnnotationObject.ts, viewer/packages/360-images/src/annotation/PolygonAnnotationData.ts, viewer/packages/360-images/src/entity/Image360RevisionEntity.ts
https://cognitedata.atlassian.net/browse/REV-879
Support polygon annotations in 360 images
- Start Reveal
- Open https://localhost:3000/?project=3d-test&env=greenfield-3d&modelId=4923307033982497&revisionId=3100284276970593
- Load 360 images named `helideck-site-2-jpeg`
- Enter the lowermost 360 image, at the edge of the helipad
- Observe that polygon annotations (along with imprecise rectangular annotations) associated with the images are visible
=> feat: support polygon annotations

renovate.json5
Make Renovate use default settings, rebasing branches when they are out of date
=> chore: make renovate auto-rebase

viewer/packages/360-images/src/collection/DefaultImage360Collection.ts, viewer/packages/api/src/api-helpers/Image360ApiHelper.ts, viewer/packages/api/src/public/migration/Cognite3DViewer.ts
Change the `needsRedraw` interface for 360 images to conform to the rest of Reveal
=> refactor: change 360 image redraw request flow

viewer/packages/cad-geometry-loaders/src/CadManager.ts, viewer/packages/cad-model/src/wrappers/CadNode.ts
I noticed this while working on https://github.com/cognitedata/reveal/pull/3178
If we set a custom transform on any model, we set the redraw flag, but never reset it.
This fixes it.
=> fix: don't redraw forever when setting custom transform

examples/yarn.lock, viewer/Cargo.lock, viewer/package.json, viewer/packages/360-images/src/collection/DefaultImage360Collection.ts, viewer/packages/360-images/src/collection/Image360CollectionFactory.ts, viewer/packages/360-images/src/entity/Image360Entity.ts, viewer/packages/360-images/src/entity/Image360VisualizationBox.ts, viewer/packages/360-images/unit-tests/Image360CollectionFactory.test.ts, viewer/packages/360-images/unit-tests/Image360Entity.test.ts, viewer/packages/360-images/visual-tests/Image360.VisualTest.ts, viewer/packages/api/src/api-helpers/Image360ApiHelper.ts, viewer/packages/cad-geometry-loaders/src/CadManager.ts, viewer/packages/cad-model/src/wrappers/CadNode.ts, viewer/packages/data-providers/src/image-360-data-providers/Cdf360ImageEventProvider.ts, viewer/test-utilities/src/setupJest.ts
Cherry picks of commits related to 360 image fixes.
=> fix: cherry pick 360 image bug fixes into 4.2

examples/src/utils/Image360StylingUI.ts
Make sure 360 annotation color applied through the Image360StylingUI uses colors that resemble those shown in dat.gui.
Before:
After:
Notice that the first is a little too dark compared to the color showed in the UI. 
This is related to the change in threejs r152, where `ColorManagement` was set to `true` by default, as described in https://threejs.org/docs/#manual/en/introduction/Color-management
=> chore: use linear-to-SRGB-conversion in Image360 styling UI

examples/public/index.html
Since upgrading to React 18, the dat.GUI tools in the examples would render twice. This fixes the issue.
Also wondering how long this has been residing in the HTML file :thinking: 
Resize the dat.GUI tools with mouse to see that there are no duplicate hiding behind
=> chore: fix double GUI in example

viewer/packages/360-images/src/annotation/Image360Annotation.ts, viewer/packages/360-images/src/annotation/ImageAnnotationObject.ts, viewer/packages/360-images/src/collection/DefaultImage360Collection.ts, viewer/packages/360-images/src/collection/Image360Collection.ts, viewer/packages/360-images/src/entity/Image360RevisionEntity.ts, viewer/reveal.api.md
- Add getters
- Ensure only visible annotations are intersected
- Load 360 image `helideck-site-2-jpeg`
- Enter lower-most image
- Click annotation
- Observe console log
- Hide all annotations using styling UI
- Click annotated object
- Observe no console log
=> feat: annotation getters and only intersect visible annotations

viewer/packages/360-images/src/collection/DefaultImage360Collection.ts, viewer/packages/360-images/src/collection/Image360Collection.ts, viewer/packages/360-images/src/collection/Image360CollectionFactory.ts, viewer/packages/360-images/src/entity/Image360.ts, viewer/packages/360-images/src/entity/Image360Entity.ts, viewer/packages/360-images/src/entity/Image360Revision.ts, viewer/packages/data-providers/src/image-360-data-providers/Cdf360ImageEventProvider.ts, viewer/packages/data-providers/src/types.ts, viewer/reveal.api.md
Add label and id to collection and fix underlying label types.
=> feat: add label and id to collection and fix underlying label types.

viewer/yarn.lock
Fixes this CVE: https://github.com/cognitedata/reveal/security/dependabot/277
=> fix: update webpack transitive dependency

documentation/docs/examples/image360-annotations.mdx, examples/src/utils/Image360UI.ts, viewer/packages/360-images/src/annotation/Image360Annotation.ts, viewer/packages/360-images/src/annotation/ImageAnnotationObject.ts, viewer/packages/360-images/src/collection/DefaultImage360Collection.ts, viewer/packages/360-images/src/collection/Image360Collection.ts, viewer/packages/api/src/api-helpers/Image360ApiHelper.ts, viewer/packages/api/src/public/migration/Cognite3DViewer.ts, viewer/reveal.api.md
Provides a few additions to the 360 API. Some of these are wanted for the next release of Data Explorer:
- Ability to get original color of an annotation
- Renamed `findImageAnnotation` -> `findImageAnnotations`
- Add `get360ImageCollections` method on viewer to list image collections
- Add new `remove360ImageCollection` method on viewer to remove
collection
- Deprecated `remove360Images` method on viewer
- Added some more TSDocs
=> feat: add 360 image list-getter, annotation default color and some adjustments

viewer/package.json
=> chore: bump to version 4.3.0

viewer/packages/data-providers/src/image-360-data-providers/Cdf360ImageEventProvider.ts
=> fix: image annotation asset list

RELEASING.md
Update the release template to reflect what the template we are actually using
=> chore: update release template

viewer/package.json
=> chore: bump version 4.3.1

.github/workflows/publish-react-component-to-npm-on-demand.yml, react-components/package.json, react-components/src/components/Toolbar/Image360HistoricalSummary.tsx, react-components/src/components/View/Image360HistoricalDetails.tsx
Updated styling of 360 historical react component which fixes gap issues at the bottom and extends the station name & id character limitation
In data explorer & storybook
- `run yarn storybook`
- Select `Image360HistoricalSummary` example
=> fix: updated styling of historical 360 react component

viewer/packages/data-providers/src/image-360-data-providers/Cdf360ImageEventProvider.ts
Make sure to list all asset IDs and annotations in CDF queries. Forgot that `autoPagingToArray` takes an argument :see_no_evil:
=> fix: make sure autoPagingToArray gives all results

viewer/package.json
=> chore: bump 4.3.2

examples/src/pages/Viewer.tsx, examples/src/utils/NodeTransformUI.ts
- Open CAD model in examples
- Write some numbers in the Node Transform UI
- Select node range (e.g. all)
- Click Apply
- Observe that parts (or all) of the model moves according to the input values
=> chore: node transform UI in examples

examples/src/utils/Image360UI.ts, viewer/packages/360-images/src/Image360Facade.ts, viewer/packages/api/src/api-helpers/Image360ApiHelper.ts
Fix a bug where removing a 360 image set was faulty, causing re-adding it to throw an exception.
Also add UI in the example for removing a single 360 image set.
- Open e.g. https://localhost:3000/?project=3d-test&env=greenfield-3d&modelId=4923307033982497&revisionId=3100284276970593
- Load 360 image set, e.g. XOM-HCU1_north_v02
- Click the remove button right underneath the add-button
- Click the add button again
- Click the remove button again
- Click the add button again
- Click the remove button again
- Click the add button again
- Click the remove button again
- Repeat until your brain stops emitting dopamine from the clicking
=> fix: 360 image set removal

viewer/package.json
=> chore: bump 4.3.3

viewer/packages/api/src/public/migration/Cognite3DViewer.ts
Make sure Viewer disposes and removes all models when it is disposed itself. Fixed by not iterating over model list, which is simultaneously mutated.
=> fix: viewer.dispose() not removing all models

viewer/package.json
=> chore: bump reveal to 4.3.4

react-components/package.json
=> chore(react-components): bump react components to v0.2.0

react-components/package.json
Bump react-components to version 0.2.1
=> chore(react-components): bump to version 0.2.1

.github/workflows/ci.yml
=> fix(CI): ci crashing when running from a push event

react-components/package.json
=> chore(react-components): bump to version 0.3.0

react-components/package.json
=> chore(react-components): bump to v0.5.0

viewer/package.json
=> chore: bump reveal to 4.4.0

react-components/package.json
=> chore(react-components): bump to v0.6.1

react-components/src/components/Reveal3DResources/Reveal3DResources.tsx, react-components/src/components/Reveal3DResources/queryMappedData.ts
To facilitate CDF-only usage too.
Will throw error when trying to use FDM without config.
=> fix: make FDM config non-required in 3DResources

.github/workflows/react-components-ci.yml, react-components/stories/HighlightNode.stories.tsx, react-components/stories/ModelsStyling.stories.tsx, react-components/stories/Reveal3DResources.stories.tsx, react-components/tsconfig.json
Adds previously missing typechecking to storybook components.
=> chore(react-components): add typechecking for react components stories

react-components/package.json
=> chore(react-components): bump reveal react components to version 0.7.0

react-components/package.json
=> chore: bump react-components 0.11.0

react-components/src/components/CadModelContainer/useApplyCadModelStyling.tsx
Fixing incorrect check for equality of two TreeIndexNodeCollections.
Any story related to styling.
=> fix(react-components): Incorrect check for equality

react-components/src/components/RevealToolbar/MeasurementButton.tsx
https://cognitedata.atlassian.net/browse/UX-1290
Fix bug where starting a measurement, and then navigating out of viewer mode, causing toolbar to unmount, would not cancel measurement properly.
In Toolbar story. 
Ensure clicking the button a second time cancels measurements.
Ensure navigating to other story after starting measurement, cancels without errors.
=> fix: reset Measurement tool on unmount

react-components/src/components/Reveal3DResources/Reveal3DResources.tsx, react-components/src/components/Reveal3DResources/types.ts
Remove `onNodeClick` in favor of `useClickedNodeData`.
=> break: remove `onNodeClick`

viewer/package.json
=> chore: bump reveal to version 4.4.1

viewer/packages/tools/src/Measurement/MeasurementTool.ts
Since 4.4.1, MeasurementTool would not permit events to propagate to the viewer. However, events would also not reach UI overlaying the canvas, and would instead trigger starting/ending a measurement.
Fix originally proposed by @christjt
=> fix(viewer): only do measurement on canvas

react-components/package.json, react-components/yarn.lock
=> chore: add `assert` as dependency

react-components/package.json, react-components/src/components/NodeCacheProvider/FdmNodeCache.ts, react-components/src/components/NodeCacheProvider/RevisionFdmNodeCache.ts, react-components/src/hooks/types.ts, react-components/src/hooks/useCalculateModelsStyling.tsx
One FDM asset may map to multiple CDF nodes in different subtrees, which we do not account for in styling. This fixes it.
On problematic Celanese data
Either
- Have access to Celanese data and use it
- Beg for access
- Create your own bug-inducing FDM-to-CDF mapping
=> fix: fdm asset to multiple cdf nodes mapping in styling

react-components/package.json
Bump of reveal-react-components-package
=> chore(react-components): Bump version of react components

react-components/package.json
=> chore: bump react components version to 0.15.0

react-components/package.json
To release node cache keep-alive update
=> chore(react-components): bump 0.15.1

react-components/package.json
Bump to version 0.15.2, including fix for viewer anchor sticky-transformation
=> chore(react-components): bump to version 0.15.2

viewer/package.json
=> chore: bump 4.4.3

react-components/package.json, react-components/yarn.lock
=> chore: bump react components and reveal peer dependency

react-components/package.json
Bump `reveal-react-components` to v.0.17.0
=> chore(react-components): bump to version 0.17.0

react-components/src/components/CadModelContainer/CadModelContainer.tsx
Ensure loading of CAD model is not attempted twice.
Linked into FDX, where some serious issues are happening...
=> fix(react-components): race condition in CadModelContainer initialization

react-components/src/components/Image360CollectionContainer/Image360CollectionContainer.tsx, react-components/src/components/PointCloudContainer/PointCloudContainer.tsx
Fix a problem equivalent to https://github.com/cognitedata/reveal/pull/3807 for point clouds and 360 image collections
Running with FDX locally, default scene in 3d-test.
=> fix(react-components): race conditions in point cloud and 360 loading

documentation/docs/examples/pointcloud.mdx, viewer/packages/pointclouds/src/CognitePointCloudModel.test.ts, viewer/packages/pointclouds/src/CognitePointCloudModel.ts, viewer/reveal.api.md
Current Point cloud model can be made invisible through `model.setDefaultPointCloudAppearance({visible: false})`, this causes issue when an styling of point cloud model is enable/triggered which overrides the invisible appearance.
This PR exposed visibility property similar to `CogniteCadModel` 
In docs
- `cd viewer && yarn && yarn build:prod`
- `cd docs && yarn && yarn build && yarn start`
- Select Point cloud example and choose `Hide model` option
=> feat: added point cloud model visibility property

documentation/docs/examples/image360-annotations.mdx, documentation/versioned_docs/version-4.x/examples/image360-annotations.mdx, examples/src/utils/Image360UI.ts
Redraw on annotation style update, and let the world know.
In examples
Go to examples and read the docs
=> docs: fix and document annotation style update best practices

viewer/package.json
=> chore: bump to @cognite/reveal@4.5.0

react-components/package.json, react-components/src/components/RevealToolbar/LayersContainer/PointCloudLayersContainer.tsx, react-components/yarn.lock
Also, bump reveal version
https://cognitedata.atlassian.net/browse/BND3D-2315
Fix the point cloud layer trouble by using the new `.visible` field on point clouds exposed in Reveal 4.5. The toggle now functions in the same way that the CAD one does.
Note that I'm really not a fan of the architecture for this solution, especially how point cloud containers (and CAD and 360 images as well) read the initial toggle state from the URL, and model visibility is mutated directly from the toggle container, instead of through a declarative prop.
But this will do for now.
Supersedes https://github.com/cognitedata/reveal/pull/3806.
In storybook, LayerContainer story.
Check that it works in Storybook.
=> fix(react-components): point cloud layer toggle error

react-components/package.json, react-components/yarn.lock
Includes important version bump of Reveal, and also 360 search image hook
=> chore(react-component): bump 0.19.0

.github/workflows/ci.yml
Currently, CD is not having a good time. Trying to fix it with this.
=> chore: use the right hash for all cargo registry references

react-components/package.json
Bumped `react-components` to v.0.20.0
=> chore(react-components): bump react-components to v0.20.0

react-components/package.json
Bump version of react-components to 0.20.1
=> chore(react-components): bump 0.20.1

.github/workflows/ci.yml, .github/workflows/locize-sync.yml, .github/workflows/nightly-publish-to-npm.yml, .github/workflows/publish-react-component-to-npm-on-demand.yml, .github/workflows/publish-to-npm-on-release.yml, .github/workflows/react-components-ci.yml
Following this guide: https://cognitedata.atlassian.net/wiki/spaces/SEC/pages/4074176548/Access+to+GitHub+actions+secrets+using+GitHub+Environments, this PR introduces the following changes:
- CI steps now use NPM_READONLY_TOKEN, and not NPM_PUBLISH_TOKEN
- CD now uses the CD environment to read the publish token from
- Both viewer and react-components CI are run when CI scripts are updated
:crossed_fingers:
=> chore: update CI/CD secret usage

.github/workflows/publish-to-npm-on-release.yml
=> chore: add workflow dispatch option to release Reveal

react-components/package.json, react-components/src/hooks/useCameraNavigation.tsx, react-components/src/hooks/useClickedNode.tsx, react-components/yarn.lock
Expose methods to fit to multiple instances/nodes, not just one.
In FDX locally
=> feat(react-components): fit-camera-to-nodes and bump version 0.21.0

.github/workflows/locize-sync.yml, .github/workflows/nightly-publish-to-npm.yml, .github/workflows/publish-react-component-to-npm-on-demand.yml, .github/workflows/publish-to-npm-on-release.yml
Exactly what the title says
:crossed_fingers:  
:pray:
=> chore: use Node 20 in CI

react-components/package.json
Bump to 0.22.1 to get out fix for direct-relation query
=> chore(react-components): bump to 0.22.1

viewer/package.json
Bump Reveal to 4.7.0
- [x ] I have performed a self-review of my own code.
=> chore: bump to 4.7.0

.github/workflows/publish-to-npm-on-release.yml
=> chore: fix publishscript

.github/workflows/publish-to-npm-on-release.yml
=> chore: add sudo in install step, release script

.github/workflows/publish-to-npm-on-release.yml
=> chore: add more essential dependencies to publish script

viewer/package.json
Release fix to model loading order
=> chore: bump 4.7.1

react-components/src/components/Widgets/WidgetHeader.tsx, react-components/src/components/Widgets/WindowWidget.tsx
Closing of split window functionality was missing, this PR enables the functionality.
In Storybook
- Run `SplitWindow` storybook example in `react-components` and Click 'Close` Button.
=> chore(react-components): closing of split window

react-components/package.json
=> chore(react-components): bump version to 0.24.0

react-components/package.json
Bump to 0.24.1, releasing fix to asset mappings hook
=> chore(react-components): bump 0.24.1

react-components/src/hooks/useSearchMappedEquipmentAssetMappings.tsx
Fixes a bug where multiple equal asset Ids would cause an error 
Linked to FDX, saw that it worked
in fusion repo: 
Add model 
```
{
modelId: 7617970672125413,
revisionId: 8633577232574048,
}
```
to Config.ts for the cog-dss config.
Navigate to https://cog-dss.dev.fusion.cogniteapp.com/dss-dev/search/file/15_9_19_A_1997_07_25?aiSearch=false&cluster=greenfield.cognitedata.com&env=greenfield&viewMode=3d&cameraPosition=%5B110.22930928843%2C19.638732681049458%2C-116.89489024014031%5D&cameraTarget=%5B107.93141861984606%2C18.288481774297672%2C-108.88116091311902%5D&cadLayersState=%5B%7B%22revisionId%22%3A8757902535696137%2C%22applied%22%3Afalse%2C%22index%22%3A0%7D%2C%7B%22revisionId%22%3A8633577232574048%2C%22applied%22%3Atrue%2C%22index%22%3A1%7D%5D&selectedInstance=%7B%22externalId%22%3A%2241 …
=> fix(react-components): deduplicate ids in asset queries

react-components/src/common/i18n/en/reveal-react-components.json
Need the strings to be pushed to locize before today for sent for translation
=> chore(react-components): added tooltip string for Camera reset button

react-components/src/hooks/use3dScenes.tsx
Fixes transformation to align with new scene component.
=> fix(react-components): fixed transform for FDM scenes hook

react-components/package.json
Bump reveal react components version as we need to release a new version
=> Bump reveal react components version

react-components/src/hooks/useSearchMappedEquipmentFDM.tsx, react-components/src/index.ts
React-components did not tackle searches with more than 10 views at a time properly. So we will now do them in series instead when applicable.
Linked into Fusion
=> fix(react-components): accomodate searches with many views too

react-components/package.json
Bump reveal react components in order to release new version
=> chore(react-components): Bump version

react-components/src/common/i18n/de/reveal-react-components.json, react-components/src/common/i18n/en/reveal-react-components.json, react-components/src/common/i18n/es/reveal-react-components.json, react-components/src/common/i18n/fr/reveal-react-components.json, react-components/src/common/i18n/it/reveal-react-components.json, react-components/src/common/i18n/ja/reveal-react-components.json, react-components/src/common/i18n/ko/reveal-react-components.json, react-components/src/common/i18n/nl/reveal-react-components.json, react-components/src/common/i18n/pt/reveal-react-components.json, react-components/src/common/i18n/sv/reveal-react-components.json, react-components/src/common/i18n/zh/reveal-react-components.json
Update the translation string with new language keys & strings for December release
=> chore(react-components): updated translation string for December release

react-components/package.json
=> chore(react-components): bump version to 0.26.1

react-components/package.json, react-components/src/hooks/useSceneDefaultCamera.tsx
Correct a bug where the camera becomes degenerate when initially applied to scene default camera.
=> fix(react-components): correct initial scene camera target + bump version 0.26.2

react-components/src/components/Reveal3DResources/Reveal3DResources.tsx
https://cognitedata.atlassian.net/browse/BND3D-3643
Linked into fusion
- Link into Fusion
- Check that camera automatically zooms out to cover the scene initially
=> fix: camera not initially focusing scene

viewer/packages/360-images/visual-tests/Image360.VisualTest.ts, viewer/packages/api/src/api-helpers/Image360ApiHelper.ts, viewer/packages/camera-manager/src/StationaryCameraManager.ts, viewer/packages/tools/src/Overlay3D/Overlay3DTool.ts, viewer/packages/utilities/index.ts, viewer/packages/utilities/src/worldToViewport.ts
This is just a tiny cleanup in the code. It removes some repetitive coding around
=> Refacoring usage of getNormalizedPixelCoordinates

react-components/package.json
=> chore(react-components): bump version to 0.26.5

react-components/src/components/CadModelContainer/CadModelContainer.tsx, react-components/src/hooks/useCalculateModelsStyling.tsx, react-components/src/utilities/isSameModel.ts
Sometimes asset mapping styling would disappear for unknown reasons. This PR fixes it.
Linked into FDX locally.
To reproduce the error:
- Go to FDX in production
- Go to the 3D scene in lervik-industries
- Click an asset
- Click "Open" in the preview card
- Click back in the browser after the instance page has loaded
- The 3D scene should now lack styling for classic asset mappings
The issue should be fixed when repeating these steps with a local version linked to a build of this PR
=> fix(react-components): make sure asset-mapping styling does not disappear

react-components/package.json
Publish fix for asset-mapping styling disappearance
=> chore(react-components): bump reveal-react-components version 0.26.6

react-components/yarn.lock
Bump - recreation of dependabot PR: https://github.com/cognitedata/reveal/pull/4069
=> chore(react-components): bump follow-redirects

react-components/package.json, react-components/src/hooks/useSkyboxFromScene.tsx
https://cognitedata.atlassian.net/browse/BND3D-3673
Make sure skybox is not clipped by far-plane.
Also, make sure sky box position is always updated before render.
Linked into Fusion
=> fix(react-components): adjust far plane sky box and bump version 0.26.7

viewer/package.json
=> chore: bump version 4.9.0

react-components/package.json
Bump version of react-components, including recent fix to 360 image loading
=> chore(react-components): bump version 0.26.8

react-components/package.json
Bumped `react-components` version to 0.27.0
=> chore(react-components): bump react-component version to 0.27.0

react-components/package.json
=> chore(react-components): bump to version 0.28.0

react-components/package.json, react-components/src/hooks/use3dRelatedEdgeConnections.ts, react-components/src/utilities/types.ts
Fix a screw-up in the type definition of FdmIdWithView from a recent PR.
=> fix(react-components): correct FdmiIdWithView type and bump version 0.28.1

react-components/src/hooks/use3dRelatedEdgeConnections.ts
Avoid 400 from doing inspect with an empty request array
- Link into Fusion
- Go to 3D view in FDX in lervik-industries
- Click WorkOrder tab
- Click around the WorkOrder
- Some of them will trigger an inspect with no items causing a 400 and an error message in the console
- No more
=> fix(react-components): don't inspect with empty array

react-components/package.json
Bump version, fix inspection-endpoint bug
=> chore(react-components): bump to 0.28.2

viewer/packages/360-images/src/annotation/ImageAnnotationObject.ts, viewer/packages/360-images/unit-tests/Image360RevisionEntity.test.ts
Fixes https://cognitedata.slack.com/archives/C8A0QGMLN/p1706780515887639 - it was caused by an unchecked annotation (presumably "diagram.assetLink") being shown, although not counted among assets in the search panel. We now disable this annotation in 360 images altogether.
In examples - just making sure all previously available annotations are still there.
=> fix: don't show anything but image asset link and object detection in 360

viewer/package.json
=> chore: bump version 4.9.2

react-components/package.json
=> chore(react-components): bump reveal-react-components to version 0.29.0

viewer/api-entry-points/core.ts, viewer/packages/camera-manager/index.ts, viewer/packages/camera-manager/src/Flexible/DampedSpherical.ts, viewer/packages/camera-manager/src/Flexible/FlexibleCameraManager.ts, viewer/packages/camera-manager/src/Flexible/FlexibleControls.ts, viewer/packages/camera-manager/src/Flexible/FlexibleControlsEvent.ts, viewer/packages/camera-manager/src/Flexible/IFlexibleCameraManager.ts, viewer/reveal.api.md
In `IFlexibleCameraManager `
* Removed the options getter. 
* Add setter and getter for `controlsType`. 
In `FlexibleControls`:
* Removed the `_rawCameraRotation`. I didn't understand what it was good for, but do this now. This was original from the `ComboControls `and was a hack to set the camera direction programmatically. After I made the `setPositionAndRotation`, this hack is no longer need. The reason for I did this is that the camera vector wasn't updated when setting the rotation. I used quite long time for finding a solution on this. To test this use the Axis tool in various direction.
* Let Shift + Mouse drag be zoom and Ctrl +Mouse drag be pan
* Some renaming and refactoring on my way
In `FlexibleCameraManager`:
* Add event listeners for …
=> Add events and fix some geometrical issues in the FlexibleControls

examples/src/utils/NodeTransformUI.ts
Don't add transform control in examples until absolutely necessary.
=> chore: don't create transform control on click

react-components/package.json
Bump react components version to 0.29.1
=> chore(react-components): bump reveal react-components to version 0.29.1

viewer/package.json
=> chore: bump Reveal version 4.10.0

react-components/src/components/RevealToolbar/RevealToolbar.tsx, react-components/src/components/RevealTopbar/RevealTopbar.tsx, react-components/src/index.ts, react-components/stories/Topbar.stories.tsx, react-components/stories/utilities/RevealStoryContainer.tsx
Initial sketch of top bar. Improvements and button versions that support it better are soon to come, but this allows for testing in by others.
Storybook
=> feat(react-components): initial top bar

react-components/package.json
=> chore(react-components): bump 0.31.2

react-components/package.json
=> chore(react-components): bump version 0.32.0

viewer/package.json
=> chore: bump version 4.10.1

viewer/package.json
=> chore: bump version 4.10.2

react-components/src/components/RevealToolbar/ResetCameraButton.tsx, react-components/src/components/RuleBasedOutputs/hooks/useFetchRuleInstances.tsx, react-components/src/hooks/use3dRelatedDirectConnections.ts, react-components/src/hooks/use3dRelatedEdgeConnections.ts, react-components/src/hooks/useGroundPlaneFromScene.tsx, react-components/src/hooks/useReveal3dResourcesFromScene.ts, react-components/src/hooks/useSceneConfig.ts, react-components/src/hooks/useSceneDefaultCamera.tsx, react-components/src/utilities/fdmViewsExist.ts
There was a bug where the scene could temporarily be undefined, which in the Search code would manifest itself as an error about not finding the scene `''`. This improves the typing, so that we don't need to send in an empty string in cases where the scene space and external ID is unknown.
Includes a few more cleanups too.
=> fix: scene console log error

react-components/package.json
=> chore(react-components): bump 0.33.1

react-components/yarn.lock
In an attempt at updating ip (redoing the upgrade attempted here: https://github.com/cognitedata/reveal/pull/4227, since `dependabot` does not have access to build Reveal), I found the simplest way to be to run `yarn dedupe` and deduplicate dependencies. On the bright side, it means the yarn lock is a bit smaller now.
=> chore(react-components): dedupe yarn lock, upgrade package ip

viewer/package.json
=> chore: bump 4.10.3

react-components/src/components/RuleBasedOutputs/RuleBasedOutputsSelector.tsx
Fix an error where color overlay gives you headache if there's a point cloud in the scene
In Fusion
=> fix(react-components):  color overlay crashes when pointcloud in scene

viewer/packages/api/src/public/migration/Cognite3DViewer.ts
Count find the Jira tsk for it.
=> Fixed bug when picking on a model in click and double click.

react-components/src/components/NodeCacheProvider/AssetMappingCache.ts, react-components/src/components/NodeCacheProvider/types.ts, react-components/src/components/Reveal3DResources/Reveal3DResources.tsx, react-components/src/hooks/useCalculateModelsStyling.tsx, react-components/src/utilities/StylingGroupUtils.ts
This fixes two issues - one is that highlighting of CAD nodes through asset reference was not working (9add3db0802383fe6568c0a1e142013daebb3934) and the second that we did not return all related nodes when searching in a CAD model with an asset ID (0bd6d3d1b094fa222224280a7138ee1c1d97c8af).
In Fusion
=> fix(react-components): fix cad asset styling

react-components/yarn.lock, viewer/packages/camera-manager/src/Flexible/FlexibleCameraManager.ts, viewer/packages/camera-manager/src/Flexible/FlexibleControls.ts, viewer/packages/tools/src/Measurement/MeasurementTool.ts
Added a isEnableClickAndDoubleClick in the FlexibleCameraManager and used it in the Measurement  tool
=> fix: problems with clicking in Measurement tool enables viewer click

react-components/package.json
=> chore(react-components): bump 0.34.0

react-components/.eslintrc.cjs, react-components/stories/HighlightNode.stories.tsx, react-components/stories/Reveal3DResources.stories.tsx
Enable rule to disallow `console.log()` in react-components. `console.warn` and `console.error` are still allowed
=> chore(react-components): enable no-console lint rule

viewer/package.json
=> chore: bump 4.10.4

RELEASING.md
Update release template to account for our new beta/experimental conventions
=> chore: add experimental section to release template

react-components/package.json
=> chore(react-components): bump 0.36.1

react-components/src/hooks/useSearchMappedEquipmentAssetMappings.tsx, react-components/stories/SearchHooks.stories.tsx
https://cognitedata.atlassian.net/browse/BND3D-3907
Asset search hook had limitation of populating only 100 when no search query was passed which limited the number of data to 100 even though model contains more, this PR fixes the limitation.
In storybook and FDX
=> fix(react-components): asset search hook to use basic search based on name and description

react-components/package.json
Bumping `react-components` version to 0.36.2
=> chore(react-components): bump react-components version 0.36.2

viewer/packages/camera-manager/src/Flexible/FlexibleControls.ts, viewer/packages/camera-manager/src/Flexible/FlexibleControlsOptions.ts
This fix  make it possible to use the touch on the Flexible Camera Manager
=> fix: touch on the flexible camera manager

viewer/package.json
=> chore: bump version 4.10.6

viewer/packages/pointclouds/src/PointCloudPickingHandler.ts, viewer/packages/tools/src/HtmlOverlay/HtmlOverlayTool.ts, viewer/packages/tools/src/Measurement/MeasurementLine.ts, viewer/packages/utilities/index.ts, viewer/packages/utilities/src/customObject/CustomObjectIntersectInput.ts, viewer/packages/utilities/src/three/isPointVisibleByPlanes.ts
Make a newfunction: isPointVisibleByPlanes in utilities and remove the 4 implementations
=> (refactor) Remove 4 different implementations of the same function

viewer/package.json
=> chore: bump version to 4.10.7

viewer/packages/utilities/src/customObject/CustomObjectIntersection.ts, viewer/reveal.api.md
=> (feat) Add customObject to CustomObjectIntersection

react-components/package.json
Bump `react-components` to version 0.36.0
=> chore(react-components): bump react-components version to 0.36.3

react-components/src/hooks/useClickedNode.tsx
=> bug(react-components): Stop other than left mouse click in selection

viewer/packages/camera-manager/src/ComboControls.ts, viewer/packages/camera-manager/src/Flexible/FlexibleCameraManager.ts, viewer/packages/camera-manager/src/Flexible/FlexibleControls.ts, viewer/packages/camera-manager/src/utils/getWheelDelta.ts
No Jira ticket. This was a tip from Henrik, that we should have a max value of the scroll wheel, since the max accelerates the wheel when used multiple times.
A also move the function out and reused it
=> fix: Move getWheelDelta to utils and add a maximum wheel delta to 120

react-components/package.json
=> chore(react-components): bump 0.37.0

react-components/README.MD, viewer/README.md, viewer/packages/camera-manager/tests/ComboControls.test.ts
No JIRA ticket
This PR fixes some typos/white space in READMEs. One test is also simplified.
I ran `yarn test` in the `viewer` package. Unfortunately, it did not work running `yarn test` in `/reveal/viewer/packages/camera-manager`.
See ☝️ 
Not relevant 👇
=> chore: Fix some typos and simplify test

react-components/package.json, react-components/src/components/RevealToolbar/SlicerButton.tsx
Fix a bug where the model would be permanently cut to "most-geometry"-boundingbox, even when slicing handles were returned to the top/bottom.
=> fix(react-components): fix slicing boundaries

react-components/package.json, react-components/src/components/RevealToolbar/SlicerButton.tsx, react-components/src/components/RevealToolbar/hooks/useUrlStateParam.tsx
Fix issue where slicing state values would be read out from the URL in the wrong order
=> fix(react-components): fix slicing URL storage and bump to version 0.38.2

react-components/package.json, react-components/src/components/Reveal3DResources/types.ts, react-components/src/hooks/network/getCadModelsForAsset.ts, react-components/src/hooks/network/getCadModelsForFdmInstance.ts, react-components/src/hooks/network/getImage360CollectionsForAsset.ts, react-components/src/hooks/network/getPointCloudModelsForAsset.ts, react-components/src/index.ts, react-components/src/query/useModelsForInstanceQuery.ts, react-components/src/utilities/types.ts
Exposes a hook that finds all models related to an instance (asset or FDM)
Asset -> Cad has been tested in FDM. The other combinations lack testing. Will get around to it when the most urgent requirement from the other FDX team  is solved.
=> feat(react-components): models for instance query hook and bump react-components 0.39.0

viewer/package.json
=> chore: bump version 4.10.8

react-components/package.json
Bumped `react-components` version to 0.40.1
=> chore(react-components): bump react-components version to 0.40.1

react-components/src/components/RuleBasedOutputs/utils.ts, react-components/src/components/ViewerAnchor/ViewerAnchor.tsx
A recent change removed the support for mixed-case metadata keys in rule-based color expressions. This re-adds support.
Linking into Search/fusion - older rules now work again
=> fix(react-components): allow mixed case rule metadata key

viewer/package.json
=> chore: bump Reveal to version 4.11.1

react-components/src/components/RuleBasedOutputs/hooks/useDeleteRuleInstance.tsx
It fixes rule based thresholds deletion. Before it was relying on the rule id but the correct should be requesting the deletion through the externalId, which is unique.
=> fix(react-components): rule based thresholds using fdmnode and externalId for deletion

react-components/src/components/RevealContext/RevealContext.tsx, react-components/src/components/RevealKeepAlive/RevealKeepAlive.tsx, react-components/src/components/RevealKeepAlive/RevealKeepAliveContext.ts, react-components/src/components/SceneContainer/LoadedSceneContext.tsx, react-components/src/components/SceneContainer/SceneContainer.tsx, react-components/src/components/SceneContainer/SceneTypes.ts, react-components/src/hooks/useSceneDefaultCamera.tsx, react-components/src/index.ts, react-components/stories/utilities/RevealStoryContainer.tsx, react-components/tests/unit-tests/components/RevealContainer.test.tsx
https://cognitedata.atlassian.net/browse/BND3D-4087
In `Search` when switched between `List view` & `3D view` camera position were not maintained and was restoring to default scene camera position & rotation, this PR fixes the issue
In `Search`
- `yalc` link `react-component` to `fusion`
- Load `Search` and `Browse to 3D` page
- Switch between different `scenes`, camera should be positioned to `Scene's default camera position & rotation`
- Select `List view` & back to `3D view`, camera position & rotation should be maintained as previous.
=> fix(react-components): maintain camera position & rotation when switched between pages

react-components/package.json
=> chore(react-components): bump react-components to 0.41.1

viewer/packages/api/src/api-helpers/Image360ApiHelper.ts, viewer/packages/api/src/public/migration/Cognite3DViewer.ts, viewer/packages/api/src/public/types.ts, viewer/reveal.api.md
Member function that returns the currently entered 360 image, complete with revision and collection
=> feat: member function to get currently entered 360 image

react-components/src/hooks/useIsDraggingOnViewer.ts, react-components/src/index.ts
Add hook for telling whether the mouse is currently being clicked+dragged from inside the viewer or not.
Tested with https://github.com/cognitedata/fusion/pull/6072
=> feat(react-components): introduce useIsDraggingOnViewer

react-components/package.json
=> chore(react-components): bump 0.42.0

react-components/yarn.lock
Make bumps from #4372 and #4354, since dependabot is not allowed to run CI itself
=> chore(react-components): make dependabot bumps

react-components/package.json
Bump `react-components` to `v0.42.1`
=> chore(react-components): bump react-components to version 0.42.1

react-components/package.json, react-components/src/components/RevealCanvas/RevealCanvas.tsx, react-components/src/components/RevealCanvas/hooks/useDisableBodyTextSelectionOnViewerDragging.ts, react-components/src/hooks/useIsDraggingOnViewer.ts
"Fix" a bug where dragging in 3D would select text that happened to fall under the cursor
=> fix(react-components): don't select any text while dragging in 3D

viewer/package.json
Bump `reveal` version to `4.12.1`
=> chore: bump reveal to v4.12.1

react-components/package.json, react-components/yarn.lock
Bump version to `0.42.3` and reveal version in react-components to `v4.12.1`
=> chore(react-components): bump react-component to v0.42.3 and reveal to v4.12.1

react-components/package.json
Bump '`react-components` to `v0.42.4`
=> chore(react-components): bump react-component version to v0.42.4

react-components/src/components/RevealContext/RevealContext.tsx, react-components/src/components/RevealToolbar/LayersContainer/useModelHandlers.tsx
Model name in layers menu was disappearing when deselecting/vice versa.
Models was set to invisible when mouse clicked in 3D.
In previous PR, `LoadedSceneProvider` was removed causing an error when `SceneContainer` is used
This PR fixes the above issues.
In Storybook and Search (fusion)
- Load `LayerContainer` storybook example
- Select `Layers` button and deselect any model and check for name is maintained in the menu
=> fix(react-components): model-name disappearing from menu when model is deselected

react-components/package.json
Bump `react-components` to `v0.42.5`
=> chore(react-components): bump react-component to v0.42.5

renovate.json, viewer/Cargo.lock
2. attempt at getting the config to work how we want...
=> fix: attempt to fix renovate config

viewer/packages/api/src/public/migration/Cognite3DViewer.ts, viewer/packages/data-source/src/LocalDataSource.ts
Allow the `addModel` method to work on local models
=> fix: allow model type inference for local models

viewer/package.json
=> chore: bump 4.13.0

viewer/package.json
=> chore: bump 4.13.1

examples/webpack.config.js
=> chore: change examples port to 3549

.github/workflows/ci.yml
=> fix: cargo update should be scoped to workspace

documentation/docs/utils/LoginManager.ts, documentation/versioned_docs/version-3.x/utils/LoginManager.ts, documentation/versioned_docs/version-4.x/utils/LoginManager.ts, examples/src/utils/example-helpers.ts, examples/yarn.lock
Missed migration commits for the msal-browser major update
=> chore: perform azure/msal-browser v2-v3 migration

documentation/package.json, documentation/yarn.lock
Looking at #4447, it seems like `query-string` is no longer used in the documentation. Removing it as a dependency.
=> chore: remove documentation dependency query-string

examples/package.json, examples/yarn.lock
Remove unused deps from /examples
=> fix: remove some unused deps

react-components/package.json, react-components/yarn.lock, viewer/packages/tools/src/AxisView/AxisViewTool.ts
Bump styled components to fix type issue.
=> fix: bump styled components to fix type issue

viewer/package.json
=> chore: bump reveal to v. 4.14.1

react-components/package.json
Bump `react-components `version to `0.43.0`
=> chore(react-components): bump react-components to v0.43.0

react-components/package.json
Bump reveal-react-components to version 0.44.0
=> chore(react-components): bump react-components to v0.44.0

react-components/package.json
Bump `react-components` to `v0.44.1`
=> chore(react-components): bump react-components to v0.44.1

examples/src/utils/PointCloudUi.ts, viewer/packages/pointclouds/src/PointCloudPickingHandler.ts
https://cognitedata.atlassian.net/browse/BND3D-4248
Picking of invisible point cloud nodes would return intersection value but for cad nodes intersection of invisible node is not consider for picking. This PR fixes the issue to match Cad behavior.
In `examples` and `Search`
- `yarn build` in `viewer` folder.
- `yarn && yarn start` in `examples`.
- Load `modelId=3218004639791347 & revisionId=2722242967685530`.
- Click on any points and check developer console logging for intersection data, values of intersection point, model type and other details are printed.
- Select `Point clouds` in GUI and deselect `visible` option, model will not be visible, now click on same position as previous and check developer console, no logging of intersection data should be printed. In master you would still …
=> fix: enable picking on visible nodes for point cloud models

react-components/package.json
=> chore(react-components): bump 0.44.2

react-components/src/components/CacheProvider/utils.ts, react-components/src/query/useSearchAssetsMapped360Annotations.tsx, react-components/src/utilities/is360ImageAnnotation.ts
https://cognitedata.atlassian.net/browse/BND3D-4252
360 Image annotation search hook would return all annotations mapped to the site-id, annotations with out `region` property in `AnnotationData` would also be return which is incorrect as we only support 360 annotation with `region`, this PR fixes the issue
In `Search` with `omv-dev` project
- In `react-components` folder, run `yarn build && yalc publish`.
- In `fusion` folder, run `yalc add @cognite/reveal-react-components && yarn && nx serve flexible-data-explorer`.
- Load `Search` with `omv-dev` project and navigation to 3D page.
- Select `Maui Production Station` site and expand asset search panel, de-select all 3D resources expect for `90b6c57e-48dc-4cf7-8a86-0f5d5bde8a62-io-1` 360 image resource.
- No data is listed in the `Asset …
=> fix(react-components): 360 image annotation search hook data incorrect

react-components/package.json, react-components/src/utilities/isSameModel.ts
Fix a bug where models would be removed if transform was not set (?)
=> fix(react-components): make sure model matrices are compared properly before removal and bump to react-components 0.44.4

react-components/package.json, react-components/src/components/RevealContext/RevealContext.tsx
Expose the `onLoading` argument for usage in react-components
=> feat(react-components): onLoading argument in RevealContext and bump to version 0.45.0

react-components/package.json, react-components/src/hooks/useCalculateModelsStyling.tsx, react-components/src/hooks/useCalculatePointCloudModelsStyling.tsx
Fixes a bug where we would temporarily remove a model with no styling.
=> fix(react-components): don't remove models with no styling and bump to 0.45.1

viewer/yarn.lock
Bumps ip package to get rid of CVE https://github.com/cognitedata/reveal/security/dependabot/355.
=> chore: patch ip to v2.0.1

react-components/package.json, react-components/src/components/RevealContext/RevealContext.tsx, react-components/stories/Architecture.stories.tsx, react-components/stories/Toolbar.stories.tsx, react-components/stories/Topbar.stories.tsx
=> fix(react-components): always use flexcam to avoid crash

react-components/src/components/RuleBasedOutputs/components/RuleBasedSelectionItem.tsx
Just a designer request: let the whole rule base item be clickable and not only the radio button
- Open the Rule Base Dropdown list in Search UI
- Select any rule not only from the radio button but also from the whole rule item space
- Observe the rule being selected
=> let the whole rule base item be clickable

react-components/package.json, react-components/yarn.lock
=> chore(react-components): bump react components to v0.47.1

react-components/package.json
=> chore(react-components): bump to version 0.48.0

react-components/src/architecture/base/commands/BaseTool.ts, react-components/src/architecture/base/renderTarget/BaseRevealConfig.ts, react-components/src/architecture/base/renderTarget/RevealRenderTarget.ts, react-components/src/architecture/concrete/config/StoryBookConfig.ts, react-components/stories/Architecture.stories.tsx
Needed this for the storybook, to fix the view when startup. This concept should be integrated closer with the app later. Now it is just used in the story book.
=> react-components (feat) Attemt on making a configurative startUp function

viewer/package.json
=> chore: bump Reveal to v4.14.6

react-components/src/query/useSearchMappedEquipmentFDM.tsx, react-components/src/utilities/FdmSDK.ts
https://cognitedata.atlassian.net/browse/UX-2706
Fixes two issues:
- The FDM `search` call would sometimes get an empty filter, causing it to fail
- After doing the search and filter queries, we figure out if the node is connected to any of the relevant models, by doing one request _per_ equipment to find its connected models. Now we fetch all possibly relevant models up-front and compare with the id
=> fix(react-components): fix FDM search issues

react-components/package.json
=> chore(react-components): bump to version 0.50.0

viewer/package.json
=> chore: bump reveal to version 4.14.8

viewer/packages/data-providers/src/pointcloud-stylable-object-providers/cdfAnnotationsToObjects.ts
none
While looking around, noticed this seemingly dead code, since the matrix mutated is not used for anything
Hasn't but should be side effect free.
=> refactor: remove dead code

documentation/yarn.lock, examples/yarn.lock, react-components/yarn.lock, viewer/yarn.lock
=> chore: update transitive packages to fix CVEs

viewer/package.json
=> chore: bump version to 4.14.9

viewer/package.json
=> chore: bump reveal to version 4.15.0

react-components/package.json
=> chore(react-components): bump to version 0.51.0

react-components/src/architecture/base/utilities/geometry/Range3.ts, react-components/src/architecture/concrete/axis/AxisThreeView.ts
=> fix(react-components):  Fix reversed Y-axis problem

react-components/src/components/Architecture/CommandButton.tsx, react-components/src/components/Architecture/OptionButton.tsx
Fix annoying console errors related to tippy react key-issues.
I don't know why this fixes it, but it does.
Storybook
=> fix(react-components): fix toolbar tippy console error

react-components/package.json
bump react components to 0.52.2
=> chore(react-components): bump to version 0.52.2

viewer/package.json
=> chore: bump to 4.15.2

react-components/package.json, react-components/src/components/CacheProvider/NodeCacheProvider.tsx
Sometimes, clicking FDM nodes in the model would not result in any sort of coloring, because the query was initiated before all models were added to the scene. This makes sure that the query is re-initialized when the models present in the scene change.
=> fix(react-components): ensure edge connection fetching updates on model change and bump to version 0.54.2

documentation/docs/examples/controlsmodes.mdx, documentation/versioned_docs/version-4.x/examples/controlsmodes.mdx, viewer/api-entry-points/core.ts, viewer/package.json, viewer/packages/camera-manager/index.ts, viewer/packages/camera-manager/src/DefaultCameraManager.ts, viewer/reveal.api.md
=> feat: add type guard for DefaultCameraManager and bump to 4.16.0

react-components/src/components/CacheProvider/AssetMappingAndNode3DCache.ts
=> chore(react-components): send 1000 assets assetmappings

react-components/package.json
Bump react-components to `v0.55.3`
=> chore(react-components): bump react-components to v0.55.3

react-components/package.json
Bump `react-components` to `v0.55.5`
=> chore(react-components): bump react-components to v0.55.5

react-components/src/architecture/concrete/measurements/getIconByPrimitiveType.ts, react-components/src/common/i18n/en/reveal-react-components.json
=> fix(react-components): Added 3 more strings

react-components/package.json
Bump `react-components` to `v0.55.6`
=> chore(react-components): bump react-components to v0.55.6

viewer/packages/camera-manager/src/Flexible/moveCamera.ts
Missed a spot when integrating the TWEEN JS 0.25.0 upgrade (https://github.com/cognitedata/reveal/pull/4692)
=> fix: make sure TWEEN in flexible camera manager works as expected

react-components/package.json
Bump react-components to v0.55.9
=> bump react-components to 0.55.9

viewer/package.json
=> chore: bump reveal to 4.17.0

react-components/src/data-providers/core-dm-provider/getDMSRevision.ts, react-components/src/data-providers/core-dm-provider/revisionQuery.ts
It's not always there for the moment, apparently
There are some inconsistencies in how revisions are stored, so we should not rely on the revisionId to be present, for now
=> fix(react-components): don't rely on revisionId in CogniteCADRevision

react-components/package.json
=> chore(react-components): bump to 0.58.0

react-components/src/data-providers/core-dm-provider/CoreDm3dDataProvider.ts, react-components/src/data-providers/core-dm-provider/getFdmConnectionsForNodes.ts
Fixes a bug where clicking CDM-contextualized objects wouldn't work before "show contextualized" was clicked.
=> fix(react-components): make cdm-clicks work before "show contextualized" is clicked

react-components/package.json
=> chore(react-components): bump to 0.58.1

react-components/src/data-providers/core-dm-provider/getCadConnectionsForRevisions.ts
Don't send request with no model/revisions in the CAD connections query
=> fix(react-components): don't send CAD connections request without items

react-components/package.json
https://cognitedata.atlassian.net/browse/BND3D-4564
=> chore(react-components): bump to version 0.58.2

react-components/src/architecture/base/concreteCommands/UndoCommand.ts, react-components/src/architecture/base/utilities/extensions/stringExtensions.ts
1. Fix a small bug in compare equalsIgnoreCaseAndSpace
2. Use correct undo icon
=> fix(react-components): Fix a small bug in compare equalsIgnoreCaseAndSpace and use correct undo icon

react-components/package.json
Bumped `react-components` to `v0.59.1`
=> chore(react-components): bump react-components version to 0.59.1

react-components/package.json
Bumped `react-components` to `v0.59.2`
=> chore(react-components): bump react-components to 0.59.2

documentation/yarn.lock, examples/yarn.lock, react-components/yarn.lock, viewer/yarn.lock
Fixed several High security issues raised in [Dependabot](https://github.com/cognitedata/reveal/security/dependabot) alerts
=> chore: fixed security vulnerable issue in dependbots

documentation/yarn.lock, react-components/yarn.lock, viewer/yarn.lock
=> chore: fixed axios security dependbots alerts

viewer/package.json
Bumped `reveal` version to `4.18.0`
=> chore: bump reveal version to 4.18.0

react-components/src/architecture/base/commands/BaseCommand.ts, react-components/src/architecture/base/commands/mocks/MockActionCommand.ts, react-components/src/architecture/base/concreteCommands/SetFlexibleControlsTypeCommand.ts, react-components/src/architecture/base/concreteCommands/UndoCommand.ts, react-components/src/architecture/base/renderTarget/CommandsController.ts, react-components/src/architecture/concrete/pointsOfInterest/DeletePointsOfInterestCommand.ts, react-components/src/components/Architecture/CommandButton.tsx, react-components/src/components/Architecture/DropdownButton.tsx, react-components/src/components/Architecture/FilterButton.tsx, react-components/src/components/Architecture/FilterItem.tsx, react-components/src/components/Architecture/SegmentedButtons.tsx, react-components/src/components/Architecture/SettingsButton.tsx
Updating vas not correct in the menu components. I use the same pattern as for the other command component.
This pattern in marked in the code as `@update-ui-component-pattern`
So the updating of the toggle (for instance Show 360 images)  in the menu should be done when changing it  other places in the UI.
Other things on this PR:
* Little refactoring regarding the short cut buttons.
* Marked `@update-ui-component-pattern` in the code to recognize the same pattern. Good for bug fixing.
I tested it by creating some Mocks. Simulated that the toggle can be turn off several places. On in the settings button. Another in the toolbar. This is now working both ways.
=> fix(react-components): Fixing updating of commands using the achitecture

react-components/src/architecture/base/commands/mocks/MockFilterCommand.ts, react-components/src/architecture/concrete/config/StoryBookConfig.ts, react-components/src/components/Architecture/FilterButton.tsx
Test it by this:
Before it looked like this:
=> fix(react-components): Fix layout of filter drop down menu

react-components/package.json
It includes fixes and changes to support the improvements and fixes for the time series searching UI in the 3D Management - Rule Builder
=> fix(react-components): bump version to 0.61.1

viewer/package.json, viewer/packages/360-images/src/Image360History.ts
Adding a small fix n Image360History
=> Update version to 4.20.0

react-components/package.json, react-components/src/architecture/base/concreteCommands/NavigationTool.ts, react-components/src/architecture/base/concreteCommands/image360Collection/Image360ActionCommand.ts, react-components/src/components/Architecture/RevealButtons.tsx, react-components/yarn.lock
Just minor fixes to update the buttons properly. 
I also implement the Escape on my side, since I need to update the buttons when exit out.
On Fusion
=> fix(react-components): Fixing bugs in 3D image navigation + Upgrade Reveal and React-component to new version

react-components/src/higher-order-components/withSuppressRevealEvents.tsx
Fixes a bug where e.g. Input fields in the UI would not be writable
=> fix(react-components): don't block input in UI

react-components/package.json, react-components/src/components/CadModelContainer/CadModelContainer.tsx, react-components/src/components/Image360CollectionContainer/Image360CollectionContainer.tsx, react-components/src/components/PointCloudContainer/PointCloudContainer.tsx, react-components/src/components/Reveal3DResources/Reveal3DResourcesInfoContext.tsx, react-components/src/components/Reveal3DResources/index.ts
Add new hook to let user know whether all resources that are expected to load, are loaded
In Fusion (also with failing models)
=> feat(react-components): add resources-expected-in-viewer hook and bump to 0.65.0

viewer/package.json, viewer/packages/360-images/src/Image360Facade.ts, viewer/packages/360-images/src/types.ts, viewer/packages/360-images/visual-tests/Image360.VisualTest.ts, viewer/packages/api/src/api-helpers/Image360ApiHelper.ts, viewer/packages/api/src/public/migration/Cognite3DViewer.ts, viewer/packages/api/src/public/migration/types.ts, viewer/reveal.api.md
=> feat(experimental): Add Image360Intersection to AnyIntersection result and bump to 4.21.0

documentation/yarn.lock, react-components/yarn.lock, viewer/yarn.lock
=> chore: depends alert vulnerable fix till November 7th 2024

react-components/package.json, react-components/src/components/Image360Details/Image360Details.tsx
This reverts commit 5f2de74f16b430f9e76bcdd6070c55922ce8f744.
The replacing UI is still not in GA.
=> fix(react-components): Revert "Update Image360Details.tsx (#4840)" and bump to 0.65.5

react-components/package.json, react-components/src/architecture/concrete/pointsOfInterest/color.ts, react-components/src/components/Architecture/pointsOfInterest/PoiList.tsx
Give Points of Interest a color that's more in-your-face. (Also, it's according to design https://www.figma.com/design/qox0T1E6FznaWClK3oxi2s/3D-Q2-%E2%80%93-Q3-2024?node-id=1759-76326&node-type=frame&t=bfTxk02OOzkl8D1O-0)
=> chore(react-components): update PoI color to be more scream-ish, bump 0.67.2

react-components/src/common/i18n/en/reveal-react-components.json
=> chore(react-components): add missing translation

react-components/src/architecture/concrete/pointsOfInterest/ads/PointsOfInterestAdsProvider.ts
Show name properly besides PoI comments
=> fix(react-components): Show proper names on PoI comments

viewer/package.json, viewer/packages/api/src/public/migration/Cognite3DViewer.ts
=> fix: use proper click event position translation and bump to 4.21.3

react-components/src/architecture/concrete/pointsOfInterest/ads/PointsOfInterestAdsProvider.ts, react-components/src/components/Architecture/pointsOfInterest/PoiList.tsx, react-components/src/components/Architecture/pointsOfInterest/index.ts, react-components/src/components/Architecture/pointsOfInterest/useFilterPointsOfInterest.ts, react-components/src/components/Architecture/pointsOfInterest/usePointsOfInterest.ts
Features to support pagination (show-more) and query filtering in the Points-of-Interest-list.
Also fixes a small bug in PoI-comment querying
=> feat(react-components): enable searching in PoIs

react-components/package.json
=> chore(react-components): bump 0.70.0

react-components/package.json, react-components/src/components/Architecture/pointsOfInterest/PoiInfoPanelContent.tsx, react-components/src/components/Architecture/pointsOfInterest/PoiList.tsx
=> fix(react-components): pois: disable row stripes and open comments and bump 0.70.1

react-components/package.json
=> chore(react-components): bump react-components to v0.71.0

react-components/src/components/Architecture/pointsOfInterest/PoiInfoPanelContent.tsx
=> fix(react-components): Move close button to side panel header

react-components/package.json
=> fix(react-components): Upgrade with correct version number

react-components/package.json, react-components/src/architecture/base/commands/CustomBaseInputCommand.ts, react-components/src/architecture/concrete/pointsOfInterest/CreatePointsOfInterestWithDescriptionCommand.ts, react-components/src/architecture/concrete/pointsOfInterest/ads/PointsOfInterestAdsProvider.ts, react-components/src/architecture/concrete/pointsOfInterest/ads/createUpsertRequestFromPois.ts, react-components/src/architecture/concrete/pointsOfInterest/models.ts, react-components/src/architecture/concrete/pointsOfInterest/types.ts, react-components/src/components/Architecture/CommandButtons.tsx, react-components/src/components/Architecture/CustomInputField.tsx, react-components/src/components/Architecture/pointsOfInterest/PoiInfoPanelContent.tsx, react-components/src/components/Architecture/pointsOfInterest/PoiList.tsx, react-components/src/components/Architecture/pointsOfInterest/useFilterPointsOfInterest.ts
Add the Name/Title field in the floating panel when creating a POI and persist it. 
For now using a custom based input command to support multiple fields in one single command.
It is also bumping react components to 0.73.1
1. Enable the POI creation
2. Click on a 3d geometry to create a POI
3. Observe the floating panel with Two fields: Title/Name and Description
4. Fill the two fields and press to Create
5. Observe the right side panel opening with the POI name on the header
[screen-capture (4).webm](https://github.com/user-attachments/assets/8cbb4be5-653e-4e1b-9d75-f957cebf825a)
=> born of the title field in floating panel when creating POIs and some other improvements - also bump react components to 0.73.1

react-components/src/architecture/base/commands/BaseTool.ts, react-components/src/architecture/base/renderTarget/ContextMenuController.ts, react-components/src/architecture/concrete/pointsOfInterest/CreatePointsOfInterestWithDescriptionCommand.ts, react-components/src/architecture/concrete/pointsOfInterest/InitiatePointsOfInterestCommand.ts, react-components/src/architecture/concrete/pointsOfInterest/PointsOfInterestTool.ts, react-components/src/architecture/concrete/pointsOfInterest/ads/PointsOfInterestAdsProvider.ts, react-components/src/architecture/concrete/pointsOfInterest/ads/createUpsertRequestFromPois.ts, react-components/src/architecture/concrete/pointsOfInterest/ads/types.ts, react-components/src/architecture/concrete/pointsOfInterest/models.ts, react-components/src/architecture/concrete/pointsOfInterest/types.ts, react-components/src/components/Architecture/RevealButtons.tsx, react-components/stories/Architecture.stories.tsx, react-components/stories/HighlightNode.stories.tsx
Upload asset reference in PoI when saving
In Fusion
=> feat(react-components): upload instance with PoI

react-components/src/architecture/concrete/pointsOfInterest/PointsOfInterestDomainObject.ts, react-components/src/architecture/concrete/pointsOfInterest/PointsOfInterestTool.ts, react-components/src/architecture/concrete/pointsOfInterest/ads/PointsOfInterestAdsProvider.ts, react-components/src/components/Reveal3DResources/instanceStyleTranslation.ts
Make instance light up when PoI is selected
=> feat(react-components): color associated POI instance on selection

react-components/package.json
=> chore(react-components): upgrade to 0.73.2

react-components/package.json, react-components/src/architecture/concrete/pointsOfInterest/ads/PointsOfInterestAdsProvider.ts, react-components/src/architecture/concrete/pointsOfInterest/ads/types.ts
=> fix(react-components): expect right scene format

react-components/package.json, react-components/src/architecture/base/commands/CustomBaseInputCommand.ts, react-components/src/architecture/concrete/pointsOfInterest/CreatePointsOfInterestWithDescriptionCommand.tsx, react-components/src/architecture/concrete/pointsOfInterest/PointsOfInterestTool.ts, react-components/src/architecture/concrete/pointsOfInterest/types.ts, react-components/src/components/Architecture/CustomInputField.tsx, react-components/src/components/Architecture/pointsOfInterest/PoiInfoSection.tsx, react-components/src/components/AssetLabel/index.ts, react-components/src/components/InstanceLabel/InstanceLabel.tsx, react-components/src/components/InstanceLabel/index.ts
Change the Custom based input command to support more field types in order to add instance reference in floating panel when creating a POI and some improvements in the instance label component
=> feat(react-components): add instance reference component in the floating panel when creating a POI and some other improvements

react-components/src/components/CadModelContainer/CadModelContainer.tsx, react-components/src/components/Image360CollectionContainer/Image360CollectionContainer.tsx, react-components/src/components/PointCloudContainer/PointCloudContainer.tsx, react-components/src/components/Reveal3DResources/Reveal3DResources.tsx, react-components/src/components/Reveal3DResources/Reveal3DResourcesInfoContext.tsx, react-components/src/components/Reveal3DResources/hooks/useCallCallbackOnFinishedLoading.ts, react-components/src/components/Reveal3DResources/hooks/useSetExpectedLoadCount.ts, react-components/src/components/Reveal3DResources/hooks/useTypedModels.ts, react-components/src/components/SceneContainer/SceneContainer.tsx
Linked into Fusion, seeing that the callback only calls once
=> fix(react-components): Ensure that SceneContainer only registers "all-loaded" once

react-components/package.json, react-components/src/components/RevealToolbar/ResetCameraButton.tsx, react-components/src/hooks/scenes/useSceneConfig.ts, react-components/src/hooks/useSceneDefaultCamera.tsx, react-components/stories/SceneContainer.stories.tsx
=> fix(react-components): fixed camera not setting to fit to model when no camera setting in scene configuration

react-components/package.json, react-components/src/components/RevealToolbar/HelpButton.tsx
Looks like this now: 
In Fusion
=> fix(react-components): Restrict max width of help panel and bump to 0.73.8

viewer/packages/pointclouds/src/potree-three-loader/Potree.ts, viewer/packages/pointclouds/src/potree-three-loader/tree/IPointCloudTreeNodeBase.ts, viewer/packages/pointclouds/src/potree-three-loader/tree/PointCloudOctree.ts, viewer/packages/pointclouds/src/potree-three-loader/tree/PointCloudOctreeNode.ts
Removing unused code in the Potree pointcloud loading
=> chore: remove unused Potree code

react-components/package.json, react-components/src/components/Architecture/types.ts, react-components/src/components/RevealToolbar/Help/elements.ts, react-components/src/components/RevealToolbar/HelpButton.tsx
https://cognitedata.atlassian.net/browse/BND3D-4798
So, apparently there were already designs for this :expressionless: It now looks like this
=> fix(react-components): Change help panel again and bump to 0.73.9

react-components/package.json, react-components/src/hooks/scenes/use3dScenes.tsx
https://cognitedata.atlassian.net/browse/BND3D-4997
Assets are not listed in Search panel in 3D page for newly created scenes, this issue is result of use3dScenes hook not fetching all scene data. Current changes have made to ensure that all scene data is fetched for further process.
_The issue was reported by Celanese and Hess customer_
In Search in Celanese project
Issue reference
Fixed reference
=> fix(react-components): fetch all scene data in use3dScene hook

react-components/package.json, react-components/src/components/Architecture/CommandButton.tsx, react-components/src/components/Architecture/CustomInputField.tsx, react-components/src/components/Architecture/DropdownButton.tsx, react-components/src/components/Architecture/FilterButton.tsx, react-components/src/components/Architecture/SegmentedButtons.tsx, react-components/src/components/Architecture/SettingsButton.tsx, react-components/src/components/Architecture/TreeView/components/TreeViewLabel.tsx, react-components/src/components/Architecture/pointsOfInterest/PoiHeader.tsx, react-components/src/components/Architecture/pointsOfInterest/PoiSharePanel.tsx, react-components/src/components/Architecture/utilities.ts, react-components/src/components/CacheProvider/RevisionFdmNodeCache.ts, react-components/src/components/RevealToolbar/AssetContextualizedButton.tsx, react-components/src/components/RevealToolbar/FitModelsButton.tsx, react-components/src/components/RevealToolbar/HelpButton.tsx, react-components/src/components/RevealToolbar/LayersButton/LayersButton.tsx, react-components/src/components/RevealToolbar/ResetCameraButton.tsx, react-components/src/components/RevealToolbar/RuleBasedOutputsButton.tsx, react-components/src/components/RevealToolbar/SelectSceneButton.tsx, react-components/src/components/RevealToolbar/SettingsButton.tsx, react-components/src/components/RevealToolbar/ShareButton.tsx, react-components/src/components/RevealToolbar/SlicerButton.tsx, react-components/src/components/Widgets/WindowWidget.tsx, react-components/yarn.lock
When panels are appended to document body, they may inherit leaked styling from other parts of the app, as was the case in Fusion.
=> fix(react-components): don't append to document body

documentation/yarn.lock, examples/yarn.lock, react-components/yarn.lock, viewer/yarn.lock
=> chore: dependbot alert fixes

viewer/packages/360-images/src/collection/DefaultImage360Collection.ts, viewer/packages/360-images/src/collection/Image360Collection.ts, viewer/packages/data-providers/src/Image360ProviderCombiner.ts, viewer/packages/data-providers/src/image-360-data-providers/Cdf360ImageAnnotationProvider.ts, viewer/packages/data-providers/src/image-360-data-providers/CoreDm360ImageAnnotationProvider.ts, viewer/packages/data-providers/src/image-360-data-providers/Local360ImageProvider.ts, viewer/packages/data-providers/src/types.ts, viewer/reveal.api.md
This is definitely a verbose extension of the code, but I'm wondering if it's the right move. Would be happy to hear input on this!
=> feat: extend API to make use of source-flag in getAnnotationsInfo

viewer/package.json
=> chore: bump to version 4.23.0

react-components/src/data-providers/core-dm-provider/listMappedFdmNodes.ts, viewer/package.json, viewer/packages/data-providers/src/pointcloud-stylable-object-providers/pointcloud-volume-data-providers/CdfPointCloudDMStylableObjectProvider.test.ts, viewer/packages/data-providers/src/pointcloud-stylable-object-providers/pointcloud-volume-data-providers/getDMPointCloudObjects.ts
Fix an error sometimes disrupting point cloud loading
=> fix: correct point cloud volume <-> asset mapping

react-components/src/hooks/useActiveReveal3dResources.ts
`useAciveRevealResources` hook was not returning active image collection but all image collection, this PR corrects the issue
=> fix(react-components): active 360 image from useAciveRevealResources hook

react-components/package.json, react-components/src/components/Reveal3DResourcesList/Reveal3DResourcesList.tsx, react-components/src/components/Reveal3DResourcesList/index.ts, react-components/src/components/index.ts
Exposed missing export of `Reveal3DResourcesList` 😞
=> fix(react-components): missing export of Reveal3DResourcesList

react-components/package.json, react-components/src/query/useAll3dDirectConnectionsWithProperties.ts
https://cognitedata.atlassian.net/browse/BND3D-5255
=> fix(react-components): fix parallel execution with fdm in rule based coloring and bump version to 0.75.2

react-components/src/architecture/base/concreteCommands/KeyboardSpeedCommand.ts, react-components/src/common/i18n/en/reveal-react-components.json
=> fix(react-components): add translation key for "Set camera fly speed"

react-components/src/components/RevealCanvas/ViewerContext.tsx, react-components/src/components/RevealContext/RevealContext.tsx, react-components/src/query/usePointCloudModelRevisionIdsFromReveal.ts
Remove 2 more circular deps by restructuring and fixing imports
Current remaining list is now: 
```
1) architecture/base/domainObjects/DomainObject.ts > architecture/base/domainObjects/RootDomainObject.ts
2) architecture/concrete/primitives/line/LineDomainObject.ts > architecture/concrete/primitives/line/LineView.ts
3) architecture/concrete/annotations/AnnotationsDomainObject.ts > architecture/concrete/annotations/BoxGizmoDomainObject.ts
4) architecture/concrete/annotations/AnnotationsDomainObject.ts > architecture/concrete/annotations/CylinderGizmoDomainObject.ts
5) architecture/concrete/annotations/commands/AnnotationsCreateTool.ts > architecture/concrete/annotations/commands/AnnotationsSelectTool.ts
6) architecture/concrete/annotations/commands/AnnotationsCreateTool.ts > …
```
=> fix: remove more circular deps

react-components/src/architecture/base/views/ThreeViewFactory.ts
I think this is a good pattern for factories. So I wanted the code to be "perfect", so other people can use this is a starting point.
The change is the function getClassesOf. This hides away a loop that is reused 2 times.
It yield the class, so the super/base class, so the super-super/base-base class etc.
=> refactor(react-components): Make ThreeViewFactory a little bit better

react-components/.eslintrc.cjs, react-components/package.json, react-components/src/components/RevealCanvas/hooks/useCameraStateControl.test.ts, react-components/tests/tests-utilities/fixtures/cameraManager.ts, react-components/tests/tests-utilities/fixtures/image360.ts, react-components/tests/tests-utilities/fixtures/viewer.ts, react-components/vite.config.ts, react-components/yarn.lock
https://cognitedata.atlassian.net/browse/BND3D-5449
Bump vitest to 3.0.6, and fix breaking changes in types.
=> chore: update vitest to 3.0.6

react-components/src/advanced-tree-view/storybook-cad/cad-tree-view.stories.tsx, react-components/src/architecture/base/commands/factory/ToolbarFactory.test.ts, react-components/src/architecture/base/domainObjects/DomainObject.test.ts, react-components/src/architecture/base/domainObjects/DomainObject.ts, react-components/src/architecture/base/domainObjects/FolderDomainObject.test.ts, react-components/src/architecture/base/domainObjects/RootDomainObject.test.ts, react-components/src/architecture/base/domainObjects/VisualDomainObject.test.ts, react-components/src/architecture/base/reactUpdaters/CommandsUpdater.ts, react-components/src/architecture/base/views/ThreeViewFactory.test.ts, react-components/src/architecture/concrete/reveal/RevealModelsUtils.test.ts
This is unit test for the base classes.
I discovered one bug in `setActiveInteractive()`, but this was not in production. The other changes in the prod code are cosmetic only.
=> test(react-components): Add unit test for base/domainObjects

react-components/src/components/RevealToolbar/LayersButton/LayersButton.viewmodel.tsx, react-components/src/components/RevealToolbar/LayersButton/components/LayersButtonsStrip.test.tsx, react-components/src/components/RevealToolbar/LayersButton/components/LayersButtonsStrip.tsx, react-components/src/components/RevealToolbar/LayersButton/hooks/useModelHandlers.test.tsx, react-components/src/components/RevealToolbar/LayersButton/hooks/useModelHandlers.tsx, react-components/src/components/RevealToolbar/LayersButton/updateExternalStateFromLayerHandlers.test.ts, react-components/stories/Toolbar.stories.tsx, react-components/tests/tests-utilities/fixtures/cadModel.ts, react-components/tests/tests-utilities/fixtures/image360.ts, react-components/tests/tests-utilities/fixtures/modelHandler.ts, react-components/tests/tests-utilities/fixtures/pointCloud.ts
The test for `LayersButtonsStrip` failed when running `yarn test`, but not when running `yarn test:coverage`, so it never failed in CI. The test seems to succeed also when the suite is run on its own, but not when running all together, suggesting that the test is affected by e.g. modifications to the big shared mock objects. After a closer look, it seems to somehow be related to us not properly injecting/using the injected hooks in LayersButtonsStrip. This PR makes sure the component uses the injected hooks, AND that we actually inject them in the test. The test seems to be succeeding consistently now.
`yarn test` and `Toolbar` storybook
`yarn test` and `Toolbar` storybook
=> chore(react-components): Properly use injected hooks in LayersButtonsStrip

react-components/src/architecture/base/utilities/extensions/mathExtensions.test.ts, react-components/src/architecture/base/utilities/extensions/mathExtensions.ts
=> test(react-components): Add test for the mathExtensions

react-components/src/architecture/base/renderTarget/RevealRenderTarget.ts, react-components/src/architecture/base/utilities/extensions/vectorExtensions.test.ts, react-components/src/architecture/base/utilities/extensions/vectorExtensions.ts, react-components/src/architecture/base/utilities/geometry/getResizeCursor.test.ts, react-components/src/architecture/base/utilities/geometry/getResizeCursor.ts, react-components/src/architecture/concrete/primitives/box/BoxDragger.ts
`vectorExtensions `contains methods that is missing in `three.js` for Vector2/3.
* Make documentation for `vectorExtensions `
* Make unit test for `vectorExtensions `
* Renamed 2 methods in `vectorExtensions `
* Make documentation for `getResizeCursor`
* Make unit test for `getResizeCursor`
**Note:** No change in implementation is done
=> test(react-components): Make documentation and unit test for vectorExtensions and getResizeCursor and and change name of 2 methods.

react-components/package.json
Bumps the version. This will release the new circle+cylinder measurement tools (#4996) and modify other measurement tool tips (#5036)
=> chore(react-components): bump react-components version 0.76.0

.github/pull_request_template.md
Seems that I went a bit overboard with the PR template and added a redundant line
Removing it here
=> chore: remove redundant PR template line

codecov.yml
This PR adds flag configuration for Codecov to improve coverage calculations when changes are made specifically to the viewer or react-components folders. Instead of averaging the coverage of both folders, this update ensures that the percentage is calculated based only on the affected folder, leading to more accurate and relevant coverage reports.
https://github.com/cognitedata/reveal/pull/5056/checks?check_run_id=39352485891
codecov report should not decrease by -21% when actually increasing the coverage of the submodule
Following CodeCov Flag documentation: https://docs.codecov.com/docs/flags
=> chore: add flag management config

react-components/src/utilities/instanceIds/typeGuards.test.ts, react-components/src/utilities/instanceIds/typeGuards.ts, react-components/tests/tests-utilities/fixtures/assets.ts
add isObject3DIdentifier typeguard and add a unit test file for the typeGuard file
This PR comes along with the PRs: 
* #5057
* #5061 (**this PR**)
* #5058
* #5056
And is linked to the Fusion PRs:
https://github.com/cognitedata/fusion/pull/12311 (**main PR**)
It has already been tested via unit test and the payload function has already been tested in the final PR in several DM projects
=> fix(react-components): dms search returns incorrect results - step 3

viewer/package.json, viewer/packages/api/src/public/RevealManager.ts, viewer/packages/api/src/public/migration/Cognite3DViewer.test.ts, viewer/packages/api/src/public/migration/Cognite3DViewer.ts, viewer/packages/rendering/src/ResizeHandler.test.ts, viewer/packages/rendering/src/ResizeHandler.ts, viewer/reveal.api.md
Part of the work with https://cognitedata.atlassian.net/browse/BND3D-5504
Adds getters for resolution state in the viewer.
=> feat: add getters for resolution state

documentation/yarn.lock, examples/yarn.lock, react-components/yarn.lock, viewer/yarn.lock
Closes Dependabot [#540](https://github.com/cognitedata/reveal/security/dependabot/540), [#507](https://github.com/cognitedata/reveal/security/dependabot/507), [#517](https://github.com/cognitedata/reveal/security/dependabot/517) and [#533](https://github.com/cognitedata/reveal/security/dependabot/533)
=> chore: closes dependbot cve's

react-components/src/architecture/base/commands/BaseSliderCommand.ts, react-components/src/architecture/base/concreteCommands/SetQualitySliderCommand/SetQualitySliderCommand.test.ts, react-components/src/architecture/base/concreteCommands/SetQualitySliderCommand/SetQualitySliderCommand.ts, react-components/src/architecture/base/concreteCommands/SetQualitySliderCommand/fidelityLevels.test.ts, react-components/src/architecture/base/concreteCommands/SetQualitySliderCommand/fidelityLevels.ts, react-components/src/common/i18n/en/reveal-react-components.json, react-components/src/components/Architecture/SettingsButton.tsx, react-components/tests/tests-utilities/fixtures/renderTarget.ts
https://cognitedata.atlassian.net/browse/BND3D-5504
Create the quality slider component.
It is based on the Command concept, which is essentially just a Model in the MVVM pattern. Tests are also included.
Depends on https://github.com/cognitedata/reveal/pull/5084
=> feat(react-components): Render quality slider (BND3D-5504 season 2, part 2)

react-components/src/architecture/base/utilities/geometry/Range1.test.ts, react-components/src/architecture/base/utilities/geometry/Range1.ts, react-components/src/architecture/base/utilities/geometry/Range3.test.ts, react-components/src/architecture/base/utilities/geometry/Range3.ts, react-components/src/architecture/concrete/terrain/geometry/RegularGrid2.ts
* Unit tests
* Remove some unused functions
* Fixed a few thing found in the tests
=> test(react-components): Make unit test for the classes Range1 and Range3

react-components/src/architecture/base/utilities/geometry/getBoundingBoxFromPlanes.test.ts, react-components/src/architecture/base/utilities/geometry/getBoundingBoxFromPlanes.ts, react-components/src/architecture/base/utilities/geometry/getCorners.test.ts, react-components/src/architecture/base/utilities/geometry/isBoxVisibleByPlanes.test.ts, react-components/src/architecture/base/utilities/geometry/isBoxVisibleByPlanes.ts, react-components/src/architecture/concrete/annotations/AnnotationsView.ts
This is unit test only
Found a small bug and renamed one function in order to be more understandable
=> test(react-components): Make the unit tests for getCorners and getBoundingBoxFromPlanes

react-components/src/architecture/concrete/annotation360/createTriangleIndexesFromVectors.test.ts, react-components/src/architecture/concrete/annotation360/createTriangleIndexesFromVectors.ts
=> test(react-components): Create createTriangleIndexesFromVectors.test.ts

react-components/package.json
https://cognitedata.atlassian.net/browse/BND3D-5504
Bump react-components to 0.77.2
This is primarily for exposing the high-fidelity slider feature
=> chore: bump react-components to 0.77.2

react-components/.eslintrc.json, react-components/package.json, react-components/src/architecture/base/commands/BaseBannerCommand.ts, react-components/src/architecture/base/concreteCommands/SetQualityCommand.ts, react-components/src/architecture/base/concreteCommands/SetQualitySliderCommand/QualityWarningBannerCommand.ts, react-components/src/architecture/base/concreteCommands/SetQualitySliderCommand/SetQualitySliderCommand.ts, react-components/src/architecture/base/concreteCommands/SetQualitySliderCommand/fidelityLevels.test.ts, react-components/src/architecture/base/concreteCommands/SetQualitySliderCommand/fidelityLevels.ts, react-components/src/architecture/concrete/reveal/RevealSettingsController.ts, react-components/src/architecture/concrete/reveal/constants.ts, react-components/src/components/Architecture/BannerComponent.tsx, react-components/src/components/Architecture/SettingsButton.tsx, react-components/src/components/RevealToolbar/LayersButton/hooks/useModelHandlers.tsx, react-components/src/components/RevealToolbar/SettingsContainer/types.ts, react-components/src/data-providers/FdmSDK.ts, react-components/src/data-providers/core-dm-provider/assetsInstanceFilterWithHasDataQuery.ts, react-components/src/data-providers/core-dm-provider/cadAndPointCloudAndImage360AssetQuery.ts, react-components/src/data-providers/core-dm-provider/filterNodesByMappedTo3d.ts, react-components/src/data-providers/core-dm-provider/listMappedFdmNodes.ts, react-components/src/data-providers/types.ts, react-components/src/data-providers/utils/getCogniteAssetDirectRelationProperties.ts, react-components/src/query/useSearchMappedEquipmentFDM.tsx, react-components/src/utilities/instanceIds/typeGuards.ts
Lint setup has been broken for a little while which was not caught. This PR recovers the lint command as well as fixing all lint errors and warnings that accumulated while it was broken.
For review it is recommended to look at each commit in separation to gain ordering of the fix:
- Nr 1: fix the lint command
- Nr 2: apply eslint auto-fix
- Nr 3: manual intervention
- Nr 4: disabling of eslint for certain edge cases related to const inferring types which is extremly cumbersome to type out.
- Nr 5: set max allowed lint warnings to 0.
=> fix: lint setup

react-components/package.json, react-components/yarn.lock, viewer/package.json, viewer/yarn.lock
https://cognitedata.atlassian.net/browse/BND3D-5529
Fixes a [Major CVE](https://github.com/cognitedata/reveal/security/dependabot/541) and [moderate CVE](https://github.com/cognitedata/reveal/security/dependabot/556) (This has to be updated by user within CogniteData organization due private package install error during restrictions on DependBot access) security issue
=> chore: fixing axios and vite cve's

react-components/src/architecture/base/utilities/translateUtils.ts, react-components/src/components/i18n/I18n.test.tsx, react-components/src/components/i18n/I18n.tsx
This make sure that the app language is set at the new translation system from outside(i.e. Fusion)
=> chore(react-component): Make sure the app language is set in the new translation system

react-components/package.json
Bump the react-components version to create a new release.
This includes a a couple of fixes:
- Dropdown button interaction: https://github.com/cognitedata/reveal/pull/5126
- Disable comments on empty field: https://github.com/cognitedata/reveal/pull/5131
=> chore(react-components): bump version to 0.77.4

viewer/package.json
Primarily bumps ThreeJS-version to 176 and fixes a bug for CAD clicking in ThreeJS-versions > 167 (https://github.com/cognitedata/reveal/pull/5133)
=> chore: bump Reveal to 4.25.2

react-components/package.json
Bumps react-component to version 0.78.0
=> chore(react-components): bump to 0.78.0

react-components/package.json, react-components/src/components/RevealToolbar/LayersButton/components/ModelLayerSelection.tsx, react-components/yarn.lock
The layers submenu had an issue where it was appended within the main menu causing difficulty in selecting 3D model to unselect/select, this PR fixes the issue.
Issue Ref:
https://github.com/user-attachments/assets/116689c7-53a0-4a95-b750-0307d9cb5f83
Fixed Ref:
https://github.com/user-attachments/assets/d5dfa6d2-6c9b-4af8-bc66-2cc2056d0ed8
In Unified-3d and Search appliation
=> fix(react-components): layer submenu UI issue

react-components/src/components/Image360HistoricalDetails/Panel/Image360HistoricalPanel.tsx
The 360 Image Details button UI styling has issue in `Unified-3d` & `Search` as the styling scope fro respective application was overriding custom styling of cogs components set in react-component
Issue Ref:
Fixed Ref:
In Unified-3d & Search
=> fix(react-components): fix 360 image details button styling issue in unified-3d & Search application

react-components/package.json
Bumped react-components to v0.78.2
=> chore(react-components): bump react-components to v0.78.2

react-components/package.json
Bumps version. This release contains a new exposed search-function (not hook) to fetch/search classic assets connected to a set of 3D models/resources (#5167 , #5170 and #5171 )
=> chore(react-components): bump to version 0.79.0

react-components/package.json, react-components/yarn.lock
This reverts commit 3c7d15eb0b86631e5cfc60270949831527a7d4c5.
Reverts the updated Cogs-version, since it cascaded into many unnecessary updates in Fusion, and is no longer needed.
=> revert(react-components): "bumped cogs version to 10.47.0 (#5173)" and bump to 0.79.3

react-components/package.json
A new round version!
Bump bump
Changelog: 
- Filtering capabilities in new classic search function: https://github.com/cognitedata/reveal/pull/5184
- Fix UI updates on 360-image interactions: https://github.com/cognitedata/reveal/pull/5176
=> chore(react-component): bump to 0.80.0

react-components/src/architecture/concrete/pointsOfInterest/ads/PointsOfInterestAdsProvider.ts, react-components/src/architecture/concrete/pointsOfInterest/fdm/PointsOfInterestFdmProvider.ts
Remove usage of UUID package. It exists as a webAPI, and we had not declared it as a dependency, so we unintentionally bundle the entire package.
=> fix: remove usage of uuid package in favor of web api

.gemini/config.yaml
add gemini configuration for code review settings in config.yaml
=> feat: add gemini config for pr review

react-components/package.json, react-components/yarn.lock
=> chore: bump reveal

README.md
Update README with correct port for serving examples
=> docs(reveal): Update README with correct port

react-components/package.json
=> chore(react-components): bump to 0.82.0

react-components/package.json
Another bump, to incorporate new developments in measurement tools
=> chore(react-components): bump react-components to 0.82.2

react-components/src/architecture/base/concreteCommands/SettingsCommand.ts
https://cognitedata.atlassian.net/browse/BND3D-5769
Reorder settings items so that Point cloud items and 360 items are shown directly after the render settings
In Fusion
Use Storybook
- Click settings button
- Observe
=> improvement(react-components): change order of default Settings items

react-components/package.json
=> chore(react-components): bump react-components to v0.82.3

react-components/src/components/CacheProvider/cad/rawAssetMappingTypes.ts, react-components/src/query/index.ts, react-components/src/query/network/cad/fetchAllAssetsForCadModels.ts, react-components/src/query/network/cad/fetchAllHybridAssetMappingsForModels.ts, react-components/src/query/network/cad/fetchHybridAssetMappingsForModels.ts, react-components/src/query/network/cad/searchHybridDmAssetsForCadModels.ts, react-components/src/query/network/cad/searchHybridDmCadAssetMappingsWithFilters.ts, react-components/src/query/network/searchHybridDmAssetsForModels.test.ts, react-components/src/query/network/searchHybridDmAssetsForModels.ts, react-components/src/utilities/restrictToViewReference.ts, react-components/tests/tests-utilities/fixtures/cadAssetMapping.ts, react-components/tests/tests-utilities/fixtures/dm/viewDefinitions.ts
Solves https://cognitedata.atlassian.net/browse/BND3D-5827 (although, it needs to be used in Fusion too)
Introduces and exposes the `searchHybridDmAssetsForModels` function for searching in hybrid CAD asset mappings with DM instances. It supports both search with and without applied filters.
I'll mention that I'd ideally make this more object-oriented, with at least _some_ common interface(s) between this and the implementation for classic asset mappings; as it would at least make the tests a lot simpler, and probably make the code more re-usable. However, the nature of the two search paths is different due to differing backend capabilities (especially for the query-search), so I have put it off.
Also introduces some minor utilities for tests, and changes/extends typing related to raw …
=> feat(react-components): Hybrid CAD search

react-components/package.json
React-components version bump to `v0.83.0`
=> chore(react-components): react-components bump to v0.83.0

react-components/yarn.lock
Re-enactment of https://github.com/cognitedata/reveal/pull/5235, which cannot build because it's external
=> chore(react-components): bump brace expansion 1.1.12

react-components/src/architecture/base/domainObjectsHelpers/BaseCreator.ts
Compute matrix as class field to prevent cross test contamination for parallel test execution.
=> fix(react-components): move matrix to class field

react-components/package.json
Bump react-components to `v0.84.0`
=> chore(react-components): bump react-components to v0.84.0

react-components/package.json
Enables Hybrid CAD functionality for rule-based coloring
=> chore(react-components): bump to version 0.85.0

viewer/package.json
Bump viewer version to `4.26.0`
=> chore(viewer): Bump viewer version to 4.26.0

react-components/package.json
Release https://github.com/cognitedata/reveal/pull/5290
=> chore(react-components): bump to 0.85.1

react-components/package.json
=> chore(react-components): bump react-components to 0.85.3

react-components/package.json, react-components/yarn.lock
Updated @cognite/cdf-utilities to v5.0.0 for using standardize Date and Time method
In storybook and linked local build to fusion code base. It works fine
=> chore(react-component): update @cognite/cdf-utilities to v5.0.0

react-components/src/architecture/index.ts
export `RevealSettingsController`
=> chore(react-components): export RevealSettingsController

react-components/package.json
Release: 
#5315 
#5322
#5323 
#5313 
#5321 
#5318 
#5283 
#5319 
#5311 
#5306 
#5314 
#5308 
#5305 
#5304
=> chore(react-components): bump to 0.88.0

viewer/yarn.lock
https://cognitedata.atlassian.net/browse/BND3D-6066
Fix for dependbot issue [Axios is vulnerable to DoS attack through lack of data size check](https://github.com/cognitedata/reveal/security/dependabot/585)
=> chore: major CVE fix on axios package

react-components/package.json
Fix dependency issue regarding `@cognite/utilities` and bump version
=> chore(react-components): move cdf-utilities to normal dependencies and bump to 0.88.1

react-components/package.json, react-components/src/components/Architecture/pointsOfInterest/PoiHeader.tsx, react-components/src/components/Image360HistoricalDetails/Image360HistoricalDetails.viewmodel.context.ts, react-components/src/utilities/date-time-utils/constants.ts, react-components/src/utilities/date-time-utils/format-date-time.spec.ts, react-components/src/utilities/date-time-utils/format-date-time.ts, react-components/src/utilities/date-time-utils/index.ts, react-components/src/utilities/date-time-utils/types.ts, react-components/vite.config.ts, react-components/yarn.lock
We're having compatibility issues with the cdf-utilities package between react-components and some subapps in Fusion, such as fdx-pages, which also uses a datetime function. So, the solution for now is to port the function used in react-components to avoid importing cdf-utilities within react-components and avoid compatibility issues in tests.
The code is practically the same as that already in production for cdf-utilities.
This PR also redirects the locations that use the function that was previously imported from cdf-utilities.
It was tested in Fusion (in the locations where the Poi Header and image 360 ​​historical details are located), where datetimes are displayed. 
Unit tests were also tested in both react-components and Fusion.
**Note**: …
=> fix(react-components): port datetime format utils from cdf utilities and replace related places to fix cdf-utilities package issues

react-components/package.json
Releases:
https://github.com/cognitedata/reveal/pull/5338
=> chore(react-components): bump to 0.88.2

react-components/src/components/SceneContainer/SceneFdmTypes.tsx
Updated scene quality properties optional in `SceneConfigurationProperties` for `SceneResponse`
=> chore(react-components): update scene quality properties optional in SceneConfigurationProperties for SceneResponse

viewer/package.json
=> chore: bump reveal to v4.27.1

.github/workflows/publish-viewer-to-npm.yml
Fixes an issue where creating a Github release triggers an attempt to publish the package to NPM directly. Because of missing authorization for the Reveal CI.
Also renamed the file and action for clarity.
=> chore: rectify publish-on-release action
